import { ExternalLink } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { DeliveryTripDetailData } from "@/features/delivery/types";
import { formatDate, formatDateTime } from "@/lib/formatters";

const activityLabels: Record<string, string> = { DELIVERY_TRIP_CREATED: "สร้างรอบจัดส่ง", DELIVERY_TRIP_UPDATED: "แก้ไขรอบจัดส่ง", DELIVERY_ORDER_ASSIGNED: "เพิ่มคำสั่งซื้อ", DELIVERY_ORDER_REMOVED: "นำคำสั่งซื้อออก", DELIVERY_SEQUENCE_UPDATED: "จัดลำดับการจัดส่ง", DELIVERY_TRIP_LOADED: "ขึ้นสินค้า", DELIVERY_TRIP_DISPATCHED: "ออกรถจัดส่ง", DELIVERY_SUCCEEDED: "จัดส่งสำเร็จ", DELIVERY_FAILED: "จัดส่งไม่สำเร็จ", DELIVERY_STOCK_RETURNED: "คืนสินค้าเข้าคลัง", DELIVERY_TRIP_COMPLETED: "จบรอบจัดส่ง", DELIVERY_TRIP_CANCELLED: "ยกเลิกรอบจัดส่ง" };

export function DeliveryTripDetail({ trip }: { trip: DeliveryTripDetailData }) { return <div className="grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><div className="space-y-4"><Card><CardHeader><CardTitle>ข้อมูลรอบจัดส่ง</CardTitle></CardHeader><CardContent><dl className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><Info label="วันที่จัดส่ง" value={formatDate(trip.plannedDate)} /><Info label="คลังต้นทาง" value={trip.warehouseName} /><Info label="รถจัดส่ง" value={trip.vehicleCode ? `${trip.vehiclePlate} (${trip.vehicleCode})` : trip.vehiclePlate} /><Info label="พนักงานขับรถ" value={trip.driverName} /><Info label="ออกจากคลัง" value={trip.departedAt ? formatDateTime(trip.departedAt) : "—"} /><Info label="กลับถึงคลัง" value={trip.returnedAt ? formatDateTime(trip.returnedAt) : "—"} /></dl>{trip.notes && <div className="mt-4 border-t pt-4"><p className="text-sm text-muted-foreground">หมายเหตุ</p><p className="mt-1 whitespace-pre-wrap text-sm">{trip.notes}</p></div>}</CardContent></Card><Card><CardHeader><CardTitle>สถานะสินค้าและคลังรถ</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">เมื่อขึ้นสินค้า ระบบโอนจาก {trip.warehouseName} ไปยัง {trip.vehicleWarehouseName ?? "คลังรถ"} และตัดเป็นการขายเมื่อบันทึกจัดส่งสำเร็จเท่านั้น</p>{trip.vehicleWarehouseId && <Button className="mt-3" size="sm" variant="outline" asChild><Link href={`/inventory/stock?warehouseId=${trip.vehicleWarehouseId}`}><ExternalLink className="size-4" aria-hidden="true" />ดูสต็อกคลังรถ</Link></Button>}</CardContent></Card></div><div className="space-y-4"><Card><CardHeader><CardTitle>ข้อมูลเอกสาร</CardTitle></CardHeader><CardContent><dl className="space-y-3 text-sm"><Info label="สร้างโดย" value={trip.createdByName} /><Info label="สร้างเมื่อ" value={formatDateTime(trip.createdAt)} /><Info label="แก้ไขล่าสุด" value={formatDateTime(trip.updatedAt)} /></dl></CardContent></Card><Card><CardHeader><CardTitle>กิจกรรม</CardTitle></CardHeader><CardContent>{trip.activity.length ? <ol className="space-y-3">{trip.activity.map((activity) => <li key={activity.id} className="border-l-2 pl-3 text-sm"><p className="font-medium">{activityLabels[activity.action] ?? activity.action}</p><p className="type-caption">{formatDateTime(activity.createdAt)} · {activity.actorName}</p></li>)}</ol> : <p className="text-sm text-muted-foreground">ยังไม่มีกิจกรรม</p>}</CardContent></Card></div></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
