"use client";

import { Pencil, Plus } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";
import { FormField } from "@/components/shared/form-layout";
import { StatusBadge } from "@/components/shared/status-badge";
import { useToast } from "@/components/shared/toast-provider";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { changeVehicleStatusAction, saveVehicleAction } from "@/features/delivery/actions";
import type { VehicleRow } from "@/features/delivery/types";
import { vehicleFormSchema, type VehicleFormValues } from "@/validations/delivery";

function VehicleDialog({ vehicle, onClose }: { vehicle?: VehicleRow; onClose: () => void }) { const router = useRouter(); const { toast } = useToast(); const form = useForm<VehicleFormValues>({ resolver: zodResolver(vehicleFormSchema), defaultValues: vehicle ? { id: vehicle.id, code: vehicle.code, registrationNumber: vehicle.registrationNumber, description: vehicle.description ?? "" } : { code: "", registrationNumber: "", description: "" } }); async function submit(values: VehicleFormValues) { const result = await saveVehicleAction(values); if (!result.ok) { form.setError("root", { message: result.message }); return; } toast({ variant: "success", title: vehicle ? "บันทึกรถจัดส่งแล้ว" : "เพิ่มรถจัดส่งแล้ว" }); onClose(); router.refresh(); } return <Dialog open onOpenChange={(open) => { if (!open && !form.formState.isSubmitting) onClose(); }}><DialogContent><DialogHeader><DialogTitle>{vehicle ? "แก้ไขรถจัดส่ง" : "เพิ่มรถจัดส่ง"}</DialogTitle><DialogDescription>ระบบจะสร้างคลังรถอัตโนมัติเพื่อติดตามสินค้าที่ขึ้นรถ</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={form.handleSubmit(submit)} noValidate>{form.formState.errors.root?.message && <Alert variant="danger"><AlertDescription>{form.formState.errors.root.message}</AlertDescription></Alert>}<FormField label="รหัสรถ" htmlFor="vehicle-code" required error={form.formState.errors.code?.message}><Input id="vehicle-code" {...form.register("code")} /></FormField><FormField label="ทะเบียนรถ" htmlFor="vehicle-registration" required error={form.formState.errors.registrationNumber?.message}><Input id="vehicle-registration" {...form.register("registrationNumber")} /></FormField><FormField label="คำอธิบาย" htmlFor="vehicle-description" error={form.formState.errors.description?.message}><Textarea id="vehicle-description" rows={3} {...form.register("description")} /></FormField><DialogFooter><Button type="button" variant="outline" onClick={onClose} disabled={form.formState.isSubmitting}>ยกเลิก</Button><Button type="submit" loading={form.formState.isSubmitting}>บันทึก</Button></DialogFooter></form></DialogContent></Dialog>; }

export function VehicleManagement({ vehicles, canManage }: { vehicles: VehicleRow[]; canManage: boolean }) { const router = useRouter(); const { toast } = useToast(); const [editing, setEditing] = useState<VehicleRow | null | undefined>(); async function toggle(vehicle: VehicleRow) { const result = await changeVehicleStatusAction({ id: vehicle.id, status: vehicle.status === "ACTIVE" ? "INACTIVE" : "ACTIVE" }); if (!result.ok) { toast({ variant: "danger", title: result.message }); return; } toast({ variant: "success", title: "อัปเดตสถานะรถจัดส่งแล้ว" }); router.refresh(); } return <><div className="mb-3 flex justify-end">{canManage && <Button size="sm" onClick={() => setEditing(null)}><Plus className="size-4" aria-hidden="true" />เพิ่มรถจัดส่ง</Button>}</div><div className="grid gap-3 lg:grid-cols-2">{vehicles.map((vehicle) => <Card key={vehicle.id}><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{vehicle.registrationNumber}</p><p className="type-caption tabular-nums">{vehicle.code}</p></div><StatusBadge status={vehicle.status === "ACTIVE" ? "active" : "inactive"} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">คลังรถ</dt><dd className="mt-1 font-medium">{vehicle.warehouseName}</dd></div><div><dt className="text-muted-foreground">สต็อกปัจจุบัน</dt><dd className="mt-1 font-medium tabular-nums">{vehicle.stockItemCount} สินค้า</dd></div><div><dt className="text-muted-foreground">รอบจัดส่ง</dt><dd className="mt-1 font-medium tabular-nums">{vehicle.tripCount} รอบ</dd></div><div><dt className="text-muted-foreground">รายละเอียด</dt><dd className="mt-1 font-medium">{vehicle.description ?? "—"}</dd></div></dl><div className="mt-4 flex flex-wrap justify-end gap-2"><Button size="sm" variant="outline" asChild><Link href={`/inventory/stock?warehouseId=${vehicle.warehouseId}`}>ดูสต็อก</Link></Button>{canManage && <><Button size="sm" variant="outline" onClick={() => setEditing(vehicle)}><Pencil className="size-4" aria-hidden="true" />แก้ไข</Button><ConfirmDialog trigger={<Button size="sm" variant="ghost">{vehicle.status === "ACTIVE" ? "ปิดใช้" : "เปิดใช้"}</Button>} title={`${vehicle.status === "ACTIVE" ? "ปิด" : "เปิด"}ใช้งานรถจัดส่ง?`} description={vehicle.status === "ACTIVE" ? "ปิดได้เมื่อคลังรถไม่มีสินค้าเหลืออยู่" : "รถและคลังรถจะพร้อมใช้สำหรับรอบใหม่"} confirmLabel="ยืนยัน" destructive={vehicle.status === "ACTIVE"} onConfirm={() => toggle(vehicle)} /></>}</div></CardContent></Card>)}{!vehicles.length && <div className="rounded-md border border-dashed p-8 text-center text-sm text-muted-foreground lg:col-span-2">ยังไม่มีรถจัดส่ง</div>}</div>{editing !== undefined && <VehicleDialog vehicle={editing ?? undefined} onClose={() => setEditing(undefined)} />}</>; }
