"use server";

import { revalidatePath } from "next/cache";
import { requireAnyPermission, requirePermission } from "@/services/auth.service";
import { resolveProductUnitPrice } from "@/services/pricing.service";
import { createSalesOrder, SalesOrderRuleError, transitionSalesOrderStatus, updateSalesOrder } from "@/services/sales-order.service";
import { getSalesSettings } from "@/services/settings.service";
import { salesOrderFormSchema, salesOrderPriceResolutionSchema, salesOrderTransitionSchema } from "@/validations/sales-order";

export type SalesOrderActionResult = { ok: true; id: string } | { ok: false; message: string };
function actor(context: Awaited<ReturnType<typeof requirePermission>>) { return { id: context.user.id === "development-preview" ? null : context.user.id, name: context.user.name }; }
function errorResult(error: unknown): SalesOrderActionResult { if (error instanceof SalesOrderRuleError) return { ok: false, message: error.message }; if (typeof error === "object" && error && "code" in error && (error.code === "P2034" || error.code === "P2002")) return { ok: false, message: "ข้อมูลมีการเปลี่ยนแปลงพร้อมกัน กรุณาโหลดหน้าใหม่แล้วลองอีกครั้ง" }; console.error("Sales order action failed", error); return { ok: false, message: "ไม่สามารถดำเนินการคำสั่งซื้อได้ กรุณาลองอีกครั้ง" }; }
function refresh(id?: string) { revalidatePath("/sales/orders"); if (id) revalidatePath(`/sales/orders/${id}`); }

export async function createSalesOrderAction(input: unknown): Promise<SalesOrderActionResult> { const parsed = salesOrderFormSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("sales_order.create"); try { const settings = await getSalesSettings(); const id = await createSalesOrder(parsed.data, actor(access), settings.allowManualPriceOverride && access.permissions.includes("sales_order.override_price")); refresh(id); return { ok: true, id }; } catch (error) { return errorResult(error); } }
export async function updateSalesOrderAction(input: unknown): Promise<SalesOrderActionResult> { const parsed = salesOrderFormSchema.safeParse(input); if (!parsed.success || !parsed.data.id) return { ok: false, message: parsed.success ? "ไม่พบรหัสคำสั่งซื้อ" : parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("sales_order.update"); try { const settings = await getSalesSettings(); const id = await updateSalesOrder({ ...parsed.data, id: parsed.data.id }, actor(access), settings.allowManualPriceOverride && access.permissions.includes("sales_order.override_price")); refresh(id); return { ok: true, id }; } catch (error) { return errorResult(error); } }
export async function transitionSalesOrderAction(input: unknown): Promise<SalesOrderActionResult> { const parsed = salesOrderTransitionSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const permission = parsed.data.toStatus === "CONFIRMED" ? "sales_order.confirm" : "sales_order.cancel"; const access = await requirePermission(permission); try { const id = await transitionSalesOrderStatus(parsed.data.id, parsed.data.toStatus, parsed.data.note, actor(access)); refresh(id); return { ok: true, id }; } catch (error) { return errorResult(error); } }
export async function resolveSalesOrderPriceAction(input: unknown) { const parsed = salesOrderPriceResolutionSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; await requireAnyPermission(["sales_order.create", "sales_order.update"]); try { return { ok: true as const, price: await resolveProductUnitPrice(parsed.data) }; } catch (error) { return { ok: false as const, message: error instanceof Error ? error.message : "ไม่สามารถคำนวณราคาได้" }; } }
