import type { SalesOrderStatusValue } from "@/config/sales-orders";
import type { SalesOrderFormValues } from "@/validations/sales-order";

export type OrderCustomerOption = { id: string; code: string; displayName: string; legalName: string; type: "RETAIL" | "WHOLESALE"; status: "ACTIVE"; phone: string | null; defaultSaleType: "CASH" | "CREDIT"; creditTermDays: number; creditLimit: string; billingCycle: string; billingCycleNote: string | null; defaultPriceList: { id: string; code: string; name: string } | null };
export type OrderProductOption = { id: string; productId: string; unitId: string; sku: string; name: string; barcode: string | null; unitName: string; unitSymbol: string; decimalScale: number };
export type WarehouseOption = { id: string; code: string; name: string; isDefault: boolean };
export type SalesOrderOptions = { customers: OrderCustomerOption[]; products: OrderProductOption[]; warehouses: WarehouseOption[] };
export type SalesOrderRow = { id: string; orderNo: string; orderDate: string; requestedDeliveryDate: string | null; customerCodeSnapshot: string; customerNameSnapshot: string; customerType: "RETAIL" | "WHOLESALE"; saleType: "CASH" | "CREDIT"; status: SalesOrderStatusValue; totalAmount: string; salesperson: string; updatedAt: string };
export type SalesOrderDetailData = Omit<SalesOrderFormValues, "items"> & { id: string; orderNo: string; status: SalesOrderStatusValue; customerType?: "RETAIL" | "WHOLESALE"; customerCodeSnapshot: string; customerNameSnapshot: string; creditTermDaysSnapshot: number; creditLimitSnapshot: string; subtotal: string; discountAmount: string; taxAmount: string; totalAmount: string; createdByName: string; createdAt: string; updatedAt: string; warehouseName: string; priceListName: string | null; items: Array<SalesOrderFormValues["items"][number] & { lineNo: number; productNameSnapshot: string; skuSnapshot: string; unitNameSnapshot: string; lineSubtotal: string; taxAmount: string; lineTotal: string; isPriceOverridden: boolean }>; statusHistory: Array<{ id: string; fromStatus: SalesOrderStatusValue | null; toStatus: SalesOrderStatusValue; changedByName: string | null; note: string | null; changedAt: string }>; activity: Array<{ id: string; action: string; actorName: string | null; createdAt: string }> };
