import "server-only";

import type { Prisma } from "@/generated/prisma/client";
import { BUSINESS_TIMEZONE } from "@/constants/app";
import { addBusinessDays, addMoney, agingBucket, calculateOutstanding, compareMoney, daysOverdue, deriveInvoiceStatus, subtractMoney, type AgingBucket } from "@/services/accounting-core";
import * as repository from "@/repositories/accounting.repository";
import type { BillingCreateValues, InvoiceCreateValues, PaymentCreateValues } from "@/validations/accounting";

export class AccountingRuleError extends Error {}
type Actor = { id: string | null; name: string };
const activeInvoiceStatuses = ["ISSUED", "PARTIALLY_PAID", "OVERDUE"] as const;
const activeBillingStatuses = ["DRAFT", "ISSUED", "PARTIALLY_PAID", "OVERDUE"] as const;
function dateKey(value: Date) { return value.toISOString().slice(0, 10); }
function businessDate(value: string) { return new Date(`${value}T00:00:00.000Z`); }
export function todayInBangkok(now = new Date()) { return new Intl.DateTimeFormat("en-CA", { timeZone: BUSINESS_TIMEZONE, year: "numeric", month: "2-digit", day: "2-digit" }).format(now); }
function yearMonth(value: string) { return value.slice(0, 7).replace("-", ""); }
function json(value: object): Prisma.InputJsonValue { return value as Prisma.InputJsonValue; }
function paidAmounts(allocations: Array<{ amount: { toString(): string } }>) { return allocations.map((allocation) => allocation.amount.toString()); }
function outstanding(total: { toString(): string }, allocations: Array<{ amount: { toString(): string } }>) { return calculateOutstanding(total.toString(), paidAmounts(allocations)); }
function unique(values: string[]) { return [...new Set(values)]; }

export async function getEligibleInvoiceOrders() { const rows = await repository.listEligibleInvoiceOrders(); return rows.map((row) => ({ ...row, orderDate: dateKey(row.orderDate), totalAmount: row.totalAmount.toString() })); }

export async function createInvoice(input: InvoiceCreateValues, actor: Actor) {
  return repository.withAccountingTransaction(async (tx) => {
    const order = await repository.findOrderForInvoice(tx, input.salesOrderId);
    if (!order) throw new AccountingRuleError("ไม่พบคำสั่งซื้อ");
    if (order.status !== "DELIVERED") throw new AccountingRuleError("สร้างใบแจ้งหนี้ได้เฉพาะคำสั่งซื้อที่จัดส่งสำเร็จแล้ว");
    if (order.invoices.length) throw new AccountingRuleError("คำสั่งซื้อนี้มีใบแจ้งหนี้ที่ยังใช้งานอยู่แล้ว");
    if (!order.items.length || compareMoney(order.totalAmount.toString(), "0.00") <= 0) throw new AccountingRuleError("คำสั่งซื้อไม่มีรายการหรือยอดรวมไม่ถูกต้อง");
    const billingAddress = order.billingAddress ?? order.shippingAddress;
    if (!billingAddress) throw new AccountingRuleError("คำสั่งซื้อไม่มีที่อยู่ออกใบแจ้งหนี้");
    const dueDate = addBusinessDays(input.invoiceDate, order.saleType === "CASH" ? 0 : order.creditTermDaysSnapshot);
    const invoiceNo = await repository.nextAccountingNumber(tx, "INV", yearMonth(input.invoiceDate));
    const invoice = await repository.createInvoiceRecord(tx, { invoiceNo, customerId: order.customerId, salesOrderId: order.id, status: "DRAFT", customerCodeSnapshot: order.customerCodeSnapshot, customerNameSnapshot: order.customerNameSnapshot, taxIdSnapshot: order.customer.taxId, taxBranchCodeSnapshot: order.customer.taxBranchCode, creditTermDaysSnapshot: order.saleType === "CASH" ? 0 : order.creditTermDaysSnapshot, invoiceDate: businessDate(input.invoiceDate), dueDate: businessDate(dueDate), currency: order.currency, billingAddress: billingAddress as Prisma.InputJsonValue, subtotal: order.subtotal, discountAmount: order.discountAmount, taxAmount: order.taxAmount, totalAmount: order.totalAmount, notes: input.notes || null, createdById: actor.id });
    await repository.createInvoiceItems(tx, order.items.map((item) => ({ invoiceId: invoice.id, lineNo: item.lineNo, salesOrderItemId: item.id, productId: item.productId, productUnitId: item.productUnitId, description: item.description, productNameSnapshot: item.productNameSnapshot, skuSnapshot: item.skuSnapshot, unitNameSnapshot: item.unitNameSnapshot, quantity: item.quantity, unitPrice: item.unitPrice, lineSubtotal: item.lineSubtotal, discountAmount: item.discountAmount, taxRate: item.taxRate, taxAmount: item.taxAmount, lineTotal: item.lineTotal })));
    await repository.createAccountingAudit(tx, { actorId: actor.id, actorName: actor.name, action: "INVOICE_CREATED", entityType: "Invoice", entityId: invoice.id, afterData: json({ invoiceNo, salesOrderId: order.id, status: "DRAFT", totalAmount: order.totalAmount.toString(), dueDate }) });
    return invoice.id;
  });
}

export async function issueInvoice(id: string, actor: Actor) { return repository.withAccountingTransaction(async (tx) => { const invoice = await repository.findInvoiceForUpdate(tx, id); if (!invoice) throw new AccountingRuleError("ไม่พบใบแจ้งหนี้"); if (invoice.status === "VOID") throw new AccountingRuleError("ไม่สามารถออกใบแจ้งหนี้ที่ยกเลิกแล้วซ้ำได้"); if (invoice.status !== "DRAFT") return invoice.id; if (!invoice.items.length || !invoice.customerCodeSnapshot || !invoice.customerNameSnapshot || compareMoney(invoice.totalAmount.toString(), "0.00") <= 0) throw new AccountingRuleError("ข้อมูลใบแจ้งหนี้ไม่ครบถ้วน"); await repository.updateInvoiceRecord(tx, id, { status: "ISSUED", issuedAt: new Date() }); if (invoice.salesOrderId) await repository.completeSalesOrderForInvoice(tx, { id: invoice.salesOrderId, actorId: actor.id, actorName: actor.name }); await repository.createAccountingAudit(tx, { actorId: actor.id, actorName: actor.name, action: "INVOICE_ISSUED", entityType: "Invoice", entityId: id, beforeData: json({ status: "DRAFT" }), afterData: json({ status: "ISSUED" }) }); return id; }); }

export async function voidInvoice(id: string, reason: string, actor: Actor) { return repository.withAccountingTransaction(async (tx) => { const invoice = await repository.findInvoiceForUpdate(tx, id); if (!invoice) throw new AccountingRuleError("ไม่พบใบแจ้งหนี้"); if (invoice.status === "VOID") return id; if (invoice.paymentAllocations.length) throw new AccountingRuleError("ไม่สามารถยกเลิกใบแจ้งหนี้ที่มีการจัดสรรยอดชำระแล้ว"); if (invoice.billingNotes.some(({ billingNote }) => activeBillingStatuses.includes(billingNote.status as typeof activeBillingStatuses[number]))) throw new AccountingRuleError("ต้องยกเลิกใบวางบิลที่เกี่ยวข้องก่อน"); await repository.updateInvoiceRecord(tx, id, { status: "VOID", voidedAt: new Date(), voidReason: reason }); await repository.createAccountingAudit(tx, { actorId: actor.id, actorName: actor.name, action: "INVOICE_VOIDED", entityType: "Invoice", entityId: id, beforeData: json({ status: invoice.status }), afterData: json({ status: "VOID", reason }) }); return id; }); }

export async function getInvoiceList(input: { q?: string; status?: string; page?: number; pageSize?: number }) { const page = Math.max(1, input.page ?? 1); const pageSize = [20, 50, 100].includes(input.pageSize ?? 20) ? input.pageSize ?? 20 : 20; const allowedStatuses = ["ALL", "DRAFT", "ISSUED", "PARTIALLY_PAID", "PAID", "OVERDUE", "VOID"]; const status = allowedStatuses.includes(input.status ?? "ALL") ? input.status : "ALL"; const asOfDate = todayInBangkok(); const result = await repository.listInvoices({ q: input.q?.trim().slice(0, 120), status, asOfDate: businessDate(asOfDate), page, pageSize }); return { ...result, page, pageSize, rows: result.rows.map((row) => { const paid = addMoney(paidAmounts(row.paymentAllocations)); const balance = calculateOutstanding(row.totalAmount.toString(), [paid]); const derivedStatus = row.status === "DRAFT" || row.status === "VOID" ? row.status : deriveInvoiceStatus({ total: row.totalAmount.toString(), outstanding: balance, dueDate: dateKey(row.dueDate), asOfDate }); return { id: row.id, invoiceNo: row.invoiceNo, invoiceDate: dateKey(row.invoiceDate), dueDate: dateKey(row.dueDate), customerCode: row.customerCodeSnapshot, customerName: row.customerNameSnapshot, orderNo: row.salesOrder?.orderNo ?? null, totalAmount: row.totalAmount.toString(), paidAmount: paid, outstandingAmount: balance, status: derivedStatus }; }) }; }

export async function getInvoice(id: string) { const [row, activity] = await Promise.all([repository.findInvoiceDetail(id), repository.listInvoiceAuditLogs(id)]); if (!row) return null; const completed = row.paymentAllocations.filter((allocation) => allocation.payment.status === "COMPLETED"); const paidAmount = addMoney(completed.map((allocation) => allocation.amount.toString())); const outstandingAmount = calculateOutstanding(row.totalAmount.toString(), [paidAmount]); const asOfDate = todayInBangkok(); const status = row.status === "DRAFT" || row.status === "VOID" ? row.status : deriveInvoiceStatus({ total: row.totalAmount.toString(), outstanding: outstandingAmount, dueDate: dateKey(row.dueDate), asOfDate }); return { ...row, status, invoiceDate: dateKey(row.invoiceDate), dueDate: dateKey(row.dueDate), subtotal: row.subtotal.toString(), discountAmount: row.discountAmount.toString(), taxAmount: row.taxAmount.toString(), totalAmount: row.totalAmount.toString(), paidAmount, outstandingAmount, items: row.items.map((item) => ({ ...item, quantity: item.quantity.toString(), unitPrice: item.unitPrice.toString(), lineSubtotal: item.lineSubtotal.toString(), discountAmount: item.discountAmount.toString(), taxRate: item.taxRate.toString(), taxAmount: item.taxAmount.toString(), lineTotal: item.lineTotal.toString(), createdAt: item.createdAt.toISOString(), updatedAt: item.updatedAt.toISOString() })), paymentAllocations: row.paymentAllocations.map((allocation) => ({ ...allocation, amount: allocation.amount.toString(), allocatedAt: allocation.allocatedAt.toISOString(), payment: { ...allocation.payment, paymentDate: dateKey(allocation.payment.paymentDate) } })), activity: activity.map((event) => ({ ...event, createdAt: event.createdAt.toISOString() })) };
}

export async function getAccountingCustomers() { const rows = await repository.listAccountingCustomers(); return rows.map((row) => ({ ...row, creditLimit: row.creditLimit.toString() })); }
export async function getOutstandingInvoices(customerId: string) { const rows = await repository.listOutstandingInvoicesForCustomer(customerId); return rows.map((row) => { const paidAmount = addMoney(paidAmounts(row.paymentAllocations)); return { id: row.id, invoiceNo: row.invoiceNo, invoiceDate: dateKey(row.invoiceDate), dueDate: dateKey(row.dueDate), totalAmount: row.totalAmount.toString(), paidAmount, outstandingAmount: calculateOutstanding(row.totalAmount.toString(), [paidAmount]), activeBilling: row.billingNotes[0]?.billingNote ?? null }; }).filter((row) => compareMoney(row.outstandingAmount, "0.00") > 0); }

export async function createBillingNote(input: BillingCreateValues, actor: Actor) { return repository.withAccountingTransaction(async (tx) => { const ids = unique(input.invoiceIds); await repository.lockInvoices(tx, ids); const invoices = await repository.findInvoicesForAccounting(tx, ids); if (invoices.length !== ids.length) throw new AccountingRuleError("ไม่พบใบแจ้งหนี้บางรายการ"); if (invoices.some((invoice) => invoice.customerId !== input.customerId)) throw new AccountingRuleError("ใบวางบิลต้องรวมใบแจ้งหนี้ของลูกค้ารายเดียวกัน"); const amounts = invoices.map((invoice) => { if (!activeInvoiceStatuses.includes(invoice.status as typeof activeInvoiceStatuses[number])) throw new AccountingRuleError("ใบแจ้งหนี้บางรายการยังไม่พร้อมวางบิล"); if (invoice.billingNotes.length) throw new AccountingRuleError("ใบแจ้งหนี้บางรายการอยู่ในใบวางบิลที่ยังใช้งานอยู่แล้ว"); const amount = outstanding(invoice.totalAmount, invoice.paymentAllocations); if (compareMoney(amount, "0.00") <= 0) throw new AccountingRuleError("ใบแจ้งหนี้บางรายการชำระครบแล้ว"); return { invoiceId: invoice.id, amount }; }); const totalAmount = addMoney(amounts.map(({ amount }) => amount)); const billingNo = await repository.nextAccountingNumber(tx, "BL", yearMonth(input.billingDate)); const billing = await repository.createBillingRecord(tx, { billingNo, customerId: input.customerId, status: "DRAFT", billingDate: businessDate(input.billingDate), dueDate: businessDate(input.dueDate), totalAmount, notes: input.notes || null, createdById: actor.id }); await repository.createBillingInvoiceRecords(tx, amounts.map(({ invoiceId, amount }) => ({ billingNoteId: billing.id, invoiceId, amount }))); await repository.createAccountingAudit(tx, { actorId: actor.id, actorName: actor.name, action: "BILLING_NOTE_CREATED", entityType: "BillingNote", entityId: billing.id, afterData: json({ billingNo, invoiceIds: ids, totalAmount }) }); return billing.id; }); }
export async function issueBillingNote(id: string, actor: Actor) { return repository.withAccountingTransaction(async (tx) => { const billing = await repository.findBillingForUpdate(tx, id); if (!billing) throw new AccountingRuleError("ไม่พบใบวางบิล"); if (billing.status === "CANCELLED") throw new AccountingRuleError("ไม่สามารถออกใบวางบิลที่ยกเลิกแล้วซ้ำได้"); if (billing.status !== "DRAFT") return id; if (!billing.invoices.length || compareMoney(billing.totalAmount.toString(), "0.00") <= 0) throw new AccountingRuleError("ใบวางบิลไม่มีรายการที่ถูกต้อง"); await repository.updateBillingRecord(tx, id, { status: "ISSUED", issuedAt: new Date() }); await repository.createAccountingAudit(tx, { actorId: actor.id, actorName: actor.name, action: "BILLING_NOTE_ISSUED", entityType: "BillingNote", entityId: id, beforeData: json({ status: "DRAFT" }), afterData: json({ status: "ISSUED" }) }); return id; }); }
export async function cancelBillingNote(id: string, reason: string, actor: Actor) { return repository.withAccountingTransaction(async (tx) => { const billing = await repository.findBillingForUpdate(tx, id); if (!billing) throw new AccountingRuleError("ไม่พบใบวางบิล"); if (billing.status === "CANCELLED") return id; if (billing.paymentAllocations.some((allocation) => allocation.payment.status === "COMPLETED")) throw new AccountingRuleError("ไม่สามารถยกเลิกใบวางบิลที่มีการรับชำระแล้ว"); await repository.updateBillingRecord(tx, id, { status: "CANCELLED", cancelledAt: new Date(), cancelReason: reason }); await repository.createAccountingAudit(tx, { actorId: actor.id, actorName: actor.name, action: "BILLING_NOTE_CANCELLED", entityType: "BillingNote", entityId: id, beforeData: json({ status: billing.status }), afterData: json({ status: "CANCELLED", reason }) }); return id; }); }

function billingOutstanding(invoiceLinks: Array<{ invoice: { totalAmount: { toString(): string }; paymentAllocations: Array<{ amount: { toString(): string } }> } }>) { return addMoney(invoiceLinks.map(({ invoice }) => outstanding(invoice.totalAmount, invoice.paymentAllocations))); }
export async function getBillingList() { const rows = await repository.listBillingNotes(); return rows.map((row) => ({ id: row.id, billingNo: row.billingNo, billingDate: dateKey(row.billingDate), dueDate: dateKey(row.dueDate), customerCode: row.customer.code, customerName: row.customer.displayName, totalAmount: row.totalAmount.toString(), outstandingAmount: billingOutstanding(row.invoices), invoiceCount: row._count.invoices, status: row.status })); }
export async function getBillingNote(id: string) { const row = await repository.findBillingDetail(id); if (!row) return null; return { ...row, billingDate: dateKey(row.billingDate), dueDate: dateKey(row.dueDate), totalAmount: row.totalAmount.toString(), outstandingAmount: billingOutstanding(row.invoices), invoices: row.invoices.map((link) => { const paidAmount = addMoney(paidAmounts(link.invoice.paymentAllocations)); return { ...link, amount: link.amount.toString(), invoice: { ...link.invoice, invoiceDate: dateKey(link.invoice.invoiceDate), dueDate: dateKey(link.invoice.dueDate), totalAmount: link.invoice.totalAmount.toString(), paidAmount, outstandingAmount: calculateOutstanding(link.invoice.totalAmount.toString(), [paidAmount]) } }; }), paymentAllocations: row.paymentAllocations.filter((allocation) => allocation.payment.status === "COMPLETED").map((allocation) => ({ ...allocation, amount: allocation.amount.toString(), allocatedAt: allocation.allocatedAt.toISOString(), payment: { ...allocation.payment, paymentDate: dateKey(allocation.payment.paymentDate) } })) };
}

async function recalculateInvoice(tx: repository.AccountingTransaction, invoiceId: string, asOfDate: string) { const rows = await repository.findInvoicesForAccounting(tx, [invoiceId]); const invoice = rows[0]; if (!invoice || invoice.status === "DRAFT" || invoice.status === "VOID") return; const balance = outstanding(invoice.totalAmount, invoice.paymentAllocations); const status = deriveInvoiceStatus({ total: invoice.totalAmount.toString(), outstanding: balance, dueDate: dateKey(invoice.dueDate), asOfDate }); await repository.updateInvoiceRecord(tx, invoice.id, { status }); }
async function recalculateBilling(tx: repository.AccountingTransaction, billingId: string, asOfDate: string) { const billing = await repository.findBillingForUpdate(tx, billingId); if (!billing || billing.status === "DRAFT" || billing.status === "CANCELLED") return; const balance = billingOutstanding(billing.invoices); const status = compareMoney(balance, "0.00") === 0 ? "PAID" : dateKey(billing.dueDate) < asOfDate ? "OVERDUE" : compareMoney(balance, billing.totalAmount.toString()) < 0 ? "PARTIALLY_PAID" : "ISSUED"; await repository.updateBillingRecord(tx, billing.id, { status }); }

export async function recordPayment(input: PaymentCreateValues, actor: Actor) {
  return repository.withAccountingTransaction(async (tx) => {
    const existing = await repository.findPaymentByIdempotencyKey(tx, input.idempotencyKey); if (existing) return existing.id;
    const allocations = input.allocations.filter((allocation) => compareMoney(allocation.amount, "0.00") > 0); const ids = unique(allocations.map(({ invoiceId }) => invoiceId));
    if (ids.length !== allocations.length) throw new AccountingRuleError("ใบแจ้งหนี้ซ้ำในรายการจัดสรรยอดชำระ");
    await repository.lockInvoices(tx, ids); const invoices = await repository.findInvoicesForAccounting(tx, ids);
    if (invoices.length !== ids.length) throw new AccountingRuleError("ไม่พบใบแจ้งหนี้บางรายการ");
    const byId = new Map(invoices.map((invoice) => [invoice.id, invoice]));
    for (const allocation of allocations) { const invoice = byId.get(allocation.invoiceId)!; if (invoice.customerId !== input.customerId || !activeInvoiceStatuses.includes(invoice.status as typeof activeInvoiceStatuses[number])) throw new AccountingRuleError("ใบแจ้งหนี้ไม่อยู่ในขอบเขตลูกค้าหรือสถานะที่รับชำระได้"); if (compareMoney(allocation.amount, outstanding(invoice.totalAmount, invoice.paymentAllocations)) > 0) throw new AccountingRuleError(`ยอดจัดสรรเกินยอดค้างชำระของ ${invoice.invoiceNo}`); if (input.billingNoteId && !invoice.billingNotes.some((link) => link.billingNoteId === input.billingNoteId)) throw new AccountingRuleError("ใบวางบิลไม่มีใบแจ้งหนี้ที่เลือก"); }
    const allocatedAmount = addMoney(allocations.map(({ amount }) => amount)); if (compareMoney(allocatedAmount, input.amount) > 0) throw new AccountingRuleError("ยอดจัดสรรรวมเกินยอดรับชำระ");
    const paymentNo = await repository.nextAccountingNumber(tx, "PAY", yearMonth(input.paymentDate));
    const payment = await repository.createPaymentRecord(tx, { paymentNo, idempotencyKey: input.idempotencyKey, customerId: input.customerId, status: "PENDING", method: input.method, paymentDate: businessDate(input.paymentDate), amount: input.amount, externalReference: input.externalReference || null, receivedAccount: input.receivedAccount || null, notes: input.notes || null, recordedById: actor.id });
    if (allocations.length) await repository.createPaymentAllocationRecords(tx, allocations.map((allocation) => ({ paymentId: payment.id, invoiceId: allocation.invoiceId, billingNoteId: input.billingNoteId ?? null, amount: allocation.amount })));
    await repository.updatePaymentRecord(tx, payment.id, { status: "COMPLETED", completedAt: new Date() });
    for (const invoiceId of ids) await recalculateInvoice(tx, invoiceId, input.paymentDate);
    const billingIds = unique([...(input.billingNoteId ? [input.billingNoteId] : []), ...invoices.flatMap((invoice) => invoice.billingNotes.map((link) => link.billingNoteId))]); for (const billingId of billingIds) await recalculateBilling(tx, billingId, input.paymentDate);
    await repository.createAccountingAudit(tx, { actorId: actor.id, actorName: actor.name, action: "PAYMENT_RECORDED", entityType: "Payment", entityId: payment.id, afterData: json({ paymentNo, amount: input.amount, allocatedAmount, unappliedAmount: subtractMoney(input.amount, allocatedAmount), invoiceIds: ids }) }); return payment.id;
  });
}

export async function voidPayment(id: string, reason: string, actor: Actor) { return repository.withAccountingTransaction(async (tx) => { const payment = await repository.findPaymentForUpdate(tx, id); if (!payment) throw new AccountingRuleError("ไม่พบการรับชำระเงิน"); if (payment.status === "VOID") return id; if (payment.status !== "COMPLETED") throw new AccountingRuleError("ยกเลิกได้เฉพาะรายการรับชำระที่บันทึกแล้ว"); const invoiceIds = unique(payment.allocations.map(({ invoiceId }) => invoiceId)); await repository.lockInvoices(tx, invoiceIds); await repository.updatePaymentRecord(tx, id, { status: "VOID", voidedAt: new Date(), voidReason: reason }); const asOfDate = todayInBangkok(); for (const invoiceId of invoiceIds) await recalculateInvoice(tx, invoiceId, asOfDate); for (const billingId of unique(payment.allocations.flatMap(({ billingNoteId }) => billingNoteId ? [billingNoteId] : []))) await recalculateBilling(tx, billingId, asOfDate); await repository.createAccountingAudit(tx, { actorId: actor.id, actorName: actor.name, action: "PAYMENT_VOIDED", entityType: "Payment", entityId: id, beforeData: json({ status: "COMPLETED" }), afterData: json({ status: "VOID", reason }) }); return id; }); }

export async function getPaymentList() { const rows = await repository.listPayments(); return rows.map((row) => { const allocatedAmount = row.status === "VOID" ? "0.00" : addMoney(row.allocations.map((allocation) => allocation.amount.toString())); return { id: row.id, paymentNo: row.paymentNo, paymentDate: dateKey(row.paymentDate), customerCode: row.customer.code, customerName: row.customer.displayName, method: row.method, status: row.status, amount: row.amount.toString(), allocatedAmount, unappliedAmount: row.status === "VOID" ? row.amount.toString() : subtractMoney(row.amount.toString(), allocatedAmount), allocationCount: row._count.allocations }; }); }
export async function getPayment(id: string) { const row = await repository.findPaymentDetail(id); if (!row) return null; const allocatedAmount = row.status === "VOID" ? "0.00" : addMoney(row.allocations.map((allocation) => allocation.amount.toString())); return { ...row, paymentDate: dateKey(row.paymentDate), amount: row.amount.toString(), allocatedAmount, unappliedAmount: row.status === "VOID" ? row.amount.toString() : subtractMoney(row.amount.toString(), allocatedAmount), allocations: row.allocations.map((allocation) => ({ ...allocation, amount: allocation.amount.toString(), allocatedAt: allocation.allocatedAt.toISOString(), invoice: { ...allocation.invoice, totalAmount: allocation.invoice.totalAmount.toString(), dueDate: dateKey(allocation.invoice.dueDate) } })) };
}

export async function getAccountsReceivable(asOfDate = todayInBangkok(), q = "") { const invoices = await repository.listReceivableInvoices(businessDate(asOfDate)); const rows = invoices.map((invoice) => { const paidAmount = addMoney(paidAmounts(invoice.paymentAllocations)); const outstandingAmount = calculateOutstanding(invoice.totalAmount.toString(), [paidAmount]); const bucket = agingBucket(dateKey(invoice.dueDate), asOfDate); return { id: invoice.id, invoiceNo: invoice.invoiceNo, invoiceDate: dateKey(invoice.invoiceDate), dueDate: dateKey(invoice.dueDate), customerId: invoice.customer.id, customerCode: invoice.customer.code, customerName: invoice.customer.displayName, creditTermDays: invoice.customer.creditTermDays, creditLimit: invoice.customer.creditLimit.toString(), originalAmount: invoice.totalAmount.toString(), paidAmount, outstandingAmount, daysOverdue: daysOverdue(dateKey(invoice.dueDate), asOfDate), bucket }; }).filter((row) => compareMoney(row.outstandingAmount, "0.00") > 0 && (!q || [row.invoiceNo, row.customerCode, row.customerName].some((value) => value.toLowerCase().includes(q.toLowerCase())))); const buckets: Record<AgingBucket, string[]> = { CURRENT: [], DAYS_1_30: [], DAYS_31_60: [], DAYS_61_90: [], DAYS_90_PLUS: [] }; for (const row of rows) buckets[row.bucket].push(row.outstandingAmount); const byCustomer = new Map<string, typeof rows>(); for (const row of rows) byCustomer.set(row.customerId, [...(byCustomer.get(row.customerId) ?? []), row]); const customers = [...byCustomer.values()].map((items) => ({ customerId: items[0]!.customerId, customerCode: items[0]!.customerCode, customerName: items[0]!.customerName, creditTermDays: items[0]!.creditTermDays, creditLimit: items[0]!.creditLimit, totalOutstanding: addMoney(items.map((item) => item.outstandingAmount)), buckets: { CURRENT: addMoney(items.filter((item) => item.bucket === "CURRENT").map((item) => item.outstandingAmount)), DAYS_1_30: addMoney(items.filter((item) => item.bucket === "DAYS_1_30").map((item) => item.outstandingAmount)), DAYS_31_60: addMoney(items.filter((item) => item.bucket === "DAYS_31_60").map((item) => item.outstandingAmount)), DAYS_61_90: addMoney(items.filter((item) => item.bucket === "DAYS_61_90").map((item) => item.outstandingAmount)), DAYS_90_PLUS: addMoney(items.filter((item) => item.bucket === "DAYS_90_PLUS").map((item) => item.outstandingAmount)) } })); return { asOfDate, total: addMoney(rows.map((row) => row.outstandingAmount)), buckets: Object.fromEntries(Object.entries(buckets).map(([key, values]) => [key, addMoney(values)])) as Record<AgingBucket, string>, invoices: rows, customers };
}

export async function checkFinancialIntegrity() { const ar = await getAccountsReceivable(); const payments = await repository.listPayments(); const paymentChecks = payments.filter((payment) => payment.status === "COMPLETED").map((payment) => { const allocated = addMoney(payment.allocations.map((allocation) => allocation.amount.toString())); return { paymentNo: payment.paymentNo, amount: payment.amount.toString(), allocated, unapplied: subtractMoney(payment.amount.toString(), allocated), valid: compareMoney(allocated, payment.amount.toString()) <= 0 }; }); return { arTotal: ar.total, invoiceCount: ar.invoices.length, invalidPayments: paymentChecks.filter((item) => !item.valid) };
}
