import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { db } from "@/lib/db";
import { addMoney, calculateOutstanding } from "@/services/accounting-core";
import { AccountingRuleError, checkFinancialIntegrity, createBillingNote, getAccountsReceivable, recordPayment, voidPayment } from "@/services/accounting.service";
import { getArAgingReport, getDashboard, getInvoiceReport, getMovementReport, getPaymentReport, getSalesReport, getStockReport } from "@/services/reporting.service";
import { reportQuerySchema } from "@/validations/reporting";

const actor = { id: null, name: "Accounting integration test" };
describe.skipIf(process.env.AQUAOPS_ACCOUNTING_DB_TEST !== "true")("accounting database workflow", () => {
  beforeAll(async () => { await db.$connect(); });
  afterAll(async () => { await db.$disconnect(); });

  it("keeps seeded invoices, payments, and global AR reconciled", async () => { const integrity = await checkFinancialIntegrity(); const ar = await getAccountsReceivable("2026-10-01"); expect(integrity.invalidPayments).toEqual([]); expect(ar.total).toBe(addMoney(ar.invoices.map((invoice) => invoice.outstandingAmount))); expect(ar.invoices.some((invoice) => invoice.paidAmount !== "0.00")).toBe(true); expect(ar.invoices.every((invoice) => invoice.outstandingAmount !== "0.00")).toBe(true); });

  it("preserves invoice snapshots and rejects posted-record mutation", async () => { const invoice = await db.invoice.findUniqueOrThrow({ where: { invoiceNo: "INV-202608-00001" }, include: { customer: true, items: true } }); const originalName = invoice.customerNameSnapshot; await db.customer.update({ where: { id: invoice.customerId }, data: { displayName: "ชื่อใหม่สำหรับทดสอบ snapshot" } }); expect((await db.invoice.findUniqueOrThrow({ where: { id: invoice.id } })).customerNameSnapshot).toBe(originalName); await expect(db.invoice.update({ where: { id: invoice.id }, data: { totalAmount: addMoney([invoice.totalAmount.toString(), "1.00"]) } })).rejects.toThrow(); await expect(db.invoiceItem.update({ where: { id: invoice.items[0]!.id }, data: { description: "ห้ามแก้ไข" } })).rejects.toThrow(); const allocation = await db.paymentAllocation.findFirstOrThrow(); await expect(db.paymentAllocation.delete({ where: { id: allocation.id } })).rejects.toThrow(); });

  it("supports a partial payment and cancellation without losing allocations", async () => { const invoice = await db.invoice.findUniqueOrThrow({ where: { invoiceNo: "INV-202610-00001" }, include: { paymentAllocations: { where: { payment: { status: "COMPLETED" } } } } }); const before = calculateOutstanding(invoice.totalAmount.toString(), invoice.paymentAllocations.map((allocation) => allocation.amount.toString())); const paymentId = await recordPayment({ idempotencyKey: "00000000-0000-4000-8000-000000000001", customerId: invoice.customerId, paymentDate: "2026-10-01", amount: "10.00", method: "CASH", externalReference: "TEST-PARTIAL", receivedAccount: "", notes: "", allocations: [{ invoiceId: invoice.id, amount: "10.00" }] }, actor); const afterPayment = await getAccountsReceivable("2026-10-01"); expect(afterPayment.invoices.find((item) => item.id === invoice.id)?.outstandingAmount).toBe(calculateOutstanding(before, ["10.00"])); await voidPayment(paymentId, "integration test reversal", actor); const afterVoid = await getAccountsReceivable("2026-10-01"); expect(afterVoid.invoices.find((item) => item.id === invoice.id)?.outstandingAmount).toBe(before); expect(await db.paymentAllocation.count({ where: { paymentId } })).toBe(1); });

  it("rejects allocation beyond the authoritative outstanding amount", async () => { const invoice = await db.invoice.findUniqueOrThrow({ where: { invoiceNo: "INV-202608-00001" } }); await expect(recordPayment({ idempotencyKey: "00000000-0000-4000-8000-000000000002", customerId: invoice.customerId, paymentDate: "2026-10-01", amount: addMoney([invoice.totalAmount.toString(), "0.01"]), method: "CASH", externalReference: "OVERPAY", receivedAccount: "", notes: "", allocations: [{ invoiceId: invoice.id, amount: addMoney([invoice.totalAmount.toString(), "0.01"]) }] }, actor)).rejects.toBeInstanceOf(AccountingRuleError); });

  it("serializes conflicting active billing-note assignment", async () => { const invoice = await db.invoice.findUniqueOrThrow({ where: { invoiceNo: "INV-202605-00001" } }); const input = { customerId: invoice.customerId, billingDate: "2026-10-01", dueDate: "2026-10-15", invoiceIds: [invoice.id], notes: "concurrency" }; const results = await Promise.allSettled([createBillingNote(input, actor), createBillingNote(input, actor)]); expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1); expect(results.filter((result) => result.status === "rejected")).toHaveLength(1); });

  it("prevents two concurrent payments from consuming the same balance", async () => { const invoice = await db.invoice.findUniqueOrThrow({ where: { invoiceNo: "INV-202607-00001" }, include: { paymentAllocations: { where: { payment: { status: "COMPLETED" } } } } }); const balance = calculateOutstanding(invoice.totalAmount.toString(), invoice.paymentAllocations.map((allocation) => allocation.amount.toString())); const input = { customerId: invoice.customerId, paymentDate: "2026-10-01", amount: balance, method: "BANK_TRANSFER" as const, externalReference: "CONCURRENT", receivedAccount: "", notes: "", allocations: [{ invoiceId: invoice.id, amount: balance }] }; const results = await Promise.allSettled([recordPayment({ ...input, idempotencyKey: "00000000-0000-4000-8000-000000000003" }, actor), recordPayment({ ...input, idempotencyKey: "00000000-0000-4000-8000-000000000004" }, actor)]); expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1); expect(results.filter((result) => result.status === "rejected")).toHaveLength(1); const refreshed = await db.invoice.findUniqueOrThrow({ where: { id: invoice.id }, include: { paymentAllocations: { where: { payment: { status: "COMPLETED" } } } } }); expect(calculateOutstanding(refreshed.totalAmount.toString(), refreshed.paymentAllocations.map((allocation) => allocation.amount.toString()))).toBe("0.00"); });
  it("keeps dashboard sales KPIs aligned with the filtered sales report", async () => { const query = reportQuerySchema.parse({ period: "custom", dateFrom: "2026-09-01", dateTo: "2026-09-30", pageSize: 100 }); const [report, dashboard] = await Promise.all([getSalesReport(query), getDashboard(query, ["sales_order.view"])]); expect(report.total).toBe(7); expect(report.rows.map((row) => row.status)).not.toContain("ฉบับร่าง"); expect(report.rows.map((row) => row.status)).not.toContain("ยกเลิก"); expect(dashboard.sales?.orderCount).toBe(report.total); expect(dashboard.sales?.value).toBe(report.summary.find((item) => item.label === "ยอดขายตามคำสั่งซื้อ")?.value); expect(addMoney(Object.values(dashboard.sales?.byPayment ?? {}))).toBe(dashboard.sales?.value); const nextMonth = await getSalesReport(reportQuerySchema.parse({ period: "custom", dateFrom: "2026-10-01", dateTo: "2026-10-31" })); expect(nextMonth.total).toBe(0); });

  it("reports inventory, payments, invoices, and AR from their authoritative sources", async () => { const base = reportQuerySchema.parse({ pageSize: 100 }); const [stock, movement, payment, invoice, aging, ar] = await Promise.all([getStockReport(base), getMovementReport(reportQuerySchema.parse({ period: "custom", dateFrom: "2026-09-30", dateTo: "2026-09-30", pageSize: 100 })), getPaymentReport(reportQuerySchema.parse({ period: "custom", dateFrom: "2026-09-01", dateTo: "2026-09-30", pageSize: 100 })), getInvoiceReport(reportQuerySchema.parse({ period: "custom", dateFrom: "2026-10-01", dateTo: "2026-10-01", pageSize: 100 })), getArAgingReport(reportQuerySchema.parse({ asOfDate: "2026-10-01", pageSize: 100 })), getAccountsReceivable("2026-10-01")]); const expectedBalances = await db.stockBalance.count({ where: { product: { trackInventory: true, deletedAt: null } } }); const expectedMovements = await db.inventoryLedgerEntry.count({ where: { movement: { occurredAt: { gte: new Date("2026-09-29T17:00:00.000Z"), lt: new Date("2026-09-30T17:00:00.000Z") } } } }); const expectedPayments = await db.payment.aggregate({ where: { status: "COMPLETED", paymentDate: { gte: new Date("2026-09-01T00:00:00.000Z"), lte: new Date("2026-09-30T00:00:00.000Z") } }, _sum: { amount: true } }); expect(stock.total).toBe(expectedBalances); expect(movement.total).toBe(expectedMovements); expect(payment.summary.find((item) => item.label === "ยอดรับชำระ")?.value).toBe(expectedPayments._sum.amount?.toFixed(2)); expect(invoice.total).toBe(1); expect(invoice.rows[0]?.outstanding).toBe(ar.invoices.find((item) => item.invoiceNo === "INV-202610-00001")?.outstandingAmount); expect(aging.summary.find((item) => item.label === "ลูกหนี้คงค้าง")?.value).toBe(ar.total); });
  it("aggregates dashboard stock alerts in the database using the StockBalance definition", async () => { const dashboard = await getDashboard(reportQuerySchema.parse({}), ["inventory.view"]); const balances = await db.stockBalance.findMany({ where: { product: { trackInventory: true, deletedAt: null } }, select: { onHandQuantity: true, product: { select: { reorderLevel: true } } } }); expect(dashboard.inventory).toEqual({ low: balances.filter((row) => row.onHandQuantity.gt(0) && row.onHandQuantity.lte(row.product.reorderLevel)).length, out: balances.filter((row) => row.onHandQuantity.lte(0)).length }); });
});
