import "server-only";
import type { Prisma } from "@/generated/prisma/client";
import { adjustmentReasonConfig } from "@/config/inventory";
import { addInventoryQuantities, compareInventoryQuantity, getStockStatus, signedInventoryQuantity, validateInventoryUnitScale } from "@/services/inventory-core";
import { clearDefaultWarehouse, createInventoryAuditLog, createInventoryLedgerEntry, createInventoryMovement, createWarehouse, findInventoryProductUnit, findLastMovements, findMovementByIdempotencyKey, findMovementEntries, findProductStock, findStockBalances, findWarehouseById, findWarehouses, listInventoryProductUnits, listStockFilterOptions, listWarehouses, lockStockBalance, nextInventoryMovementNumber, readStockBalance, reconcileInventoryProjection, updateWarehouse, withInventoryTransaction, type InventoryTransaction } from "@/repositories/inventory.repository";
import type { MovementListQuery, StockAdjustmentValues, StockListQuery, StockTransferValues, WarehouseFormValues, WarehouseListQuery } from "@/validations/inventory";

type Actor = { id: string | null; name: string };
type MovementType = "OPENING" | "RECEIPT" | "ISSUE" | "TRANSFER" | "ADJUSTMENT" | "SALE" | "DELIVERY" | "RETURN";
type MovementInput = { type: MovementType; productUnitId: string; quantity: string; sourceWarehouseId?: string; destinationWarehouseId?: string; adjustmentDirection?: "IN" | "OUT"; referenceType?: string; referenceId?: string; idempotencyKey?: string; notes?: string };
type BatchMovementInput = { type: "TRANSFER" | "SALE" | "RETURN"; items: Array<{ productUnitId: string; quantity: string }>; sourceWarehouseId?: string; destinationWarehouseId?: string; referenceType: string; referenceId: string; idempotencyKey: string; notes?: string };
export class InventoryRuleError extends Error { constructor(message: string) { super(message); this.name = "InventoryRuleError"; } }
export class WarehouseRuleError extends Error { constructor(message: string) { super(message); this.name = "WarehouseRuleError"; } }
const nullable = (value?: string) => value?.trim() || null;
const decimal = (value: { toFixed(scale: number): string } | null | undefined) => value?.toFixed(3) ?? "0.000";
function yearMonth(date: Date) { const parts = new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "2-digit", timeZone: "Asia/Bangkok" }).formatToParts(date); return `${parts.find((part) => part.type === "year")!.value}${parts.find((part) => part.type === "month")!.value}`; }
function available(onHand: string, reserved: string) { return addInventoryQuantities(onHand, `-${reserved}`); }
function isDatabaseInsufficientStock(error: unknown) { return JSON.stringify(error).includes("AQUAOPS_INSUFFICIENT_STOCK"); }

export async function getWarehouses(query: WarehouseListQuery) { const result = await findWarehouses(query); return { rows: result.rows.map((row) => ({ id: row.id, code: row.code, name: row.name, status: row.status, isDefault: row.isDefault, balanceCount: row._count.stockBalances, movementCount: row._count.inventoryEntries, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() })), total: result.total, pageCount: Math.ceil(result.total / query.pageSize) }; }
export async function getWarehouseOptions(activeOnly = false) { return (await listWarehouses(activeOnly ? "ACTIVE" : undefined)).map((row) => ({ ...row })); }
export async function saveWarehouse(input: WarehouseFormValues, actor: Actor) { return withInventoryTransaction(async (tx) => { const current = input.id ? await findWarehouseById(input.id, tx) : null; if (input.id && !current) throw new WarehouseRuleError("ไม่พบคลังสินค้า"); if (current?.type === "VEHICLE") throw new WarehouseRuleError("กรุณาจัดการคลังรถจากเมนูรถจัดส่ง"); if (input.isDefault) await clearDefaultWarehouse(tx, input.id); const warehouse = current ? await updateWarehouse(tx, current.id, { code: input.code.toUpperCase(), name: input.name, isDefault: input.isDefault }) : await createWarehouse(tx, { code: input.code.toUpperCase(), name: input.name, type: "STORAGE", isDefault: input.isDefault }); await createInventoryAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: current ? "WAREHOUSE_UPDATED" : "WAREHOUSE_CREATED", entityType: "Warehouse", entityId: warehouse.id, beforeData: current ? { code: current.code, name: current.name, isDefault: current.isDefault } : undefined, afterData: { code: warehouse.code, name: warehouse.name, isDefault: warehouse.isDefault, status: warehouse.status } }); return warehouse.id; }); }
export async function changeWarehouseStatus(id: string, status: "ACTIVE" | "INACTIVE", actor: Actor) { return withInventoryTransaction(async (tx) => { const current = await findWarehouseById(id, tx); if (!current) throw new WarehouseRuleError("ไม่พบคลังสินค้า"); if (current.type === "VEHICLE") throw new WarehouseRuleError("กรุณาจัดการคลังรถจากเมนูรถจัดส่ง"); if (current.status === status) return current.id; if (status === "INACTIVE" && current.isDefault) throw new WarehouseRuleError("ไม่สามารถปิดคลังหลักได้ กรุณากำหนดคลังหลักแห่งใหม่ก่อน"); const warehouse = await updateWarehouse(tx, id, { status }); await createInventoryAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: status === "ACTIVE" ? "WAREHOUSE_REACTIVATED" : "WAREHOUSE_DEACTIVATED", entityType: "Warehouse", entityId: id, beforeData: { status: current.status }, afterData: { status } }); return warehouse.id; }); }

export async function getInventoryOptions() { const [warehouses, products] = await Promise.all([getWarehouseOptions(true), listInventoryProductUnits()]); return { warehouses, products: products.map((item) => ({ id: item.id, productId: item.productId, sku: item.product.sku, name: item.product.name, barcode: item.barcode ?? "", unitName: item.unit.nameTh, unitSymbol: item.unit.symbol, decimalScale: item.unit.decimalScale })) }; }
export async function getStockOptions() { const [warehouses, categories, products] = await listStockFilterOptions(); return { warehouses, categories, products }; }

export async function getStock(query: StockListQuery) {
  const balances = await findStockBalances(query); const last = await findLastMovements(balances.map((row) => ({ warehouseId: row.warehouseId, productId: row.productId }))); const lastMap = new Map(last.map((item) => [`${item.warehouseId}:${item.productId}`, item._max.createdAt?.toISOString() ?? null]));
  let rows = balances.map((row) => { const base = row.product.units[0]; const quantity = row.onHandQuantity.toFixed(3); const minimumStock = row.product.reorderLevel.toFixed(3); return { id: row.id, productId: row.productId, sku: row.product.sku, barcode: base?.barcode ?? "", productName: row.product.name, productStatus: row.product.status, categoryId: row.product.categoryId, categoryName: row.product.category?.name ?? null, warehouseId: row.warehouseId, warehouseName: row.warehouse.name, unitName: base?.unit.nameTh ?? "หน่วยหลัก", unitSymbol: base?.unit.symbol ?? "", quantity, reservedQuantity: row.reservedQuantity.toFixed(3), minimumStock, status: getStockStatus(quantity, minimumStock), lastMovementAt: lastMap.get(`${row.warehouseId}:${row.productId}`) ?? null, updatedAt: row.updatedAt.toISOString() }; });
  if (query.status !== "ALL") rows = rows.filter((row) => row.status === query.status);
  const direction = query.order === "asc" ? 1 : -1; rows.sort((a, b) => { if (query.sort === "quantity") return compareInventoryQuantity(a.quantity, b.quantity) * direction; if (query.sort === "sku") return a.sku.localeCompare(b.sku, "th") * direction; if (query.sort === "name") return a.productName.localeCompare(b.productName, "th") * direction; if (query.sort === "warehouse") return a.warehouseName.localeCompare(b.warehouseName, "th") * direction; return a.updatedAt.localeCompare(b.updatedAt) * direction; });
  const total = rows.length; const paged = rows.slice((query.page - 1) * query.pageSize, query.page * query.pageSize); return { rows: paged, total, pageCount: Math.ceil(total / query.pageSize) };
}

export async function getStockDetail(productId: string) { const product = await findProductStock(productId); if (!product) return null; const base = product.units[0]; const balances = product.stockBalances.map((row) => ({ id: row.id, warehouseId: row.warehouseId, warehouseName: row.warehouse.name, warehouseStatus: row.warehouse.status, quantity: row.onHandQuantity.toFixed(3), reservedQuantity: row.reservedQuantity.toFixed(3), status: getStockStatus(row.onHandQuantity.toFixed(3), product.reorderLevel.toFixed(3)) })); const total = balances.reduce((sum, row) => addInventoryQuantities(sum, row.quantity), "0.000"); return { id: product.id, sku: product.sku, name: product.name, productStatus: product.status, categoryName: product.category?.name ?? null, barcode: base?.barcode ?? "", unitName: base?.unit.nameTh ?? "หน่วยหลัก", unitSymbol: base?.unit.symbol ?? "", minimumStock: product.reorderLevel.toFixed(3), total, balances, movements: product.inventoryEntries.map((row) => ({ id: row.id, movementId: row.movementId, movementNo: row.movement.movementNo, occurredAt: row.movement.occurredAt.toISOString(), productId: product.id, sku: product.sku, productName: product.name, warehouseId: row.warehouseId, warehouseName: row.warehouse.name, unitName: base?.unit.nameTh ?? "หน่วยหลัก", unitSymbol: base?.unit.symbol ?? "", type: row.movement.type, quantity: row.quantity.toFixed(3), referenceType: row.movement.referenceType, referenceId: row.movement.referenceId, userName: row.movement.createdBy?.name ?? "ระบบ", note: row.movement.notes })) }; }

export async function getMovements(query: MovementListQuery) { const [entries, total] = await findMovementEntries(query); return { rows: entries.map((row) => { const base = row.product.units[0]; return { id: row.id, movementId: row.movementId, movementNo: row.movement.movementNo, occurredAt: row.movement.occurredAt.toISOString(), productId: row.productId, sku: row.product.sku, productName: row.product.name, warehouseId: row.warehouseId, warehouseName: row.warehouse.name, unitName: base?.unit.nameTh ?? "หน่วยหลัก", unitSymbol: base?.unit.symbol ?? "", type: row.movement.type, quantity: row.quantity.toFixed(3), referenceType: row.movement.referenceType, referenceId: row.movement.referenceId, userName: row.movement.createdBy?.name ?? "ระบบ", note: row.movement.notes }; }), total, pageCount: Math.ceil(total / query.pageSize) }; }

async function validateActiveWarehouse(id: string | undefined, label: string, tx: InventoryTransaction) { if (!id) throw new InventoryRuleError(`กรุณาเลือก${label}`); const warehouse = await findWarehouseById(id, tx); if (!warehouse) throw new InventoryRuleError(`ไม่พบ${label}`); if (warehouse.status !== "ACTIVE") throw new InventoryRuleError(`${label}ไม่ได้เปิดใช้งาน`); return warehouse; }
async function postMovement(tx: InventoryTransaction, input: MovementInput, actor: Actor) {
  const productUnit = await findInventoryProductUnit(input.productUnitId, tx); if (!productUnit) throw new InventoryRuleError("ไม่พบสินค้าหรือหน่วยหลักที่เปิดใช้งาน");
  let quantity: string; try { quantity = validateInventoryUnitScale(input.quantity, productUnit.unit.decimalScale); } catch (error) { throw new InventoryRuleError(error instanceof Error ? error.message : "จำนวนไม่ถูกต้อง"); }
  const needsSource = ["ISSUE", "SALE", "DELIVERY", "TRANSFER"].includes(input.type) || (input.type === "ADJUSTMENT" && input.adjustmentDirection === "OUT"); const needsDestination = ["OPENING", "RECEIPT", "RETURN", "TRANSFER"].includes(input.type) || (input.type === "ADJUSTMENT" && input.adjustmentDirection === "IN");
  if (input.type === "ADJUSTMENT" && !input.adjustmentDirection) throw new InventoryRuleError("กรุณาระบุทิศทางการปรับสต็อก");
  const source = needsSource ? await validateActiveWarehouse(input.sourceWarehouseId, "คลังต้นทาง", tx) : null; const destination = needsDestination ? await validateActiveWarehouse(input.destinationWarehouseId, "คลังปลายทาง", tx) : null;
  if (source && destination && source.id === destination.id) throw new InventoryRuleError("คลังต้นทางและคลังปลายทางต้องไม่ใช่คลังเดียวกัน");
  const lockIds = [...new Set([source?.id, destination?.id].filter(Boolean) as string[])].sort(); const balances = new Map<string, Awaited<ReturnType<typeof lockStockBalance>>>(); for (const warehouseId of lockIds) balances.set(warehouseId, await lockStockBalance(tx, warehouseId, productUnit.productId));
  const sourceBefore = source ? balances.get(source.id) ?? null : null; if (source) { const sourceAvailable = available(decimal(sourceBefore?.onHandQuantity), decimal(sourceBefore?.reservedQuantity)); if (compareInventoryQuantity(sourceAvailable, quantity) < 0) throw new InventoryRuleError(`สต็อกคงเหลือไม่เพียงพอ (พร้อมใช้ ${sourceAvailable} ${productUnit.unit.symbol})`); }
  const occurredAt = new Date(); const movementNo = await nextInventoryMovementNumber(tx, yearMonth(occurredAt)); const movement = await createInventoryMovement(tx, { movementNo, type: input.type, occurredAt, sourceWarehouseId: source?.id, destinationWarehouseId: destination?.id, referenceType: nullable(input.referenceType), referenceId: nullable(input.referenceId) ?? movementNo, idempotencyKey: nullable(input.idempotencyKey), notes: nullable(input.notes), createdById: actor.id });
  try { if (source) await createInventoryLedgerEntry(tx, { movementId: movement.id, warehouseId: source.id, productId: productUnit.productId, quantity: signedInventoryQuantity(quantity, "OUT") }); if (destination) await createInventoryLedgerEntry(tx, { movementId: movement.id, warehouseId: destination.id, productId: productUnit.productId, quantity: signedInventoryQuantity(quantity, "IN") }); } catch (error) { if (isDatabaseInsufficientStock(error)) throw new InventoryRuleError("สต็อกมีการเปลี่ยนแปลงและจำนวนคงเหลือไม่เพียงพอ กรุณาตรวจสอบแล้วลองอีกครั้ง"); throw error; }
  return { movement, productUnit, quantity, source, destination, sourceBefore: decimal(sourceBefore?.onHandQuantity), destinationBefore: destination ? decimal(balances.get(destination.id)?.onHandQuantity) : "0.000" };
}

export function recordInventoryMovement(input: MovementInput, actor: Actor) { return withInventoryTransaction((tx) => postMovement(tx, input, actor)); }

export async function recordInventoryBatchMovement(tx: InventoryTransaction, input: BatchMovementInput, actor: Actor) {
  const existing = await findMovementByIdempotencyKey(tx, input.idempotencyKey); if (existing) return { movement: existing, duplicate: true };
  if (!input.items.length) throw new InventoryRuleError("ไม่พบรายการสินค้าสำหรับเคลื่อนไหวสต็อก");
  const source = input.sourceWarehouseId ? await validateActiveWarehouse(input.sourceWarehouseId, "คลังต้นทาง", tx) : null;
  const destination = input.destinationWarehouseId ? await validateActiveWarehouse(input.destinationWarehouseId, "คลังปลายทาง", tx) : null;
  if (["TRANSFER", "SALE"].includes(input.type) && !source) throw new InventoryRuleError("กรุณาเลือกคลังต้นทาง");
  if (["TRANSFER", "RETURN"].includes(input.type) && !destination) throw new InventoryRuleError("กรุณาเลือกคลังปลายทาง");
  if (source && destination && source.id === destination.id) throw new InventoryRuleError("คลังต้นทางและคลังปลายทางต้องไม่ใช่คลังเดียวกัน");
  const prepared = new Map<string, { productUnitId: string; productId: string; productName: string; quantity: string; symbol: string }>();
  for (const item of input.items) {
    const productUnit = await findInventoryProductUnit(item.productUnitId, tx); if (!productUnit) throw new InventoryRuleError("ไม่พบสินค้าหรือหน่วยหลักที่เปิดใช้งาน");
    let quantity: string; try { quantity = validateInventoryUnitScale(item.quantity, productUnit.unit.decimalScale); } catch (error) { throw new InventoryRuleError(error instanceof Error ? error.message : "จำนวนไม่ถูกต้อง"); }
    const current = prepared.get(productUnit.productId); prepared.set(productUnit.productId, { productUnitId: productUnit.id, productId: productUnit.productId, productName: productUnit.product.name, quantity: current ? addInventoryQuantities(current.quantity, quantity) : quantity, symbol: productUnit.unit.symbol });
  }
  const products = [...prepared.values()].sort((a, b) => a.productId.localeCompare(b.productId));
  const lockedBalances = new Map<string, Awaited<ReturnType<typeof lockStockBalance>>>(); const warehouseIds = [...new Set([source?.id, destination?.id].filter(Boolean) as string[])].sort();
  for (const warehouseId of warehouseIds) for (const item of products) lockedBalances.set(`${warehouseId}:${item.productId}`, await lockStockBalance(tx, warehouseId, item.productId));
  for (const item of products) {
    if (!source) continue; const balance = lockedBalances.get(`${source.id}:${item.productId}`); const sourceAvailable = available(decimal(balance?.onHandQuantity), decimal(balance?.reservedQuantity));
    if (compareInventoryQuantity(sourceAvailable, item.quantity) < 0) throw new InventoryRuleError(`สต็อก ${item.productName} คงเหลือไม่เพียงพอ (พร้อมใช้ ${sourceAvailable} ${item.symbol})`);
  }
  const occurredAt = new Date(); const movementNo = await nextInventoryMovementNumber(tx, yearMonth(occurredAt)); const movement = await createInventoryMovement(tx, { movementNo, type: input.type, occurredAt, sourceWarehouseId: source?.id, destinationWarehouseId: destination?.id, referenceType: input.referenceType, referenceId: input.referenceId, idempotencyKey: input.idempotencyKey, notes: nullable(input.notes), createdById: actor.id });
  try { for (const item of products) { if (source) await createInventoryLedgerEntry(tx, { movementId: movement.id, warehouseId: source.id, productId: item.productId, quantity: signedInventoryQuantity(item.quantity, "OUT") }); if (destination) await createInventoryLedgerEntry(tx, { movementId: movement.id, warehouseId: destination.id, productId: item.productId, quantity: signedInventoryQuantity(item.quantity, "IN") }); } } catch (error) { if (isDatabaseInsufficientStock(error)) throw new InventoryRuleError("สต็อกมีการเปลี่ยนแปลงและจำนวนคงเหลือไม่เพียงพอ กรุณาตรวจสอบแล้วลองอีกครั้ง"); throw error; }
  return { movement, duplicate: false };
}

export function createStockAdjustment(input: StockAdjustmentValues, actor: Actor) { return withInventoryTransaction(async (tx) => { const result = await postMovement(tx, { type: "ADJUSTMENT", productUnitId: input.productUnitId, quantity: input.quantity, sourceWarehouseId: input.direction === "OUT" ? input.warehouseId : undefined, destinationWarehouseId: input.direction === "IN" ? input.warehouseId : undefined, adjustmentDirection: input.direction, referenceType: "STOCK_ADJUSTMENT", notes: [adjustmentReasonConfig[input.reason], input.note].filter(Boolean).join(" — ") }, actor); const after = await readStockBalance(tx, input.warehouseId, result.productUnit.productId); const previous = input.direction === "OUT" ? result.sourceBefore : result.destinationBefore; await createInventoryAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: "STOCK_ADJUSTED", entityType: "InventoryMovement", entityId: result.movement.id, afterData: { movementNo: result.movement.movementNo, warehouseId: input.warehouseId, productId: result.productUnit.productId, productUnitId: input.productUnitId, direction: input.direction, quantity: result.quantity, reason: input.reason, note: nullable(input.note), previousBalance: previous, newBalance: decimal(after?.onHandQuantity) } }); return result.movement.id; }); }

export function createStockTransfer(input: StockTransferValues, actor: Actor) { return withInventoryTransaction(async (tx) => { const result = await postMovement(tx, { type: "TRANSFER", productUnitId: input.productUnitId, quantity: input.quantity, sourceWarehouseId: input.sourceWarehouseId, destinationWarehouseId: input.destinationWarehouseId, referenceType: "STOCK_TRANSFER", notes: input.note }, actor); const [sourceAfter, destinationAfter] = await Promise.all([readStockBalance(tx, input.sourceWarehouseId, result.productUnit.productId), readStockBalance(tx, input.destinationWarehouseId, result.productUnit.productId)]); await createInventoryAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: "STOCK_TRANSFERRED", entityType: "InventoryMovement", entityId: result.movement.id, afterData: { movementNo: result.movement.movementNo, sourceWarehouseId: input.sourceWarehouseId, destinationWarehouseId: input.destinationWarehouseId, productId: result.productUnit.productId, productUnitId: input.productUnitId, quantity: result.quantity, sourcePreviousBalance: result.sourceBefore, sourceNewBalance: decimal(sourceAfter?.onHandQuantity), destinationPreviousBalance: result.destinationBefore, destinationNewBalance: decimal(destinationAfter?.onHandQuantity), note: nullable(input.note) } }); return result.movement.id; }); }

export async function checkInventoryIntegrity() { const mismatches = await reconcileInventoryProjection(); return mismatches.map((row) => ({ warehouseId: row.warehouseId, productId: row.productId, ledgerQuantity: row.ledgerQuantity.toFixed(3), balanceQuantity: row.balanceQuantity.toFixed(3), difference: row.difference.toFixed(3) })); }

export function inventoryAuditJson(value: unknown): Prisma.InputJsonValue { return value as Prisma.InputJsonValue; }
