import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { db } from "@/lib/db";
import { createStockAdjustment, createStockTransfer, InventoryRuleError, recordInventoryMovement, checkInventoryIntegrity } from "@/services/inventory.service";

const actor = { id: null, name: "Inventory integration test" };
async function fixture(decimalScale = 3) { const suffix = randomUUID().slice(0, 8).toUpperCase(); const unit = await db.unitOfMeasure.create({ data: { code: `U-${suffix}`, nameTh: "หน่วยทดสอบ", symbol: "น.", decimalScale } }); const product = await db.product.create({ data: { sku: `SKU-${suffix}`, name: `สินค้าทดสอบ ${suffix}`, reorderLevel: "1.000" } }); const productUnit = await db.productUnit.create({ data: { productId: product.id, unitId: unit.id, conversionFactor: "1.000000", isBase: true } }); const source = await db.warehouse.create({ data: { code: `S-${suffix}`, name: `คลังต้นทาง ${suffix}` } }); const destination = await db.warehouse.create({ data: { code: `D-${suffix}`, name: `คลังปลายทาง ${suffix}` } }); return { product, productUnit, source, destination }; }
async function balance(warehouseId: string, productId: string) { return (await db.stockBalance.findUnique({ where: { warehouseId_productId: { warehouseId, productId } } }))?.onHandQuantity.toFixed(3) ?? "0.000"; }

describe.skipIf(process.env.AQUAOPS_INVENTORY_DB_TEST !== "true")("inventory database integrity", () => {
  beforeAll(async () => { await db.$connect(); });
  afterAll(async () => { await db.$disconnect(); });

  it("posts opening and adjustment movements with exact balances", async () => { const data = await fixture(); await recordInventoryMovement({ type: "OPENING", productUnitId: data.productUnit.id, quantity: "10.125", destinationWarehouseId: data.source.id, referenceType: "TEST" }, actor); await createStockAdjustment({ warehouseId: data.source.id, productUnitId: data.productUnit.id, direction: "IN", quantity: "0.200", reason: "DATA_CORRECTION", note: "test" }, actor); await createStockAdjustment({ warehouseId: data.source.id, productUnitId: data.productUnit.id, direction: "OUT", quantity: "0.100", reason: "PHYSICAL_COUNT", note: "test" }, actor); expect(await balance(data.source.id, data.product.id)).toBe("10.225"); });

  it("posts balanced transfer entries atomically", async () => { const data = await fixture(); await recordInventoryMovement({ type: "OPENING", productUnitId: data.productUnit.id, quantity: "10", destinationWarehouseId: data.source.id }, actor); const movementId = await createStockTransfer({ sourceWarehouseId: data.source.id, destinationWarehouseId: data.destination.id, productUnitId: data.productUnit.id, quantity: "4", note: "test" }, actor); const entries = await db.inventoryLedgerEntry.findMany({ where: { movementId }, orderBy: { quantity: "asc" } }); expect(entries.map((entry) => entry.quantity.toFixed(3))).toEqual(["-4.000", "4.000"]); expect(await balance(data.source.id, data.product.id)).toBe("6.000"); expect(await balance(data.destination.id, data.product.id)).toBe("4.000"); });

  it("rolls back the complete transfer when stock is insufficient", async () => { const data = await fixture(); await recordInventoryMovement({ type: "OPENING", productUnitId: data.productUnit.id, quantity: "2", destinationWarehouseId: data.source.id }, actor); const before = await db.inventoryMovement.count(); await expect(createStockTransfer({ sourceWarehouseId: data.source.id, destinationWarehouseId: data.destination.id, productUnitId: data.productUnit.id, quantity: "3", note: "test" }, actor)).rejects.toBeInstanceOf(InventoryRuleError); expect(await db.inventoryMovement.count()).toBe(before); expect(await balance(data.source.id, data.product.id)).toBe("2.000"); expect(await balance(data.destination.id, data.product.id)).toBe("0.000"); });

  it("allows only one of two concurrent reductions that would oversell", async () => { const data = await fixture(); await recordInventoryMovement({ type: "OPENING", productUnitId: data.productUnit.id, quantity: "10", destinationWarehouseId: data.source.id }, actor); const results = await Promise.allSettled([createStockAdjustment({ warehouseId: data.source.id, productUnitId: data.productUnit.id, direction: "OUT", quantity: "7", reason: "PHYSICAL_COUNT", note: "concurrent A" }, actor), createStockAdjustment({ warehouseId: data.source.id, productUnitId: data.productUnit.id, direction: "OUT", quantity: "7", reason: "PHYSICAL_COUNT", note: "concurrent B" }, actor)]); expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1); expect(await balance(data.source.id, data.product.id)).toBe("3.000"); });

  it("rejects inactive warehouses and same-warehouse transfers", async () => { const data = await fixture(); await db.warehouse.update({ where: { id: data.source.id }, data: { status: "INACTIVE" } }); await expect(recordInventoryMovement({ type: "OPENING", productUnitId: data.productUnit.id, quantity: "1", destinationWarehouseId: data.source.id }, actor)).rejects.toBeInstanceOf(InventoryRuleError); await expect(createStockTransfer({ sourceWarehouseId: data.destination.id, destinationWarehouseId: data.destination.id, productUnitId: data.productUnit.id, quantity: "1", note: "" }, actor)).rejects.toBeInstanceOf(InventoryRuleError); });

  it("rolls back ledger headers when the database balance guard fails", async () => { const data = await fixture(); const movementNo = `TEST-${randomUUID()}`; await expect(db.$transaction(async (tx) => { const movement = await tx.inventoryMovement.create({ data: { movementNo, type: "ISSUE", occurredAt: new Date(), sourceWarehouseId: data.source.id } }); await tx.inventoryLedgerEntry.create({ data: { movementId: movement.id, warehouseId: data.source.id, productId: data.product.id, quantity: "-1.000" } }); })).rejects.toThrow(); expect(await db.inventoryMovement.findUnique({ where: { movementNo } })).toBeNull(); expect(await balance(data.source.id, data.product.id)).toBe("0.000"); });

  it("prevents posted ledger and movement mutation and reconciles the projection", async () => { const data = await fixture(); const result = await recordInventoryMovement({ type: "OPENING", productUnitId: data.productUnit.id, quantity: "1", destinationWarehouseId: data.source.id }, actor); const entry = await db.inventoryLedgerEntry.findFirstOrThrow({ where: { movementId: result.movement.id } }); await expect(db.inventoryLedgerEntry.update({ where: { id: entry.id }, data: { quantity: "2.000" } })).rejects.toThrow(); await expect(db.inventoryMovement.update({ where: { id: result.movement.id }, data: { notes: "mutated" } })).rejects.toThrow(); expect(await checkInventoryIntegrity()).toEqual([]); });
});
