import "server-only";
import { BUSINESS_CURRENCY } from "@/constants/app";
import { createCustomerPriceRecord, createPriceListItemRecord, createPriceListRecord, createPricingAuditLog, deletePriceListItemRecord, findActiveCustomerPrice, findCustomerForPricing, findCustomerPriceById, findDuplicatePriceListItem, findPriceListByCode, findPriceListById, findPriceListByIdForUpdate, findPriceListItemById, findPriceLists, findPriceResolutionContext, findPricingProductUnit, listCustomerPrices, listPricingProductUnits, updateCustomerPriceRecord, updatePriceListItemRecord, updatePriceListRecord, withPricingTransaction } from "@/repositories/pricing.repository";
import type { PricingTransaction } from "@/repositories/pricing.repository";
import { normalizeCustomerPriceInput, normalizePriceListInput, normalizePriceListItemInput, parseBusinessDate, selectResolvedPrice, toDateInput } from "@/services/pricing-core";
import { getSalesSettings } from "@/services/settings.service";
import type { CustomerPriceValues, PriceListFormValues, PriceListItemValues, PriceListQuery } from "@/validations/pricing";

export class PricingRuleError extends Error { constructor(message: string) { super(message); this.name = "PricingRuleError"; } }
type Actor = { id: string | null; name: string };
const nullable = (value: string) => value || null;
function serializeProductUnit(unit: Awaited<ReturnType<typeof listPricingProductUnits>>[number]) { return { id: unit.id, productId: unit.productId, sku: unit.product.sku, productName: unit.product.name, unitId: unit.unitId, unitName: unit.unit.nameTh, unitSymbol: unit.unit.symbol, retailPrice: unit.retailPrice.toFixed(4), wholesalePrice: unit.wholesalePrice.toFixed(4), isActive: unit.isActive && unit.unit.isActive && unit.product.status === "ACTIVE" && !unit.product.deletedAt }; }

export async function getPriceLists(query: PriceListQuery) { const result = await findPriceLists(query); return { rows: result.rows.map((row) => ({ ...row, description: row.description, validFrom: row.validFrom?.toISOString() ?? null, validTo: row.validTo?.toISOString() ?? null, customerCount: row._count.customers, itemCount: row._count.items, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() })), total: result.total, pageCount: Math.ceil(result.total / query.pageSize) }; }
export async function getPriceList(id: string) { const priceList = await findPriceListById(id); if (!priceList) return null; return { id: priceList.id, code: priceList.code, name: priceList.name, description: priceList.description ?? "", status: priceList.status, currency: priceList.currency, validFrom: toDateInput(priceList.validFrom), validTo: toDateInput(priceList.validTo), customerCount: priceList._count.customers, createdAt: priceList.createdAt.toISOString(), updatedAt: priceList.updatedAt.toISOString(), items: priceList.items.map((item) => ({ id: item.id, productUnitId: item.productUnitId, minimumQuantity: item.minimumQuantity.toFixed(3), unitPrice: item.unitPrice.toFixed(4), productUnit: serializeProductUnit(item.productUnit) })) }; }
export async function getPricingProductUnits(activeOnly = false) { const units = (await listPricingProductUnits()).map(serializeProductUnit); return activeOnly ? units.filter((unit) => unit.isActive) : units; }
export async function getCustomerPrices(customerId: string) { const now = new Date(); return (await listCustomerPrices(customerId)).map((item) => ({ id: item.id, customerId: item.customerId, productUnitId: item.productUnitId, unitPrice: item.unitPrice.toFixed(4), validFrom: item.validFrom.toISOString(), validTo: item.validTo?.toISOString() ?? null, isActive: item.validFrom <= now && (!item.validTo || item.validTo >= now), productUnit: serializeProductUnit(item.productUnit) })); }

export function createPriceList(input: PriceListFormValues, actor: Actor) { const normalized = normalizePriceListInput(input); return withPricingTransaction(async (tx) => { if (await findPriceListByCode(normalized.code, tx)) throw new PricingRuleError("รหัสรายการราคานี้ถูกใช้งานแล้ว"); const priceList = await createPriceListRecord(tx, { code: normalized.code, name: normalized.name, description: nullable(normalized.description), status: normalized.status, currency: BUSINESS_CURRENCY, validFrom: parseBusinessDate(normalized.validFrom), validTo: parseBusinessDate(normalized.validTo) }); await createPricingAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: "PRICE_LIST_CREATED", entityType: "PriceList", entityId: priceList.id, afterData: normalized }); return priceList.id; }); }
export function updatePriceList(input: PriceListFormValues & { id: string }, actor: Actor) { const normalized = normalizePriceListInput(input); return withPricingTransaction(async (tx) => { const current = await findPriceListByIdForUpdate(input.id, tx); if (!current) throw new PricingRuleError("ไม่พบรายการราคา"); if (normalized.status !== "ACTIVE" && (await getSalesSettings(tx)).defaultPriceListId === input.id) throw new PricingRuleError("รายการราคานี้เป็นค่าเริ่มต้นของระบบ กรุณาเปลี่ยนการตั้งค่าก่อนปิดใช้งาน"); const duplicate = await findPriceListByCode(normalized.code, tx); if (duplicate && duplicate.id !== input.id) throw new PricingRuleError("รหัสรายการราคานี้ถูกใช้งานแล้ว"); await updatePriceListRecord(tx, input.id, { code: normalized.code, name: normalized.name, description: nullable(normalized.description), status: normalized.status, validFrom: parseBusinessDate(normalized.validFrom), validTo: parseBusinessDate(normalized.validTo) }); await createPricingAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: "PRICE_LIST_UPDATED", entityType: "PriceList", entityId: input.id, beforeData: { code: current.code, name: current.name, description: current.description, status: current.status, validFrom: current.validFrom?.toISOString(), validTo: current.validTo?.toISOString() }, afterData: normalized }); return input.id; }); }
export function changePriceListStatus(id: string, status: "ACTIVE" | "INACTIVE", actor: Actor) { return withPricingTransaction(async (tx) => { const current = await findPriceListByIdForUpdate(id, tx); if (!current) throw new PricingRuleError("ไม่พบรายการราคา"); if (current.status === status) return id; await updatePriceListRecord(tx, id, { status }); await createPricingAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: status === "ACTIVE" ? "PRICE_LIST_ACTIVATED" : "PRICE_LIST_DEACTIVATED", entityType: "PriceList", entityId: id, beforeData: { status: current.status }, afterData: { status } }); return id; }); }

export function savePriceListItem(input: PriceListItemValues, actor: Actor) { const normalized = normalizePriceListItemInput(input); return withPricingTransaction(async (tx) => { const priceList = await findPriceListByIdForUpdate(normalized.priceListId, tx); if (!priceList) throw new PricingRuleError("ไม่พบรายการราคา"); const productUnit = await findPricingProductUnit(normalized.productUnitId, tx); if (!productUnit || !productUnit.isActive || !productUnit.unit.isActive || productUnit.product.status !== "ACTIVE" || productUnit.product.deletedAt) throw new PricingRuleError("ไม่พบสินค้าและหน่วยที่ใช้งานได้"); const current = normalized.id ? await findPriceListItemById(normalized.id, tx) : null; if (normalized.id && (!current || current.priceListId !== normalized.priceListId)) throw new PricingRuleError("ไม่พบราคาสินค้า"); const duplicate = await findDuplicatePriceListItem(normalized.priceListId, normalized.productUnitId, normalized.minimumQuantity, tx); if (duplicate && duplicate.id !== normalized.id) throw new PricingRuleError("สินค้า หน่วย และจำนวนขั้นต่ำนี้มีราคาอยู่แล้ว"); const item = normalized.id ? await updatePriceListItemRecord(tx, normalized.id, { productUnitId: normalized.productUnitId, minimumQuantity: normalized.minimumQuantity, unitPrice: normalized.unitPrice }) : await createPriceListItemRecord(tx, { priceListId: normalized.priceListId, productUnitId: normalized.productUnitId, minimumQuantity: normalized.minimumQuantity, unitPrice: normalized.unitPrice }); await createPricingAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: normalized.id ? "PRICE_LIST_PRICE_UPDATED" : "PRICE_LIST_PRICE_ADDED", entityType: "PriceList", entityId: normalized.priceListId, beforeData: current ? { productUnitId: current.productUnitId, minimumQuantity: current.minimumQuantity.toFixed(3), unitPrice: current.unitPrice.toFixed(4) } : undefined, afterData: { itemId: item.id, productUnitId: normalized.productUnitId, minimumQuantity: normalized.minimumQuantity, unitPrice: normalized.unitPrice } }); return item.id; }); }
export function removePriceListItem(id: string, priceListId: string, actor: Actor) { return withPricingTransaction(async (tx) => { const current = await findPriceListItemById(id, tx); if (!current || current.priceListId !== priceListId) throw new PricingRuleError("ไม่พบราคาสินค้า"); await deletePriceListItemRecord(tx, id); await createPricingAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: "PRICE_LIST_PRICE_REMOVED", entityType: "PriceList", entityId: priceListId, beforeData: { itemId: id, productUnitId: current.productUnitId, minimumQuantity: current.minimumQuantity.toFixed(3), unitPrice: current.unitPrice.toFixed(4) } }); return priceListId; }); }

export function saveCustomerPrice(input: CustomerPriceValues, actor: Actor) { const normalized = normalizeCustomerPriceInput(input); return withPricingTransaction(async (tx) => { const customer = await findCustomerForPricing(normalized.customerId, tx); if (!customer) throw new PricingRuleError("ไม่พบลูกค้า"); const productUnit = await findPricingProductUnit(normalized.productUnitId, tx); if (!productUnit || !productUnit.isActive || !productUnit.unit.isActive || productUnit.product.status !== "ACTIVE" || productUnit.product.deletedAt) throw new PricingRuleError("ไม่พบสินค้าและหน่วยที่ใช้งานได้"); const current = normalized.id ? await findCustomerPriceById(normalized.id, tx) : null; if (normalized.id && (!current || current.customerId !== normalized.customerId || current.validTo)) throw new PricingRuleError("ไม่พบราคาพิเศษที่ใช้งานได้"); if (await findActiveCustomerPrice(normalized.customerId, normalized.productUnitId, new Date(), tx, normalized.id)) throw new PricingRuleError("ลูกค้ามีราคาพิเศษสำหรับสินค้าและหน่วยนี้แล้ว"); const price = normalized.id ? await updateCustomerPriceRecord(tx, normalized.id, { productUnitId: normalized.productUnitId, unitPrice: normalized.unitPrice }) : await createCustomerPriceRecord(tx, { customerId: normalized.customerId, productUnitId: normalized.productUnitId, unitPrice: normalized.unitPrice }); await createPricingAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: normalized.id ? "CUSTOMER_PRICE_UPDATED" : "CUSTOMER_PRICE_ADDED", entityType: "Customer", entityId: normalized.customerId, beforeData: current ? { priceId: current.id, productUnitId: current.productUnitId, unitPrice: current.unitPrice.toFixed(4) } : undefined, afterData: { priceId: price.id, productUnitId: normalized.productUnitId, unitPrice: normalized.unitPrice } }); return price.id; }); }
export function deactivateCustomerPrice(id: string, customerId: string, actor: Actor) { return withPricingTransaction(async (tx) => { const current = await findCustomerPriceById(id, tx); if (!current || current.customerId !== customerId) throw new PricingRuleError("ไม่พบราคาพิเศษลูกค้า"); if (current.validTo) return id; const validTo = new Date(); await updateCustomerPriceRecord(tx, id, { validTo }); await createPricingAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: "CUSTOMER_PRICE_REMOVED", entityType: "Customer", entityId: customerId, beforeData: { priceId: id, productUnitId: current.productUnitId, unitPrice: current.unitPrice.toFixed(4), validTo: null }, afterData: { priceId: id, validTo: validTo.toISOString() } }); return id; }); }

export async function resolveProductPrice(input: { customerId: string; productId: string; unitId: string; quantity?: string; at?: Date }, tx?: PricingTransaction) { const at = input.at ?? new Date(); const context = await findPriceResolutionContext({ ...input, quantity: input.quantity ?? "1.000", at }, tx); if (!context.customer) throw new PricingRuleError("ไม่พบลูกค้า"); if (context.customer.status !== "ACTIVE") throw new PricingRuleError("ลูกค้าไม่ได้เปิดใช้งาน"); const unit = context.productUnit; if (!unit || !unit.isActive || !unit.unit.isActive || unit.product.status !== "ACTIVE" || unit.product.deletedAt) throw new PricingRuleError("ไม่พบสินค้าและหน่วยที่ใช้งานได้"); const override = context.customer.customPrices[0]; const list = context.customer.defaultPriceList; const listActive = list?.status === "ACTIVE" && (!list.validFrom || list.validFrom <= at) && (!list.validTo || list.validTo >= at); const listItem = listActive ? list?.items[0] : null; return selectResolvedPrice({ customerType: context.customer.type, retailPrice: unit.retailPrice.toFixed(4), wholesalePrice: unit.wholesalePrice.toFixed(4), customerOverride: override ? { unitPrice: override.unitPrice.toFixed(4), source: "CUSTOMER_OVERRIDE", customerOverrideId: override.id } : null, priceListPrice: list && listItem ? { unitPrice: listItem.unitPrice.toFixed(4), source: "PRICE_LIST", priceList: { id: list.id, code: list.code, name: list.name } } : null }); }
export async function resolveProductUnitPrice(input: { customerId: string; productUnitId: string }) { const units = await getPricingProductUnits(); const unit = units.find((item) => item.id === input.productUnitId); if (!unit) throw new PricingRuleError("ไม่พบสินค้าและหน่วย"); return resolveProductPrice({ customerId: input.customerId, productId: unit.productId, unitId: unit.unitId }); }
