import "server-only";
import { createCategoryRecord, createProductAuditLog, createProductRecord, createProductUnitRecord, createUnitRecord, findActiveCategory, findActiveUnit, findCategoryByCode, findCategoryById, findProductById, findProductByIdForUpdate, findProductBySku, findProductUnitByBarcode, findProducts, findUnitByCode, findUnitById, listProductAuditLogs, listProductCategories, listUnits, updateCategoryRecord, updateProductRecord, updateProductUnitRecord, updateUnitRecord, withProductTransaction } from "@/repositories/product.repository";
import { normalizeCategoryInput, normalizeProductInput, normalizeUnitInput, summarizeProductForAudit } from "@/services/product-core";
import type { ProductCategoryValues, ProductFormValues, ProductListQuery, UnitValues } from "@/validations/product";

export class ProductRuleError extends Error { constructor(message: string) { super(message); this.name = "ProductRuleError"; } }
type Actor = { id: string | null; name: string };
const nullable = (value: string) => value || null;
function serializeUnit(unit: Awaited<ReturnType<typeof findProductById>> extends infer T ? NonNullable<T> extends { units: (infer U)[] } ? U : never : never) { return { id: unit.id, unitId: unit.unitId, barcode: unit.barcode ?? "", conversionFactor: unit.conversionFactor.toFixed(6), cost: unit.cost.toFixed(4), retailPrice: unit.retailPrice.toFixed(4), wholesalePrice: unit.wholesalePrice.toFixed(4), isBase: unit.isBase, isActive: unit.isActive, unit: { id: unit.unit.id, code: unit.unit.code, nameTh: unit.unit.nameTh, nameEn: unit.unit.nameEn ?? "", symbol: unit.unit.symbol, decimalScale: unit.unit.decimalScale, isActive: unit.unit.isActive } }; }

export async function getProducts(query: ProductListQuery) { const result = await findProducts(query); return { rows: result.rows.map(({ units, ...row }) => ({ ...row, reorderLevel: row.reorderLevel.toFixed(3), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), baseUnit: units[0] ? serializeUnit(units[0]) : null })), total: result.total, pageCount: Math.ceil(result.total / query.pageSize) }; }
export async function getProduct(id: string) { const product = await findProductById(id); if (!product) return null; const units = product.units.map(serializeUnit); const base = units.find((unit) => unit.isBase); if (!base) return null; return { id: product.id, sku: product.sku, name: product.name, description: product.description ?? "", categoryId: product.categoryId ?? "", category: product.category, status: product.status, trackInventory: product.trackInventory, reorderLevel: product.reorderLevel.toFixed(3), barcode: base.barcode, cost: base.cost, retailPrice: base.retailPrice, wholesalePrice: base.wholesalePrice, baseUnitId: base.unitId, createdAt: product.createdAt.toISOString(), updatedAt: product.updatedAt.toISOString(), units }; }
export async function getProductOptions() { const [categories, units] = await Promise.all([listProductCategories(), listUnits()]); return { categories: categories.map((item) => ({ ...item, productCount: item._count.products })), units: units.map((item) => ({ ...item, nameEn: item.nameEn ?? "", productCount: item._count.productUnits })) }; }
export async function getProductActivity(id: string) { return (await listProductAuditLogs(id)).map((log) => ({ ...log, createdAt: log.createdAt.toISOString() })); }

async function validateReferences(input: ProductFormValues, tx: Parameters<typeof findActiveCategory>[1]) { if (input.categoryId && !await findActiveCategory(input.categoryId, tx)) throw new ProductRuleError("ไม่พบหมวดหมู่ที่ใช้งานได้"); if (!await findActiveUnit(input.baseUnitId, tx)) throw new ProductRuleError("ไม่พบหน่วยสินค้าที่ใช้งานได้"); }
async function validateProductUniqueness(input: ProductFormValues, tx: Parameters<typeof findProductBySku>[1], currentId?: string) { const sku = await findProductBySku(input.sku, tx); if (sku && sku.id !== currentId) throw new ProductRuleError("SKU นี้ถูกใช้งานแล้ว"); if (input.barcode) { const barcode = await findProductUnitByBarcode(input.barcode, tx); if (barcode && barcode.productId !== currentId) throw new ProductRuleError("บาร์โค้ดนี้ถูกใช้งานแล้ว"); } }

export function createProduct(input: ProductFormValues, actor: Actor) { const normalized = normalizeProductInput(input); return withProductTransaction(async (tx) => { await validateReferences(normalized, tx); await validateProductUniqueness(normalized, tx); const product = await createProductRecord(tx, { sku: normalized.sku, name: normalized.name, description: nullable(normalized.description), categoryId: nullable(normalized.categoryId), status: normalized.status, trackInventory: normalized.trackInventory, reorderLevel: normalized.reorderLevel }); await createProductUnitRecord(tx, { productId: product.id, unitId: normalized.baseUnitId, conversionFactor: "1.000000", barcode: nullable(normalized.barcode), cost: normalized.cost, retailPrice: normalized.retailPrice, wholesalePrice: normalized.wholesalePrice, isBase: true, isActive: true }); await createProductAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: "PRODUCT_CREATED", entityType: "Product", entityId: product.id, afterData: summarizeProductForAudit(normalized) }); return product.id; }); }

export function updateProduct(input: ProductFormValues & { id: string }, actor: Actor) { const normalized = normalizeProductInput(input); return withProductTransaction(async (tx) => { const current = await findProductByIdForUpdate(input.id, tx); if (!current) throw new ProductRuleError("ไม่พบสินค้า"); const base = current.units.find((unit) => unit.isBase); if (!base) throw new ProductRuleError("สินค้าไม่มีหน่วยหลัก"); if (base.unitId !== normalized.baseUnitId) throw new ProductRuleError("ไม่สามารถเปลี่ยนหน่วยหลักของสินค้าที่สร้างแล้วได้"); if (normalized.categoryId !== (current.categoryId ?? "") || normalized.baseUnitId !== base.unitId) await validateReferences(normalized, tx); await validateProductUniqueness(normalized, tx, input.id); await updateProductRecord(tx, input.id, { sku: normalized.sku, name: normalized.name, description: nullable(normalized.description), categoryId: nullable(normalized.categoryId), trackInventory: normalized.trackInventory, reorderLevel: normalized.reorderLevel }); await updateProductUnitRecord(tx, base.id, { barcode: nullable(normalized.barcode), cost: normalized.cost, retailPrice: normalized.retailPrice, wholesalePrice: normalized.wholesalePrice }); await createProductAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: "PRODUCT_UPDATED", entityType: "Product", entityId: input.id, beforeData: { sku: current.sku, name: current.name, categoryId: current.categoryId, status: current.status, reorderLevel: current.reorderLevel.toFixed(3), barcode: base.barcode, cost: base.cost.toFixed(4), retailPrice: base.retailPrice.toFixed(4), wholesalePrice: base.wholesalePrice.toFixed(4) }, afterData: summarizeProductForAudit({ ...normalized, status: current.status }) }); return input.id; }); }

export function changeProductStatus(id: string, status: "ACTIVE" | "INACTIVE", actor: Actor) { return withProductTransaction(async (tx) => { const current = await findProductByIdForUpdate(id, tx); if (!current) throw new ProductRuleError("ไม่พบสินค้า"); if (current.status === status) return id; await updateProductRecord(tx, id, { status }); await createProductAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: status === "ACTIVE" ? "PRODUCT_REACTIVATED" : "PRODUCT_DEACTIVATED", entityType: "Product", entityId: id, beforeData: { status: current.status }, afterData: { status } }); return id; }); }

export function saveCategory(input: ProductCategoryValues, actor: Actor) { const normalized = normalizeCategoryInput(input); return withProductTransaction(async (tx) => { const duplicate = await findCategoryByCode(normalized.code, tx); if (duplicate && duplicate.id !== input.id) throw new ProductRuleError("รหัสหมวดหมู่นี้ถูกใช้งานแล้ว"); const before = input.id ? await findCategoryById(input.id, tx) : null; if (input.id && !before) throw new ProductRuleError("ไม่พบหมวดหมู่"); const category = input.id ? await updateCategoryRecord(tx, input.id, { code: normalized.code, name: normalized.name, isActive: normalized.isActive }) : await createCategoryRecord(tx, { code: normalized.code, name: normalized.name, isActive: normalized.isActive }); await createProductAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: input.id ? "PRODUCT_CATEGORY_UPDATED" : "PRODUCT_CATEGORY_CREATED", entityType: "ProductCategory", entityId: category.id, beforeData: before ?? undefined, afterData: category }); return category.id; }); }
export function changeCategoryStatus(id: string, isActive: boolean, actor: Actor) { return withProductTransaction(async (tx) => { const before = await findCategoryById(id, tx); if (!before) throw new ProductRuleError("ไม่พบหมวดหมู่"); if (before.isActive === isActive) return id; const category = await updateCategoryRecord(tx, id, { isActive }); await createProductAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: isActive ? "PRODUCT_CATEGORY_REACTIVATED" : "PRODUCT_CATEGORY_DEACTIVATED", entityType: "ProductCategory", entityId: id, beforeData: before, afterData: category }); return id; }); }
export function saveUnit(input: UnitValues, actor: Actor) { const normalized = normalizeUnitInput(input); return withProductTransaction(async (tx) => { const duplicate = await findUnitByCode(normalized.code, tx); if (duplicate && duplicate.id !== input.id) throw new ProductRuleError("รหัสหน่วยนี้ถูกใช้งานแล้ว"); const before = input.id ? await findUnitById(input.id, tx) : null; if (input.id && !before) throw new ProductRuleError("ไม่พบหน่วย"); const unit = input.id ? await updateUnitRecord(tx, input.id, { code: normalized.code, nameTh: normalized.nameTh, nameEn: nullable(normalized.nameEn), symbol: normalized.symbol, decimalScale: normalized.decimalScale, isActive: normalized.isActive }) : await createUnitRecord(tx, { code: normalized.code, nameTh: normalized.nameTh, nameEn: nullable(normalized.nameEn), symbol: normalized.symbol, decimalScale: normalized.decimalScale, isActive: normalized.isActive }); await createProductAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: input.id ? "UNIT_UPDATED" : "UNIT_CREATED", entityType: "UnitOfMeasure", entityId: unit.id, beforeData: before ?? undefined, afterData: unit }); return unit.id; }); }
export function changeUnitStatus(id: string, isActive: boolean, actor: Actor) { return withProductTransaction(async (tx) => { const before = await findUnitById(id, tx); if (!before) throw new ProductRuleError("ไม่พบหน่วย"); if (before.isActive === isActive) return id; const unit = await updateUnitRecord(tx, id, { isActive }); await createProductAuditLog(tx, { actorId: actor.id, actorName: actor.name, action: isActive ? "UNIT_REACTIVATED" : "UNIT_DEACTIVATED", entityType: "UnitOfMeasure", entityId: id, beforeData: before, afterData: unit }); return id; }); }
