import "server-only";

import { Prisma } from "@/generated/prisma/client";
import { invoiceStatusConfig, paymentMethodConfig, paymentStatusConfig } from "@/config/accounting";
import { deliveryStatusConfig as deliveryStatusBase, deliveryTripStatusConfig as deliveryTripStatusBase } from "@/config/delivery";
import { inventoryMovementTypeConfig, stockStatusConfig as stockStatusBase } from "@/config/inventory";
import { salesOrderStatusConfig as salesOrderStatusBase } from "@/config/sales-orders";
import type { PermissionCode } from "@/config/permissions";
import * as repository from "@/repositories/reporting.repository";
import { getDeliveryDashboardCounts } from "@/repositories/delivery.repository";
import { addMoney, calculateOutstanding, deriveInvoiceStatus, subtractMoney } from "@/services/accounting-core";
import { getAccountsReceivable } from "@/services/accounting.service";
import { getMovements, getStock } from "@/services/inventory.service";
import { bangkokTimestampRange, businessDateKey, createCsv, dateOnly, REPORT_EXPORT_LIMIT, resolveReportRange } from "@/services/reporting-core";
import type { ReportResult } from "@/features/reports/types";
import type { ReportQuery } from "@/validations/reporting";

const dateKey = (value: Date) => value.toISOString().slice(0, 10);
const money = (value: { toFixed(scale: number): string } | null | undefined) => value?.toFixed(2) ?? "0.00";
const quantity = (value: { toFixed(scale: number): string } | null | undefined) => value?.toFixed(3) ?? "0.000";
const pageCount = (total: number, size: number) => Math.ceil(total / size);
const typeLabel = (value: string) => value === "RETAIL" ? "ค้าปลีก" : "ค้าส่ง";
const saleTypeLabel = (value: string) => value === "CASH" ? "เงินสด" : "เครดิต";
const salesOrderStatusConfig = { ...Object.fromEntries(Object.entries(salesOrderStatusBase).map(([key, value]) => [key, { label: value.th }])), PENDING: { label: "ฉบับร่าง" } } as Record<string, { label: string }>;
const deliveryStatusConfig = Object.fromEntries(Object.entries(deliveryStatusBase).map(([key, value]) => [key, { label: value.th }])) as Record<string, { label: string }>;
const deliveryTripStatusConfig = Object.fromEntries(Object.entries(deliveryTripStatusBase).map(([key, value]) => [key, { label: value.th }])) as Record<string, { label: string }>;
const stockStatusConfig = Object.fromEntries(Object.entries(stockStatusBase).map(([key, value]) => [key, value.th])) as Record<string, string>;
const inventoryMovementConfig = inventoryMovementTypeConfig;
function range(query: ReportQuery) { return resolveReportRange(query); }

export async function getReportOptions() { return repository.getReportOptions(); }

export async function getSalesReport(query: ReportQuery, exportAll = false): Promise<ReportResult> { const dates = range(query); const data = await repository.listSales(query, dates.dateFrom, dates.dateTo, exportAll ? REPORT_EXPORT_LIMIT : query.pageSize, exportAll ? 0 : (query.page - 1) * query.pageSize); return { rows: data.rows.map((row) => ({ id: row.id, orderNo: row.orderNo, orderDate: dateKey(row.orderDate), customer: `${row.customerCodeSnapshot} · ${row.customerNameSnapshot}`, customerType: typeLabel(row.customerTypeSnapshot), paymentType: saleTypeLabel(row.saleType), subtotal: money(row.subtotal), discount: money(row.discountAmount), tax: money(row.taxAmount), total: money(row.totalAmount), status: salesOrderStatusConfig[row.status].label, salesperson: row.createdBy?.name ?? "ระบบ" })), total: data.total, pageCount: pageCount(data.total, query.pageSize), summary: [{ label: "คำสั่งซื้อ", value: String(data.aggregate._count), format: "number" }, { label: "ยอดก่อนส่วนลด", value: money(data.aggregate._sum.subtotal), format: "money" }, { label: "ส่วนลด", value: money(data.aggregate._sum.discountAmount), format: "money" }, { label: "ภาษี", value: money(data.aggregate._sum.taxAmount), format: "money" }, { label: "ยอดขายตามคำสั่งซื้อ", value: money(data.aggregate._sum.totalAmount), format: "money" }] }; }

export async function getProductSalesReport(query: ReportQuery, exportAll = false): Promise<ReportResult> { const dates = range(query); const data = await repository.listProductSales(query, dates.dateFrom, dates.dateTo, exportAll ? REPORT_EXPORT_LIMIT : query.pageSize, exportAll ? 0 : (query.page - 1) * query.pageSize); return { rows: data.rows.map((row, index) => { const qty = row._sum.quantity ?? new Prisma.Decimal(0); const total = row._sum.lineTotal ?? new Prisma.Decimal(0); return { id: `${row.productId}:${row.productUnitId}:${index}`, sku: row.skuSnapshot, product: row.productNameSnapshot, unit: row.unitNameSnapshot, quantity: quantity(qty), salesValue: money(total), averagePrice: qty.isZero() ? "0.00" : total.div(qty).toFixed(2), lineCount: row._count }; }), total: data.total, pageCount: pageCount(data.total, query.pageSize), summary: [{ label: "รายการสินค้า/หน่วย", value: String(data.total), format: "number" }, { label: "ยอดขายตามรายการสินค้า", value: money(data.aggregate._sum.lineTotal), format: "money" }] }; }

export async function getCustomerSalesReport(query: ReportQuery, exportAll = false): Promise<ReportResult> { const dates = range(query); const data = await repository.listCustomerSales(query, dates.dateFrom, dates.dateTo, exportAll ? REPORT_EXPORT_LIMIT : query.pageSize, exportAll ? 0 : (query.page - 1) * query.pageSize); return { rows: data.rows.map((row) => { const total = row._sum.totalAmount ?? new Prisma.Decimal(0); const count = row._count.id; return { id: `${row.customerId}:${row.customerTypeSnapshot}`, code: row.customerCodeSnapshot, customer: row.customerNameSnapshot, type: typeLabel(row.customerTypeSnapshot), orders: count, salesValue: money(total), averageOrder: count ? total.div(count).toFixed(2) : "0.00" }; }), total: data.total, pageCount: pageCount(data.total, query.pageSize), summary: [{ label: "ลูกค้า", value: String(data.total), format: "number" }, { label: "คำสั่งซื้อ", value: String(data.aggregate._count), format: "number" }, { label: "ยอดขายตามคำสั่งซื้อ", value: money(data.aggregate._sum.totalAmount), format: "money" }] }; }

export async function getDeliveryReport(query: ReportQuery, exportAll = false): Promise<ReportResult> { const dates = range(query); const data = await repository.listDeliveries(query, dates.dateFrom, dates.dateTo, exportAll ? REPORT_EXPORT_LIMIT : query.pageSize, exportAll ? 0 : (query.page - 1) * query.pageSize); return { rows: data.rows.map((row) => ({ id: row.id, tripNo: row.deliveryStop.deliveryTrip.tripNo, plannedDate: dateKey(row.deliveryStop.deliveryTrip.plannedDate), resultDate: (row.deliveredAt ?? row.deliveryStop.completedAt)?.toISOString() ?? null, driver: row.deliveryStop.deliveryTrip.driverName ?? "—", vehicle: row.deliveryStop.deliveryTrip.vehiclePlate ?? "—", orderNo: row.salesOrder.orderNo, customer: `${row.salesOrder.customerCodeSnapshot} · ${row.salesOrder.customerNameSnapshot}`, result: deliveryStatusConfig[row.status].label, tripStatus: deliveryTripStatusConfig[row.deliveryStop.deliveryTrip.status].label })), total: data.total, pageCount: pageCount(data.total, query.pageSize), summary: [{ label: "รอบจัดส่ง", value: String(data.trips), format: "number" }, { label: "คำสั่งซื้อที่มีผลจัดส่ง", value: String(data.total), format: "number" }, { label: "จัดส่งสำเร็จ", value: String(data.delivered), format: "number" }, { label: "จัดส่งไม่สำเร็จ", value: String(data.failed), format: "number" }] }; }

export async function getStockReport(query: ReportQuery, exportAll = false): Promise<ReportResult> { const stockQuery = { q: query.q, warehouseId: query.warehouseId, categoryId: query.categoryId, status: (["IN_STOCK", "LOW_STOCK", "OUT_OF_STOCK"].includes(query.status) ? query.status : "ALL") as "ALL" | "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK", productStatus: "ALL" as const, sort: (["sku", "name", "warehouse", "quantity"].includes(query.sort) ? query.sort : "updatedAt") as "sku" | "name" | "warehouse" | "quantity" | "updatedAt", order: query.order, page: exportAll ? 1 : query.page, pageSize: exportAll ? REPORT_EXPORT_LIMIT : query.pageSize }; const data = await getStock(stockQuery); const all = await getStock({ ...stockQuery, status: "ALL", page: 1, pageSize: REPORT_EXPORT_LIMIT }); return { rows: data.rows.map((row) => ({ id: row.id, sku: row.sku, product: row.productName, category: row.categoryName ?? "—", warehouse: row.warehouseName, unit: row.unitName, quantity: row.quantity, minimumStock: row.minimumStock, status: stockStatusConfig[row.status] })), total: data.total, pageCount: pageCount(data.total, query.pageSize), summary: [{ label: "รายการสต็อก", value: String(all.total), format: "number" }, { label: "สต็อกต่ำ", value: String(all.rows.filter((row) => row.status === "LOW_STOCK").length), format: "number" }, { label: "หมดสต็อก", value: String(all.rows.filter((row) => row.status === "OUT_OF_STOCK").length), format: "number" }] }; }

export async function getMovementReport(query: ReportQuery, exportAll = false): Promise<ReportResult> { const dates = range(query); const movementQuery = { q: query.q, warehouseId: query.warehouseId, productId: query.productId, type: (["OPENING", "RECEIPT", "ISSUE", "TRANSFER", "ADJUSTMENT", "SALE", "DELIVERY", "RETURN"].includes(query.status) ? query.status : "ALL") as "ALL" | "OPENING" | "RECEIPT" | "ISSUE" | "TRANSFER" | "ADJUSTMENT" | "SALE" | "DELIVERY" | "RETURN", dateFrom: dates.dateFrom, dateTo: dates.dateTo, sort: (["movementNo", "product", "warehouse", "quantity"].includes(query.sort) ? query.sort : "occurredAt") as "movementNo" | "occurredAt" | "product" | "warehouse" | "quantity", order: query.order, page: exportAll ? 1 : query.page, pageSize: exportAll ? REPORT_EXPORT_LIMIT : query.pageSize }; const data = await getMovements(movementQuery); return { rows: data.rows.map((row) => ({ id: row.id, movementNo: row.movementNo, occurredAt: row.occurredAt, product: `${row.sku} · ${row.productName}`, warehouse: row.warehouseName, type: inventoryMovementConfig[row.type], quantity: row.quantity, unit: row.unitName, reference: row.referenceId ?? "—", user: row.userName })), total: data.total, pageCount: pageCount(data.total, query.pageSize), summary: [{ label: "รายการเคลื่อนไหว", value: String(data.total), format: "number" }] }; }

export async function getInvoiceReport(query: ReportQuery, exportAll = false): Promise<ReportResult> { const dates = range(query); const data = await repository.listInvoices(query, dates.dateFrom, dates.dateTo, exportAll ? REPORT_EXPORT_LIMIT : query.pageSize, exportAll ? 0 : (query.page - 1) * query.pageSize); const asOf = businessDateKey(); return { rows: data.rows.map((row) => { const paid = addMoney(row.paymentAllocations.map((item) => item.amount.toFixed(2))); const outstanding = calculateOutstanding(row.totalAmount.toFixed(2), [paid]); const status = row.status === "DRAFT" || row.status === "VOID" ? row.status : deriveInvoiceStatus({ total: row.totalAmount.toFixed(2), outstanding, dueDate: dateKey(row.dueDate), asOfDate: asOf }); return { id: row.id, invoiceNo: row.invoiceNo, invoiceDate: dateKey(row.invoiceDate), customer: `${row.customerCodeSnapshot} · ${row.customerNameSnapshot}`, dueDate: dateKey(row.dueDate), originalAmount: money(row.totalAmount), paid, outstanding, status: invoiceStatusConfig[status].label }; }), total: data.total, pageCount: pageCount(data.total, query.pageSize), summary: [{ label: "ใบแจ้งหนี้", value: String(data.aggregate._count), format: "number" }, { label: "ยอดเดิม", value: money(data.aggregate._sum.totalAmount), format: "money" }, { label: "ชำระแล้ว", value: money(data.paid._sum.amount), format: "money" }, { label: "ยอดคงค้าง", value: subtractMoney(money(data.aggregate._sum.totalAmount), money(data.paid._sum.amount)), format: "money" }] }; }

export async function getPaymentReport(query: ReportQuery, exportAll = false): Promise<ReportResult> { const dates = range(query); const data = await repository.listPayments(query, dates.dateFrom, dates.dateTo, exportAll ? REPORT_EXPORT_LIMIT : query.pageSize, exportAll ? 0 : (query.page - 1) * query.pageSize); return { rows: data.rows.map((row) => { const allocated = row.status === "COMPLETED" ? addMoney(row.allocations.map((item) => item.amount.toFixed(2))) : "0.00"; return { id: row.id, paymentNo: row.paymentNo, paymentDate: dateKey(row.paymentDate), customer: `${row.customer.code} · ${row.customer.displayName}`, method: paymentMethodConfig[row.method], amount: money(row.amount), allocated, unapplied: row.status === "COMPLETED" ? subtractMoney(row.amount.toFixed(2), allocated) : money(row.amount), status: paymentStatusConfig[row.status].label }; }), total: data.total, pageCount: pageCount(data.total, query.pageSize), summary: [{ label: "รายการรับชำระ", value: String(data.aggregate._count), format: "number" }, { label: "ยอดรับชำระ", value: money(data.aggregate._sum.amount), format: "money" }, { label: "ยอดจัดสรรที่มีผล", value: money(data.allocated._sum.amount), format: "money" }] }; }

export async function getArAgingReport(query: ReportQuery, exportAll = false): Promise<ReportResult> { const asOfDate = query.asOfDate || businessDateKey(); const ar = await getAccountsReceivable(asOfDate, query.q); const selected = query.customerId === "ALL" ? ar.customers : ar.customers.filter((item) => item.customerId === query.customerId); const totals = { total: addMoney(selected.map((item) => item.totalOutstanding)), current: addMoney(selected.map((item) => item.buckets.CURRENT)), days1to30: addMoney(selected.map((item) => item.buckets.DAYS_1_30)), days31to60: addMoney(selected.map((item) => item.buckets.DAYS_31_60)), days61to90: addMoney(selected.map((item) => item.buckets.DAYS_61_90)), days90plus: addMoney(selected.map((item) => item.buckets.DAYS_90_PLUS)) }; const total = selected.length; const customers = exportAll ? selected.slice(0, REPORT_EXPORT_LIMIT) : selected.slice((query.page - 1) * query.pageSize, query.page * query.pageSize); return { rows: customers.map((row) => ({ id: row.customerId, code: row.customerCode, customer: row.customerName, current: row.buckets.CURRENT, days1to30: row.buckets.DAYS_1_30, days31to60: row.buckets.DAYS_31_60, days61to90: row.buckets.DAYS_61_90, days90plus: row.buckets.DAYS_90_PLUS, total: row.totalOutstanding, invoiceHref: `/reports/ar-aging?asOfDate=${asOfDate}&customerId=${row.customerId}#invoices` })), total, pageCount: pageCount(total, query.pageSize), summary: [{ label: "ลูกหนี้คงค้าง", value: totals.total, format: "money" }, { label: "ยังไม่ครบกำหนด", value: totals.current, format: "money" }, { label: "เกินกำหนด 1–30", value: totals.days1to30, format: "money" }, { label: "เกินกำหนด 31–60", value: totals.days31to60, format: "money" }, { label: "เกินกำหนด 61–90", value: totals.days61to90, format: "money" }, { label: "เกินกำหนด 90+", value: totals.days90plus, format: "money" }] }; }

export async function getArInvoiceDetails(query: ReportQuery) { if (query.customerId === "ALL") return []; const ar = await getAccountsReceivable(query.asOfDate || businessDateKey(), query.q); return ar.invoices.filter((item) => item.customerId === query.customerId).map((row) => ({ id: row.id, invoiceNo: row.invoiceNo, customer: `${row.customerCode} · ${row.customerName}`, invoiceDate: row.invoiceDate, dueDate: row.dueDate, originalAmount: row.originalAmount, paid: row.paidAmount, outstanding: row.outstandingAmount, days: row.daysOverdue })); }

export type ReportKey = "sales" | "products" | "customers" | "delivery" | "inventory-stock" | "inventory-movements" | "invoices" | "payments" | "ar-aging";
export async function getReport(key: ReportKey, query: ReportQuery, exportAll = false) { if (key === "sales") return getSalesReport(query, exportAll); if (key === "products") return getProductSalesReport(query, exportAll); if (key === "customers") return getCustomerSalesReport(query, exportAll); if (key === "delivery") return getDeliveryReport(query, exportAll); if (key === "inventory-stock") return getStockReport(query, exportAll); if (key === "inventory-movements") return getMovementReport(query, exportAll); if (key === "invoices") return getInvoiceReport(query, exportAll); if (key === "payments") return getPaymentReport(query, exportAll); return getArAgingReport(query, exportAll); }

export function reportCsv(headers: Array<{ key: string; label: string }>, result: ReportResult) { return createCsv(headers.map((item) => item.label), result.rows.map((row) => headers.map((item) => row[item.key]))); }

export async function getDashboard(query: ReportQuery, permissions: readonly string[]) { const dates = range(query); const allowed = new Set(permissions); const today = businessDateKey(); const tasks: Array<Promise<unknown>> = []; const indexes: Record<string, number> = {}; const add = (key: string, promise: Promise<unknown>) => { indexes[key] = tasks.length; tasks.push(promise); }; if (allowed.has("sales_order.view")) add("sales", repository.getDashboardSales(dates.dateFrom, dates.dateTo)); if (allowed.has("delivery.view")) { const timestamps = bangkokTimestampRange(today, today); const dateToday = dateOnly(today); const dateTomorrow = new Date(dateToday.getTime() + 86_400_000); add("delivery", getDeliveryDashboardCounts(dateToday, dateTomorrow, timestamps.gte, timestamps.lt)); } if (allowed.has("inventory.view")) add("inventory", repository.getDashboardInventory()); if (allowed.has("ar.view")) add("ar", getAccountsReceivable(today)); const values = await Promise.all(tasks); const sales = indexes.sales == null ? null : values[indexes.sales] as Awaited<ReturnType<typeof repository.getDashboardSales>>; const inventory = indexes.inventory == null ? null : values[indexes.inventory] as Awaited<ReturnType<typeof repository.getDashboardInventory>>; const retailWholesale = sales ? sales.retailWholesale.reduce<Record<string, string[]>>((acc, row) => { acc[row.customerTypeSnapshot].push(money(row._sum.totalAmount)); return acc; }, { RETAIL: [], WHOLESALE: [] }) : null; return { range: dates, sales: sales ? { orderCount: sales.totals._count, value: money(sales.totals._sum.totalAmount), byPayment: Object.fromEntries(sales.byPayment.map((row) => [row.saleType, money(row._sum.totalAmount)])), byStatus: sales.byStatus.map((row) => ({ label: salesOrderStatusConfig[row.status].label, value: row._count })), trend: sales.byDate.map((row) => ({ date: dateKey(row.orderDate), value: money(row._sum.totalAmount) })), retailWholesale: { RETAIL: addMoney(retailWholesale!.RETAIL), WHOLESALE: addMoney(retailWholesale!.WHOLESALE) }, topCustomers: sales.topCustomers.map((row) => ({ name: row.customerNameSnapshot, value: money(row._sum.totalAmount) })), topProducts: sales.topProducts.map((row) => ({ name: `${row.skuSnapshot} · ${row.productNameSnapshot}`, value: money(row._sum.lineTotal) })) } : null, delivery: indexes.delivery == null ? null : values[indexes.delivery] as Awaited<ReturnType<typeof getDeliveryDashboardCounts>>, inventory, ar: indexes.ar == null ? null : values[indexes.ar] as Awaited<ReturnType<typeof getAccountsReceivable>> };
}

export const reportUnderlyingPermission: Record<ReportKey, PermissionCode> = { sales: "sales_order.view", products: "sales_order.view", customers: "sales_order.view", delivery: "delivery.view", "inventory-stock": "inventory.view", "inventory-movements": "inventory.view", invoices: "invoice.view", payments: "payment.view", "ar-aging": "ar.view" };
