import { describe, expect, it } from "vitest";
import { calculateSalesOrderTotals, canTransitionSalesOrder, isManualPriceOverride } from "@/services/sales-order-core";

describe("sales order calculations", () => {
  it("calculates document VAT after line and document discounts with exact decimals", () => { const result = calculateSalesOrderTotals([{ quantity: "2.500", unitPrice: "10.5555", discountAmount: "1.00" }, { quantity: "1.000", unitPrice: "20.0000", discountAmount: "0.00" }], "2.00", "7.00"); expect(result).toMatchObject({ subtotal: "46.39", discountAmount: "3.00", amountBeforeTax: "43.39", taxAmount: "3.04", totalAmount: "46.43" }); expect(result.lines[0]?.lineSubtotal).toBe("26.39"); });
  it("rejects discounts above the available amount", () => { expect(() => calculateSalesOrderTotals([{ quantity: "1", unitPrice: "5", discountAmount: "6" }], "0", "0.00")).toThrow(); });
  it("allocates a rounding-sensitive document discount without negative line totals", () => { const result = calculateSalesOrderTotals(Array.from({ length: 100 }, () => ({ quantity: "1", unitPrice: "0.01", discountAmount: "0" })), "0.99", "7.00"); expect(result.totalAmount).toBe("0.01"); expect(result.lines.every((line) => !line.lineTotal.startsWith("-"))).toBe(true); expect(result.lines.reduce((sum, line) => sum + Number(line.documentDiscountShare), 0)).toBeCloseTo(0.99); });
});
describe("sales order status policy", () => { it("allows Phase 7 transitions and rejects later workflow shortcuts", () => { expect(canTransitionSalesOrder("DRAFT", "CONFIRMED")).toBe(true); expect(canTransitionSalesOrder("DRAFT", "CANCELLED")).toBe(true); expect(canTransitionSalesOrder("CONFIRMED", "CANCELLED")).toBe(true); expect(canTransitionSalesOrder("CONFIRMED", "PREPARING")).toBe(false); }); });
describe("sales order price snapshots", () => { it("normalizes prices before detecting a manual override", () => { expect(isManualPriceOverride("42.5", "42.5000")).toBe(false); expect(isManualPriceOverride("41.0000", "42.5000")).toBe(true); }); });
