import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { db } from "@/lib/db";
import { nextSalesOrderNumber } from "@/repositories/sales-order.repository";
import { resolveProductPrice } from "@/services/pricing.service";
import { getSettingsPageData, SettingsConflictError, updateDocumentSettings, updateFinanceSettings, updateGeneralSettings, updateInventoryDeliverySettings, updateSalesSettings } from "@/services/settings.service";

const actor = { id: null, name: "Settings integration test" };
describe.skipIf(process.env.AQUAOPS_SETTINGS_DB_TEST !== "true")("settings database workflow", () => {
  beforeAll(async () => { await db.$connect(); });
  afterAll(async () => { await db.$disconnect(); });

  it("persists business information and captures old/new audit values", async () => { const before = await getSettingsPageData(); await updateGeneralSettings({ version: before.version, ...before.general, businessName: "โรงงานน้ำดื่มทดสอบ" }, actor); const after = await getSettingsPageData(); expect(after.general.businessName).toBe("โรงงานน้ำดื่มทดสอบ"); const audit = await db.auditLog.findFirstOrThrow({ where: { entityId: "default:general" }, orderBy: { createdAt: "desc" } }); expect(audit.beforeData).toMatchObject({ businessName: before.general.businessName }); expect(audit.afterData).toMatchObject({ businessName: "โรงงานน้ำดื่มทดสอบ" }); });

  it("rejects stale concurrent edits", async () => { const current = await getSettingsPageData(); await updateFinanceSettings({ version: current.version, ...current.finance, billingInstructions: "รับเช็ควันทำการ" }, actor); await expect(updateFinanceSettings({ version: current.version, ...current.finance, billingInstructions: "ค่าที่มาช้า" }, actor)).rejects.toBeInstanceOf(SettingsConflictError); });

  it("uses the configured Price List only after customer-specific precedence", async () => { const item = await db.priceListItem.findFirstOrThrow({ where: { priceList: { status: "ACTIVE" } }, include: { priceList: true, productUnit: true } }); const customer = await db.customer.findFirstOrThrow({ where: { status: "ACTIVE", deletedAt: null, defaultPriceListId: null } }); const current = await getSettingsPageData(); await updateSalesSettings({ version: current.version, ...current.sales, defaultPriceListId: item.priceListId }, actor); const resolved = await resolveProductPrice({ customerId: customer.id, productId: item.productUnit.productId, unitId: item.productUnit.unitId, quantity: item.minimumQuantity.toString() }); expect(resolved.source).toBe("PRICE_LIST"); expect(resolved.priceList?.id).toBe(item.priceListId); expect(resolved.unitPrice).toBe(item.unitPrice.toFixed(4)); });

  it("keeps historical VAT, warehouse ledger, and payment records unchanged", async () => { const settings = await getSettingsPageData(); const orderItem = await db.salesOrderItem.findFirstOrThrow({ orderBy: { createdAt: "asc" } }); const movement = await db.inventoryMovement.findFirstOrThrow({ orderBy: { createdAt: "asc" } }); const payment = await db.payment.findFirstOrThrow({ orderBy: { createdAt: "asc" } }); const warehouse = await db.warehouse.findFirstOrThrow({ where: { status: "ACTIVE", type: "STORAGE", id: { not: settings.inventoryDelivery.defaultWarehouseId || undefined } } }); await updateSalesSettings({ version: settings.version, ...settings.sales, defaultVatRate: "10.00" }, actor); let current = await getSettingsPageData(); await updateInventoryDeliverySettings({ version: current.version, defaultWarehouseId: warehouse.id, defaultDeliverySourceWarehouseId: warehouse.id }, actor); current = await getSettingsPageData(); await updateFinanceSettings({ version: current.version, defaultPaymentMethod: "CASH", billingInstructions: current.finance.billingInstructions }, actor); expect((await db.salesOrderItem.findUniqueOrThrow({ where: { id: orderItem.id } })).taxRate.toFixed(2)).toBe(orderItem.taxRate.toFixed(2)); expect(await db.inventoryMovement.findUnique({ where: { id: movement.id } })).toMatchObject({ movementNo: movement.movementNo, sourceWarehouseId: movement.sourceWarehouseId, destinationWarehouseId: movement.destinationWarehouseId }); expect((await db.payment.findUniqueOrThrow({ where: { id: payment.id } })).method).toBe(payment.method); });

  it("changes future prefixes without changing history or resetting the counter", async () => { const existing = await db.salesOrder.findFirstOrThrow({ orderBy: { orderNo: "asc" } }); const current = await getSettingsPageData(); await updateDocumentSettings({ version: current.version, ...current.documents, salesOrderPrefix: "ORD" }, actor); const [first, second] = await Promise.all([db.$transaction((tx) => nextSalesOrderNumber(tx, "202609")), db.$transaction((tx) => nextSalesOrderNumber(tx, "202609"))]); expect(new Set([first, second]).size).toBe(2); expect([first, second].sort()).toEqual(["ORD-202609-00011", "ORD-202609-00012"]); expect((await db.salesOrder.findUniqueOrThrow({ where: { id: existing.id } })).orderNo).toBe(existing.orderNo); expect((await db.documentSequence.findUniqueOrThrow({ where: { key: "SALES_ORDER-202609" } })).currentValue).toBe(12); });
});
