"use client";

import type { ColumnDef, PaginationState, SortingState } from "@tanstack/react-table";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { DataTable } from "@/components/shared/data-table";
import { DataTableColumnHeader } from "@/components/shared/data-table-column-header";
import { DateRange } from "@/components/shared/date-range";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { inventoryMovementTypeConfig } from "@/config/inventory";
import type { MovementRow, WarehouseOption } from "@/features/inventory/types";
import { formatDateTime, formatQuantityDecimal } from "@/lib/formatters";
import type { MovementListQuery } from "@/validations/inventory";

type ProductOption = { id: string; sku: string; name: string };
export function MovementTable({ rows, total, pageCount, query, warehouses, products }: { rows: MovementRow[]; total: number; pageCount: number; query: MovementListQuery; warehouses: WarehouseOption[]; products: ProductOption[] }) { const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const [search, setSearch] = useState(query.q); function navigate(changes: Record<string, string | number | undefined>) { const params = new URLSearchParams(searchParams.toString()); for (const [key, value] of Object.entries(changes)) if (value === undefined || value === "" || value === "ALL") params.delete(key); else params.set(key, String(value)); router.replace(`${pathname}${params.size ? `?${params}` : ""}`); } useEffect(() => { if (search === query.q) return; const timeout = window.setTimeout(() => navigate({ q: search, page: 1 }), 350); return () => window.clearTimeout(timeout); }, [search, query.q]); // eslint-disable-line react-hooks/exhaustive-deps
  const columns = useMemo<ColumnDef<MovementRow>[]>(() => [{ accessorKey: "movementNo", header: ({ column }) => <DataTableColumnHeader column={column} title="เลขที่รายการ" />, cell: ({ row }) => <span className="font-medium tabular-nums">{row.original.movementNo}</span> }, { accessorKey: "occurredAt", header: ({ column }) => <DataTableColumnHeader column={column} title="วันเวลา" />, cell: ({ row }) => <span className="whitespace-nowrap tabular-nums">{formatDateTime(row.original.occurredAt)}</span> }, { accessorKey: "productName", id: "product", header: ({ column }) => <DataTableColumnHeader column={column} title="สินค้า" />, cell: ({ row }) => <div className="min-w-44"><Link className="font-medium hover:underline" href={`/inventory/stock/${row.original.productId}`} onClick={(event) => event.stopPropagation()}>{row.original.productName}</Link><p className="type-caption tabular-nums">{row.original.sku}</p></div> }, { accessorKey: "warehouseName", id: "warehouse", header: ({ column }) => <DataTableColumnHeader column={column} title="คลังสินค้า" /> }, { accessorKey: "type", header: "ประเภท", enableSorting: false, cell: ({ row }) => <Badge variant="outline">{inventoryMovementTypeConfig[row.original.type]}{row.original.type === "TRANSFER" ? row.original.quantity.startsWith("-") ? "ออก" : "เข้า" : ""}</Badge> }, { accessorKey: "quantity", header: ({ column }) => <DataTableColumnHeader column={column} title="จำนวน" />, meta: { align: "right" }, cell: ({ row }) => <span className={`font-medium tabular-nums ${row.original.quantity.startsWith("-") ? "text-danger" : "text-success"}`}>{row.original.quantity.startsWith("-") ? "" : "+"}{formatQuantityDecimal(row.original.quantity, row.original.unitSymbol)}</span> }, { id: "reference", header: "อ้างอิง", enableSorting: false, cell: ({ row }) => <div className="max-w-48"><p className="truncate tabular-nums" title={row.original.referenceId ?? undefined}>{row.original.referenceId ?? "—"}</p>{row.original.note && <p className="truncate type-caption" title={row.original.note}>{row.original.note}</p>}</div> }, { accessorKey: "userName", header: "ผู้บันทึก", enableSorting: false }], []);
  const filters = <><Select value={query.warehouseId} onValueChange={(value) => navigate({ warehouseId: value, page: 1 })}><SelectTrigger className="w-full md:w-44" aria-label="คลังสินค้า"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกคลังสินค้า</SelectItem>{warehouses.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select><Select value={query.productId} onValueChange={(value) => navigate({ productId: value, page: 1 })}><SelectTrigger className="w-full md:w-52" aria-label="สินค้า"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">สินค้าทั้งหมด</SelectItem>{products.map((item) => <SelectItem key={item.id} value={item.id}>{item.name} ({item.sku})</SelectItem>)}</SelectContent></Select><Select value={query.type} onValueChange={(value) => navigate({ type: value, page: 1 })}><SelectTrigger className="w-full md:w-40" aria-label="ประเภทรายการ"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกประเภท</SelectItem>{Object.entries(inventoryMovementTypeConfig).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><DateRange hideLabel className="w-full md:w-72" label="ช่วงวันที่" from={{ value: query.dateFrom, onChange: (event) => navigate({ dateFrom: event.target.value, page: 1 }), "aria-label": "วันที่เริ่มต้น" }} to={{ value: query.dateTo, onChange: (event) => navigate({ dateTo: event.target.value, page: 1 }), "aria-label": "วันที่สิ้นสุด" }} /></>;
  const activeFilterCount = [query.warehouseId, query.productId, query.type].filter((value) => value !== "ALL").length + Number(Boolean(query.dateFrom || query.dateTo)); const sorting: SortingState = [{ id: query.sort, desc: query.order === "desc" }]; const pagination: PaginationState = { pageIndex: query.page - 1, pageSize: query.pageSize }; return <DataTable columns={columns} data={rows} searchValue={search} onSearchChange={setSearch} searchPlaceholder="ค้นหาเลขที่รายการ SKU สินค้า หรือเลขอ้างอิง..." filters={filters} activeFilterCount={activeFilterCount} onResetFilters={() => { setSearch(""); router.replace(pathname); }} emptyTitle={query.q || activeFilterCount ? "ไม่พบรายการเคลื่อนไหวที่ตรงกับตัวกรอง" : "ยังไม่มีรายการเคลื่อนไหวสต็อก"} emptyDescription={query.q || activeFilterCount ? "ลองเปลี่ยนคำค้นหาหรือล้างตัวกรอง" : "รายการที่บันทึกผ่านยอดยกมา การปรับปรุง หรือการโอนย้ายจะแสดงที่นี่"} manualPagination manualSorting manualFiltering pageCount={pageCount} totalRows={total} pagination={pagination} onPaginationChange={(next) => navigate({ page: next.pageIndex + 1, pageSize: next.pageSize })} sorting={sorting} onSortingChange={(next) => { const selected = next[0]; if (selected) navigate({ sort: selected.id, order: selected.desc ? "desc" : "asc", page: 1 }); }} pageSizeOptions={[20, 50, 100]} getRowId={(row) => row.id} />; }
