"use client";

import type { ColumnDef, PaginationState, SortingState } from "@tanstack/react-table";
import { ArrowLeftRight, SlidersHorizontal } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { DataTable } from "@/components/shared/data-table";
import { DataTableColumnHeader } from "@/components/shared/data-table-column-header";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { stockStatusConfig } from "@/config/inventory";
import type { StockRow, WarehouseOption } from "@/features/inventory/types";
import { formatDateTime, formatQuantityDecimal } from "@/lib/formatters";
import type { StockListQuery } from "@/validations/inventory";

type Option = { id: string; name: string };
export function StockTable({ rows, total, pageCount, query, warehouses, categories, canAdjust, canTransfer }: { rows: StockRow[]; total: number; pageCount: number; query: StockListQuery; warehouses: WarehouseOption[]; categories: Option[]; canAdjust: boolean; canTransfer: boolean }) { const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const [search, setSearch] = useState(query.q); function navigate(changes: Record<string, string | number | undefined>) { const params = new URLSearchParams(searchParams.toString()); for (const [key, value] of Object.entries(changes)) if (value === undefined || value === "" || value === "ALL") params.delete(key); else params.set(key, String(value)); router.replace(`${pathname}${params.size ? `?${params}` : ""}`); } useEffect(() => { if (search === query.q) return; const timeout = window.setTimeout(() => navigate({ q: search, page: 1 }), 350); return () => window.clearTimeout(timeout); }, [search, query.q]); // eslint-disable-line react-hooks/exhaustive-deps
  const columns = useMemo<ColumnDef<StockRow>[]>(() => [{ accessorKey: "sku", header: ({ column }) => <DataTableColumnHeader column={column} title="SKU" />, cell: ({ row }) => <span className="font-medium tabular-nums">{row.original.sku}</span> }, { accessorKey: "productName", id: "name", header: ({ column }) => <DataTableColumnHeader column={column} title="สินค้า" />, cell: ({ row }) => <div className="min-w-48"><p className="font-medium">{row.original.productName}</p><p className="type-caption tabular-nums">{row.original.barcode || "ไม่มีบาร์โค้ด"}</p></div> }, { accessorKey: "warehouseName", id: "warehouse", header: ({ column }) => <DataTableColumnHeader column={column} title="คลังสินค้า" /> }, { id: "unit", header: "หน่วย", enableSorting: false, cell: ({ row }) => row.original.unitName }, { accessorKey: "quantity", header: ({ column }) => <DataTableColumnHeader column={column} title="จำนวนคงเหลือ" />, meta: { align: "right" }, cell: ({ row }) => <span className="font-medium tabular-nums">{formatQuantityDecimal(row.original.quantity, row.original.unitSymbol)}</span> }, { accessorKey: "minimumStock", header: "สต็อกขั้นต่ำ", enableSorting: false, meta: { align: "right" }, cell: ({ row }) => <span className="tabular-nums">{formatQuantityDecimal(row.original.minimumStock, row.original.unitSymbol)}</span> }, { accessorKey: "status", header: "สถานะ", enableSorting: false, cell: ({ row }) => <StatusBadge status={stockStatusConfig[row.original.status].badge} /> }, { accessorKey: "updatedAt", header: ({ column }) => <DataTableColumnHeader column={column} title="เคลื่อนไหวล่าสุด" />, cell: ({ row }) => <span className="whitespace-nowrap tabular-nums">{row.original.lastMovementAt ? formatDateTime(row.original.lastMovementAt) : "—"}</span> }], []);
  const filters = <><Select value={query.warehouseId} onValueChange={(value) => navigate({ warehouseId: value, page: 1 })}><SelectTrigger className="w-full md:w-44" aria-label="คลังสินค้า"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกคลังสินค้า</SelectItem>{warehouses.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select><Select value={query.categoryId} onValueChange={(value) => navigate({ categoryId: value, page: 1 })}><SelectTrigger className="w-full md:w-44" aria-label="หมวดหมู่"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกหมวดหมู่</SelectItem>{categories.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select><Select value={query.status} onValueChange={(value) => navigate({ status: value, page: 1 })}><SelectTrigger className="w-full md:w-40" aria-label="สถานะสต็อก"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกสถานะสต็อก</SelectItem><SelectItem value="IN_STOCK">มีสินค้า</SelectItem><SelectItem value="LOW_STOCK">สต็อกต่ำ</SelectItem><SelectItem value="OUT_OF_STOCK">สินค้าหมด</SelectItem></SelectContent></Select><Select value={query.productStatus} onValueChange={(value) => navigate({ productStatus: value, page: 1 })}><SelectTrigger className="w-full md:w-40" aria-label="สถานะสินค้า"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">สินค้าทุกสถานะ</SelectItem><SelectItem value="ACTIVE">ใช้งาน</SelectItem><SelectItem value="INACTIVE">ไม่ใช้งาน</SelectItem></SelectContent></Select></>;
  const actions = <>{canTransfer && <Button size="sm" variant="outline" asChild><Link href="/inventory/transfers/new"><ArrowLeftRight className="size-4" aria-hidden="true" />โอนย้าย</Link></Button>}{canAdjust && <Button size="sm" asChild><Link href="/inventory/adjustments/new"><SlidersHorizontal className="size-4" aria-hidden="true" />ปรับปรุงสต็อก</Link></Button>}</>; const activeFilterCount = [query.warehouseId, query.categoryId, query.status, query.productStatus].filter((value) => value !== "ALL").length; const sorting: SortingState = [{ id: query.sort, desc: query.order === "desc" }]; const pagination: PaginationState = { pageIndex: query.page - 1, pageSize: query.pageSize }; return <DataTable columns={columns} data={rows} searchValue={search} onSearchChange={setSearch} searchPlaceholder="ค้นหา SKU บาร์โค้ด หรือชื่อสินค้า..." filters={filters} activeFilterCount={activeFilterCount} onResetFilters={() => { setSearch(""); router.replace(pathname); }} toolbarActions={actions} emptyTitle={query.q || activeFilterCount ? "ไม่พบสต็อกที่ตรงกับตัวกรอง" : "ยังไม่มีรายการสต็อก"} emptyDescription={query.q || activeFilterCount ? "ลองเปลี่ยนคำค้นหาหรือล้างตัวกรอง" : "ยอดสต็อกจะปรากฏเมื่อมีรายการยอดยกมาหรือการเคลื่อนไหวครั้งแรก"} manualPagination manualSorting manualFiltering pageCount={pageCount} totalRows={total} pagination={pagination} onPaginationChange={(next) => navigate({ page: next.pageIndex + 1, pageSize: next.pageSize })} sorting={sorting} onSortingChange={(next) => { const selected = next[0]; if (selected) navigate({ sort: selected.id, order: selected.desc ? "desc" : "asc", page: 1 }); }} pageSizeOptions={[20, 50, 100]} getRowId={(row) => row.id} onRowClick={(row) => router.push(`/inventory/stock/${row.original.productId}`)} />; }
