"use client";
/* eslint-disable react-hooks/exhaustive-deps -- row actions intentionally capture the current table callback. */

import { zodResolver } from "@hookform/resolvers/zod";
import type { ColumnDef, PaginationState, SortingState } from "@tanstack/react-table";
import { Pencil, Plus } from "lucide-react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";
import { DataTable } from "@/components/shared/data-table";
import { DataTableColumnHeader } from "@/components/shared/data-table-column-header";
import { FormField } from "@/components/shared/form-layout";
import { StatusBadge } from "@/components/shared/status-badge";
import { useToast } from "@/components/shared/toast-provider";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { changeWarehouseStatusAction, saveWarehouseAction } from "@/features/inventory/actions";
import type { WarehouseRow } from "@/features/inventory/types";
import { formatDateTime } from "@/lib/formatters";
import { warehouseFormSchema, type WarehouseFormValues, type WarehouseListQuery } from "@/validations/inventory";

function WarehouseDialog({ open, onOpenChange, warehouse }: { open: boolean; onOpenChange: (open: boolean) => void; warehouse?: WarehouseRow }) { const router = useRouter(); const { toast } = useToast(); const form = useForm<WarehouseFormValues>({ resolver: zodResolver(warehouseFormSchema), values: warehouse ? { id: warehouse.id, code: warehouse.code, name: warehouse.name, isDefault: warehouse.isDefault } : { code: "", name: "", isDefault: false } }); async function submit(values: WarehouseFormValues) { const result = await saveWarehouseAction(values); if (!result.ok) { form.setError("root", { message: result.message }); return; } toast({ variant: "success", title: warehouse ? "บันทึกคลังสินค้าแล้ว" : "เพิ่มคลังสินค้าแล้ว" }); onOpenChange(false); router.refresh(); } return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{warehouse ? "แก้ไขคลังสินค้า" : "เพิ่มคลังสินค้า"}</DialogTitle><DialogDescription>คลังที่มีประวัติจะปิดใช้งานแทนการลบ</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={form.handleSubmit(submit)} noValidate>{form.formState.errors.root?.message && <Alert variant="danger"><AlertDescription>{form.formState.errors.root.message}</AlertDescription></Alert>}<FormField label="รหัสคลังสินค้า" htmlFor="warehouse-code" required error={form.formState.errors.code?.message}><Input id="warehouse-code" {...form.register("code")} /></FormField><FormField label="ชื่อคลังสินค้า" htmlFor="warehouse-name" required error={form.formState.errors.name?.message}><Input id="warehouse-name" {...form.register("name")} /></FormField><FormField label="คลังหลัก" htmlFor="warehouse-default" description="การเลือกคลังนี้จะยกเลิกคลังหลักเดิม"><Controller name="isDefault" control={form.control} render={({ field }) => <label className="flex min-h-10 items-center gap-3"><Switch id="warehouse-default" checked={field.value} onCheckedChange={field.onChange} /><span className="text-sm">ใช้เป็นคลังหลัก</span></label>} /></FormField><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>ยกเลิก</Button><Button type="submit" loading={form.formState.isSubmitting}>บันทึก</Button></DialogFooter></form></DialogContent></Dialog>; }

export function WarehouseTable({ rows, total, pageCount, query, canManage }: { rows: WarehouseRow[]; total: number; pageCount: number; query: WarehouseListQuery; canManage: boolean }) { const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const { toast } = useToast(); const [search, setSearch] = useState(query.q); const [editing, setEditing] = useState<WarehouseRow | null | undefined>(); function navigate(changes: Record<string, string | number | undefined>) { const params = new URLSearchParams(searchParams.toString()); for (const [key, value] of Object.entries(changes)) if (value === undefined || value === "" || value === "ALL") params.delete(key); else params.set(key, String(value)); router.replace(`${pathname}${params.size ? `?${params}` : ""}`); } useEffect(() => { if (search === query.q) return; const timeout = window.setTimeout(() => navigate({ q: search, page: 1 }), 350); return () => window.clearTimeout(timeout); }, [search, query.q]);
  async function toggle(row: WarehouseRow) { const result = await changeWarehouseStatusAction({ id: row.id, status: row.status === "ACTIVE" ? "INACTIVE" : "ACTIVE" }); if (result.ok) { toast({ variant: "success", title: "อัปเดตสถานะคลังสินค้าแล้ว" }); router.refresh(); } else toast({ variant: "danger", title: result.message }); }
  const columns = useMemo<ColumnDef<WarehouseRow>[]>(() => [{ accessorKey: "code", header: ({ column }) => <DataTableColumnHeader column={column} title="รหัส" />, cell: ({ row }) => <span className="font-medium tabular-nums">{row.original.code}</span> }, { accessorKey: "name", header: ({ column }) => <DataTableColumnHeader column={column} title="คลังสินค้า" />, cell: ({ row }) => <div><p className="font-medium">{row.original.name}</p>{row.original.isDefault && <p className="type-caption">คลังหลัก</p>}</div> }, { accessorKey: "status", header: ({ column }) => <DataTableColumnHeader column={column} title="สถานะ" />, cell: ({ row }) => <StatusBadge status={row.original.status === "ACTIVE" ? "active" : "inactive"} /> }, { id: "history", header: "ประวัติ", enableSorting: false, cell: ({ row }) => <span className="tabular-nums">{row.original.movementCount} รายการ</span> }, { accessorKey: "updatedAt", header: ({ column }) => <DataTableColumnHeader column={column} title="แก้ไขล่าสุด" />, cell: ({ row }) => <span className="whitespace-nowrap tabular-nums">{formatDateTime(row.original.updatedAt)}</span> }, ...(canManage ? [{ id: "actions", header: "", enableSorting: false, cell: ({ row }: { row: { original: WarehouseRow } }) => <div className="flex justify-end gap-1" onClick={(event) => event.stopPropagation()}><Button size="icon" variant="ghost" aria-label={`แก้ไข ${row.original.name}`} onClick={() => setEditing(row.original)}><Pencil className="size-4" /></Button><ConfirmDialog trigger={<Button size="sm" variant="ghost">{row.original.status === "ACTIVE" ? "ปิดใช้" : "เปิดใช้"}</Button>} title={`${row.original.status === "ACTIVE" ? "ปิด" : "เปิด"}ใช้งานคลังสินค้า?`} description="ประวัติการเคลื่อนไหวและยอดคงเหลือจะยังคงอยู่ คลังที่ปิดใช้งานจะใช้ทำรายการใหม่ไม่ได้" confirmLabel="ยืนยัน" destructive={row.original.status === "ACTIVE"} onConfirm={() => toggle(row.original)} /></div> }] as ColumnDef<WarehouseRow>[] : [])], [canManage]);
  const sorting: SortingState = [{ id: query.sort, desc: query.order === "desc" }]; const pagination: PaginationState = { pageIndex: query.page - 1, pageSize: query.pageSize }; return <><DataTable columns={columns} data={rows} searchValue={search} onSearchChange={setSearch} searchPlaceholder="ค้นหารหัสหรือชื่อคลังสินค้า..." filters={<Select value={query.status} onValueChange={(value) => navigate({ status: value, page: 1 })}><SelectTrigger className="w-full md:w-40" aria-label="สถานะคลังสินค้า"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกสถานะ</SelectItem><SelectItem value="ACTIVE">ใช้งาน</SelectItem><SelectItem value="INACTIVE">ไม่ใช้งาน</SelectItem></SelectContent></Select>} activeFilterCount={query.status === "ALL" ? 0 : 1} onResetFilters={() => { setSearch(""); router.replace(pathname); }} toolbarActions={canManage ? <Button size="sm" onClick={() => setEditing(null)}><Plus className="size-4" aria-hidden="true" />เพิ่มคลังสินค้า</Button> : undefined} emptyTitle={query.q || query.status !== "ALL" ? "ไม่พบคลังสินค้าที่ตรงกับตัวกรอง" : "ยังไม่มีคลังสินค้า"} emptyDescription="เพิ่มคลังสินค้าก่อนบันทึกการเคลื่อนไหวสต็อก" manualPagination manualSorting manualFiltering pageCount={pageCount} totalRows={total} pagination={pagination} onPaginationChange={(next) => navigate({ page: next.pageIndex + 1, pageSize: next.pageSize })} sorting={sorting} onSortingChange={(next) => { const selected = next[0]; if (selected) navigate({ sort: selected.id, order: selected.desc ? "desc" : "asc", page: 1 }); }} pageSizeOptions={[20, 50, 100]} getRowId={(row) => row.id} />{editing !== undefined && <WarehouseDialog open onOpenChange={(open) => { if (!open) setEditing(undefined); }} warehouse={editing ?? undefined} />}</>; }
