"use client";

import { Check, ChevronDown, Minus, Plus } from "lucide-react";
import { forwardRef, useId, useRef, useState, type ComponentProps, type HTMLAttributes, type ReactNode } from "react";
import { Input } from "@/components/ui/input";
export { DateInput } from "@/components/ui/date-input";
import { cn } from "@/lib/utils";

type NumberInputProps = Omit<ComponentProps<typeof Input>, "type"> & { prefix?: ReactNode };
export const NumberInput = forwardRef<HTMLInputElement, NumberInputProps>(function NumberInput({ className, disabled, readOnly, prefix, onWheel, ...props }, forwardedRef) {
  const inputRef = useRef<HTMLInputElement>(null);
  function change(direction: "up" | "down") { const input = inputRef.current; if (!input || disabled || readOnly) return; if (direction === "up") input.stepUp(); else input.stepDown(); input.dispatchEvent(new Event("input", { bubbles: true })); input.focus(); }
  return <div className="relative"><Input ref={(node) => { inputRef.current = node; if (typeof forwardedRef === "function") forwardedRef(node); else if (forwardedRef) forwardedRef.current = node; }} type="number" inputMode="decimal" disabled={disabled} readOnly={readOnly} className={cn("appearance-textfield px-12 tabular-nums [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none", prefix && "pl-16", className)} onWheel={(event) => { event.currentTarget.blur(); onWheel?.(event); }} {...props} /><button type="button" className="absolute inset-y-0 left-0 flex size-10 items-center justify-center border-r border-input text-muted-foreground hover:bg-accent hover:text-accent-foreground focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-ring disabled:cursor-not-allowed disabled:opacity-50 sm:size-9" aria-label="ลดค่า" disabled={disabled || readOnly} onMouseDown={(event) => event.preventDefault()} onClick={() => change("down")}><Minus className="size-4" aria-hidden="true" /></button>{prefix && <span className="pointer-events-none absolute left-11 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">{prefix}</span>}<button type="button" className="absolute inset-y-0 right-0 flex size-10 items-center justify-center border-l border-input text-muted-foreground hover:bg-accent hover:text-accent-foreground focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-ring disabled:cursor-not-allowed disabled:opacity-50 sm:size-9" aria-label="เพิ่มค่า" disabled={disabled || readOnly} onMouseDown={(event) => event.preventDefault()} onClick={() => change("up")}><Plus className="size-4" aria-hidden="true" /></button></div>;
});
export function CurrencyInput({ className, disabled, ...props }: Omit<ComponentProps<typeof Input>, "type">) { return <NumberInput prefix="฿" step="0.01" readOnly={disabled} aria-disabled={disabled} className={cn("text-right", disabled && "cursor-not-allowed bg-muted opacity-70", className)} {...props} />; }
type ComboboxProps = Omit<ComponentProps<typeof Input>, "list" | "onChange"> & { options: Array<{ value: string; label: string }>; onValueChange?: (value: string) => void };
export function Combobox({ options, onValueChange, disabled, value, ...props }: ComboboxProps) {
  const id = useId(); const inputRef = useRef<HTMLInputElement>(null); const wrapperRef = useRef<HTMLDivElement>(null); const [open, setOpen] = useState(false); const [activeIndex, setActiveIndex] = useState(-1); const [uncontrolledValue, setUncontrolledValue] = useState(""); const [search, setSearch] = useState("");
  const displayValue = typeof value === "string" ? value : uncontrolledValue; const query = search.trim().toLocaleLowerCase("th-TH"); const filtered = query ? options.filter((option) => `${option.value} ${option.label}`.toLocaleLowerCase("th-TH").includes(query)) : options;
  function update(nextValue: string) { if (typeof value !== "string") setUncontrolledValue(nextValue); onValueChange?.(nextValue); }
  function select(option: { value: string }) { update(option.value); setSearch(""); setOpen(false); inputRef.current?.focus(); }
  return <div ref={wrapperRef} className="relative"><Input ref={inputRef} role="combobox" autoComplete="off" aria-autocomplete="list" aria-expanded={open} aria-controls={`${id}-listbox`} aria-activedescendant={activeIndex >= 0 ? `${id}-option-${activeIndex}` : undefined} disabled={disabled} value={displayValue} className="pr-9" onFocus={(event) => { setOpen(true); event.currentTarget.select(); }} onBlur={() => requestAnimationFrame(() => { if (!wrapperRef.current?.contains(document.activeElement)) setOpen(false); })} onChange={(event) => { update(event.target.value); setSearch(event.target.value); setOpen(true); setActiveIndex(-1); }} onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setOpen(true); setActiveIndex((index) => Math.min(index + 1, filtered.length - 1)); } else if (event.key === "ArrowUp") { event.preventDefault(); setOpen(true); setActiveIndex((index) => Math.max(index - 1, 0)); } else if (event.key === "Enter" && open && activeIndex >= 0 && filtered[activeIndex]) { event.preventDefault(); select(filtered[activeIndex]); } else if (event.key === "Escape") { setOpen(false); setActiveIndex(-1); } }} {...props} /><button type="button" tabIndex={-1} disabled={disabled} aria-label="เปิดรายการ" className="absolute inset-y-0 right-0 flex w-9 items-center justify-center text-muted-foreground" onMouseDown={(event) => event.preventDefault()} onClick={() => { setSearch(""); setOpen((current) => !current); inputRef.current?.focus(); }}><ChevronDown className="size-4" aria-hidden="true" /></button>{open && <div id={`${id}-listbox`} role="listbox" className="absolute z-50 mt-1 max-h-60 w-full overflow-auto rounded-md border border-border/80 bg-popover p-1 shadow-md">{filtered.length ? filtered.map((option, index) => <button key={`${option.value}-${index}`} id={`${id}-option-${index}`} type="button" role="option" aria-selected={option.value === displayValue} className={cn("flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-left text-sm outline-none hover:bg-accent focus:bg-accent", activeIndex === index && "bg-accent")} onMouseDown={(event) => event.preventDefault()} onMouseEnter={() => setActiveIndex(index)} onClick={() => select(option)}>{option.value === displayValue && <Check className="size-4 shrink-0 text-primary" aria-hidden="true" />}<span className={cn("min-w-4", option.value !== displayValue && "pl-4")}>{option.label}</span></button>) : <p className="px-2 py-1.5 text-sm text-muted-foreground">ไม่พบรายการ</p>}</div>}</div>;
}

type RadioGroupProps = Omit<HTMLAttributes<HTMLDivElement>, "onChange" | "defaultValue"> & { name: string; value?: string; defaultValue?: string; onChange?: (value: string) => void; options: Array<{ value: string; label: string; disabled?: boolean }>; disabled?: boolean };
export function RadioGroup({ name, value, defaultValue, onChange, options, disabled, className, ...props }: RadioGroupProps) { return <div role="radiogroup" className={cn("flex flex-wrap gap-x-4 gap-y-2", className)} {...props}>{options.map((option) => <label key={option.value} className="flex min-h-8 items-center gap-2 text-sm"><input type="radio" name={name} value={option.value} checked={value !== undefined ? value === option.value : undefined} defaultChecked={value === undefined ? defaultValue === option.value : undefined} disabled={disabled || option.disabled} onChange={(event) => onChange?.(event.target.value)} className="size-4 accent-primary focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring" /><span>{option.label}</span></label>)}</div>; }
