"use client";

import type { ColumnDef, PaginationState, SortingState } from "@tanstack/react-table";
import { Plus } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { DataTable } from "@/components/shared/data-table";
import { DataTableColumnHeader } from "@/components/shared/data-table-column-header";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { CategoryOption, ProductRow } from "@/features/products/types";
import { formatCurrencyDecimal } from "@/lib/formatters";
import type { ProductListQuery } from "@/validations/product";

export function ProductTable({ rows, total, pageCount, query, categories, canCreate }: { rows: ProductRow[]; total: number; pageCount: number; query: ProductListQuery; categories: CategoryOption[]; canCreate: boolean }) { const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const [search, setSearch] = useState(query.q); function navigate(changes: Record<string, string | number | undefined>) { const params = new URLSearchParams(searchParams.toString()); for (const [key, value] of Object.entries(changes)) if (value === undefined || value === "" || value === "ALL") params.delete(key); else params.set(key, String(value)); router.replace(`${pathname}${params.size ? `?${params}` : ""}`); } useEffect(() => { if (search === query.q) return; const timeout = window.setTimeout(() => navigate({ q: search, page: 1 }), 350); return () => window.clearTimeout(timeout); }, [search, query.q]); // eslint-disable-line react-hooks/exhaustive-deps
  const columns = useMemo<ColumnDef<ProductRow>[]>(() => [{ accessorKey: "sku", header: ({ column }) => <DataTableColumnHeader column={column} title="SKU" />, cell: ({ row }) => <span className="font-medium tabular-nums">{row.original.sku}</span> }, { accessorKey: "name", header: ({ column }) => <DataTableColumnHeader column={column} title="สินค้า" />, cell: ({ row }) => <div className="min-w-44 max-w-72"><p className="truncate font-medium">{row.original.name}</p>{row.original.baseUnit?.barcode && <p className="truncate text-xs tabular-nums text-muted-foreground">{row.original.baseUnit.barcode}</p>}</div> }, { id: "category", header: "หมวดหมู่", enableSorting: false, cell: ({ row }) => row.original.category?.name ?? "—" }, { id: "baseUnit", header: "หน่วย", enableSorting: false, cell: ({ row }) => row.original.baseUnit ? `${row.original.baseUnit.unit.nameTh} (${row.original.baseUnit.unit.symbol})` : "—" }, { id: "retailPrice", header: "ราคาปลีก", enableSorting: false, meta: { align: "right" }, cell: ({ row }) => <span className="tabular-nums">{row.original.baseUnit ? formatCurrencyDecimal(row.original.baseUnit.retailPrice) : "—"}</span> }, { id: "wholesalePrice", header: "ราคาส่ง", enableSorting: false, meta: { align: "right" }, cell: ({ row }) => <span className="tabular-nums">{row.original.baseUnit ? formatCurrencyDecimal(row.original.baseUnit.wholesalePrice) : "—"}</span> }, { accessorKey: "reorderLevel", header: "สต็อกขั้นต่ำ", enableSorting: false, meta: { align: "right" }, cell: ({ row }) => <span className="tabular-nums">{row.original.reorderLevel} {row.original.baseUnit?.unit.symbol ?? ""}</span> }, { accessorKey: "status", header: "สถานะ", enableSorting: false, cell: ({ row }) => <StatusBadge status={row.original.status === "ACTIVE" ? "active" : "inactive"} /> }], []);
  const activeFilterCount = [query.categoryId, query.status].filter((value) => value !== "ALL").length; const sorting: SortingState = [{ id: query.sort, desc: query.order === "desc" }]; const pagination: PaginationState = { pageIndex: query.page - 1, pageSize: query.pageSize }; const filters = <><Select value={query.categoryId} onValueChange={(value) => navigate({ categoryId: value, page: 1 })}><SelectTrigger className="w-full sm:w-44" aria-label="หมวดหมู่"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกหมวดหมู่</SelectItem>{categories.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}{!item.isActive ? " — ไม่ใช้งาน" : ""}</SelectItem>)}</SelectContent></Select><Select value={query.status} onValueChange={(value) => navigate({ status: value, page: 1 })}><SelectTrigger className="w-full sm:w-32" aria-label="สถานะ"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกสถานะ</SelectItem><SelectItem value="ACTIVE">ใช้งาน</SelectItem><SelectItem value="INACTIVE">ไม่ใช้งาน</SelectItem></SelectContent></Select></>;
  return <DataTable columns={columns} data={rows} searchValue={search} onSearchChange={setSearch} searchPlaceholder="ค้นหา SKU บาร์โค้ด หรือชื่อสินค้า..." filters={filters} activeFilterCount={activeFilterCount} onResetFilters={() => { setSearch(""); router.replace(pathname); }} toolbarActions={canCreate ? <Button size="sm" asChild><Link href="/inventory/products/new"><Plus className="size-4" aria-hidden="true" />เพิ่มสินค้า</Link></Button> : undefined} emptyTitle={query.q || activeFilterCount ? "ไม่พบสินค้าที่ตรงกับตัวกรอง" : "ยังไม่มีข้อมูลสินค้า"} emptyDescription={query.q || activeFilterCount ? "ลองเปลี่ยนคำค้นหาหรือล้างตัวกรอง" : "เพิ่มสินค้ารายแรกเพื่อเริ่มกำหนดราคา"} emptyAction={!query.q && !activeFilterCount && canCreate ? <Button asChild><Link href="/inventory/products/new">เพิ่มสินค้า</Link></Button> : undefined} manualPagination manualSorting manualFiltering pageCount={pageCount} totalRows={total} pagination={pagination} onPaginationChange={(next) => navigate({ page: next.pageIndex + 1, pageSize: next.pageSize })} sorting={sorting} onSortingChange={(next) => { const selected = next[0]; if (selected) navigate({ sort: selected.id, order: selected.desc ? "desc" : "asc", page: 1 }); }} pageSizeOptions={[20, 50, 100]} getRowId={(row) => row.id} onRowClick={(row) => router.push(`/inventory/products/${row.original.id}`)} />;
}
