"use server";

import { revalidatePath } from "next/cache";
import { requirePermission } from "@/services/auth.service";
import { assignDeliveryOrder, cancelDeliveryTrip, changeVehicleStatus, completeDeliveryTrip, createDeliveryTrip, DeliveryRuleError, dispatchDeliveryTrip, loadDeliveryTrip, recordDeliveryResult, removeDeliveryOrder, reorderDeliveryStops, returnFailedDelivery, saveVehicle, updateDeliveryTrip, VehicleRuleError } from "@/services/delivery.service";
import { assignDeliveryOrderSchema, deliveryResultSchema, deliveryTripActionSchema, deliveryTripFormSchema, removeDeliveryOrderSchema, reorderDeliveryStopsSchema, vehicleFormSchema, vehicleStatusSchema } from "@/validations/delivery";

export type DeliveryActionResult = { ok: true; id: string } | { ok: false; message: string };
function actor(context: Awaited<ReturnType<typeof requirePermission>>) { return { id: context.user.id === "development-preview" ? null : context.user.id, name: context.user.name }; }
function errorResult(error: unknown): DeliveryActionResult { if (error instanceof DeliveryRuleError || error instanceof VehicleRuleError) return { ok: false, message: error.message }; if (typeof error === "object" && error && "code" in error && (error.code === "P2034" || error.code === "P2002")) return { ok: false, message: error.code === "P2002" ? "ข้อมูลนี้ถูกใช้งานแล้วหรือมีการดำเนินการซ้ำ" : "ข้อมูลหรือสต็อกมีการเปลี่ยนแปลงพร้อมกัน กรุณาโหลดหน้าใหม่แล้วลองอีกครั้ง" }; console.error("Delivery action failed", error); return { ok: false, message: "ไม่สามารถดำเนินการจัดส่งได้ กรุณาลองอีกครั้ง" }; }
function refreshDelivery(id?: string) { revalidatePath("/delivery"); revalidatePath("/delivery/trips"); revalidatePath("/delivery/vehicles"); revalidatePath("/inventory/stock"); revalidatePath("/inventory/movements"); revalidatePath("/sales/orders"); if (id) revalidatePath(`/delivery/trips/${id}`); }
async function mutate(operation: (access: Awaited<ReturnType<typeof requirePermission>>) => Promise<string>): Promise<DeliveryActionResult> { const access = await requirePermission("delivery.manage"); try { const id = await operation(access); refreshDelivery(id); return { ok: true, id }; } catch (error) { return errorResult(error); } }

export async function createDeliveryTripAction(input: unknown) { const parsed = deliveryTripFormSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return mutate((access) => createDeliveryTrip(parsed.data, actor(access))); }
export async function updateDeliveryTripAction(input: unknown) { const parsed = deliveryTripFormSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const id = parsed.data.id; if (!id) return { ok: false as const, message: "ไม่พบรหัสรอบจัดส่ง" }; return mutate((access) => updateDeliveryTrip({ ...parsed.data, id }, actor(access))); }
export async function assignDeliveryOrderAction(input: unknown) { const parsed = assignDeliveryOrderSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return mutate((access) => assignDeliveryOrder(parsed.data.tripId, parsed.data.orderId, actor(access))); }
export async function removeDeliveryOrderAction(input: unknown) { const parsed = removeDeliveryOrderSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return mutate((access) => removeDeliveryOrder(parsed.data.tripId, parsed.data.deliveryId, actor(access))); }
export async function reorderDeliveryStopsAction(input: unknown) { const parsed = reorderDeliveryStopsSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return mutate((access) => reorderDeliveryStops(parsed.data.tripId, parsed.data.stopIds, actor(access))); }
export async function loadDeliveryTripAction(input: unknown) { const parsed = deliveryTripActionSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: "ไม่พบรอบจัดส่ง" }; return mutate((access) => loadDeliveryTrip(parsed.data.id, actor(access))); }
export async function dispatchDeliveryTripAction(input: unknown) { const parsed = deliveryTripActionSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: "ไม่พบรอบจัดส่ง" }; return mutate((access) => dispatchDeliveryTrip(parsed.data.id, actor(access))); }
export async function completeDeliveryTripAction(input: unknown) { const parsed = deliveryTripActionSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: "ไม่พบรอบจัดส่ง" }; return mutate((access) => completeDeliveryTrip(parsed.data.id, actor(access))); }
export async function cancelDeliveryTripAction(input: unknown) { const parsed = deliveryTripActionSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: "ไม่พบรอบจัดส่ง" }; return mutate((access) => cancelDeliveryTrip(parsed.data.id, actor(access))); }
export async function recordDeliveryResultAction(input: unknown) { const parsed = deliveryResultSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return mutate((access) => recordDeliveryResult(parsed.data, actor(access))); }
export async function returnFailedDeliveryAction(input: unknown) { const parsed = deliveryTripActionSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: "ไม่พบรายการจัดส่ง" }; return mutate((access) => returnFailedDelivery(parsed.data.id, actor(access))); }
export async function saveVehicleAction(input: unknown) { const parsed = vehicleFormSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return mutate((access) => saveVehicle(parsed.data, actor(access))); }
export async function changeVehicleStatusAction(input: unknown) { const parsed = vehicleStatusSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: "ข้อมูลไม่ถูกต้อง" }; return mutate((access) => changeVehicleStatus(parsed.data.id, parsed.data.status, actor(access))); }
