"use server";

import { revalidatePath } from "next/cache";
import { requirePermission } from "@/services/auth.service";
import { AccountingRuleError, cancelBillingNote, createBillingNote, createInvoice, issueBillingNote, issueInvoice, recordPayment, voidInvoice, voidPayment } from "@/services/accounting.service";
import { billingCreateSchema, cancellationSchema, documentActionSchema, invoiceCreateSchema, paymentCreateSchema } from "@/validations/accounting";

export type AccountingActionResult = { ok: true; id: string } | { ok: false; message: string };
function actor(access: Awaited<ReturnType<typeof requirePermission>>) { return { id: access.user.id === "development-preview" ? null : access.user.id, name: access.user.name }; }
function errorResult(error: unknown): AccountingActionResult { if (error instanceof AccountingRuleError) return { ok: false, message: error.message }; if (typeof error === "object" && error && "code" in error && (error.code === "P2002" || error.code === "P2034")) return { ok: false, message: error.code === "P2002" ? "มีการสร้างเอกสารนี้แล้ว กรุณาโหลดหน้าใหม่" : "ข้อมูลการเงินเปลี่ยนแปลงพร้อมกัน กรุณาโหลดหน้าใหม่แล้วลองอีกครั้ง" }; console.error("Accounting action failed", error); return { ok: false, message: "ไม่สามารถดำเนินการทางการเงินได้ กรุณาลองอีกครั้ง" }; }
function refresh(id?: string) { revalidatePath("/accounting/invoices"); revalidatePath("/accounting/billing"); revalidatePath("/accounting/payments"); revalidatePath("/accounting/receivables"); revalidatePath("/accounting/ar"); revalidatePath("/sales/orders"); if (id) { revalidatePath(`/accounting/invoices/${id}`); revalidatePath(`/accounting/billing/${id}`); revalidatePath(`/accounting/payments/${id}`); } }
async function run(permission: Parameters<typeof requirePermission>[0], operation: (access: Awaited<ReturnType<typeof requirePermission>>) => Promise<string>) { const access = await requirePermission(permission); try { const id = await operation(access); refresh(id); return { ok: true as const, id }; } catch (error) { return errorResult(error); } }

export async function createInvoiceAction(input: unknown) { const parsed = invoiceCreateSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return run("invoice.create", (access) => createInvoice(parsed.data, actor(access))); }
export async function issueInvoiceAction(input: unknown) { const parsed = documentActionSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: "ไม่พบใบแจ้งหนี้" }; return run("invoice.issue", (access) => issueInvoice(parsed.data.id, actor(access))); }
export async function voidInvoiceAction(input: unknown) { const parsed = cancellationSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return run("invoice.cancel", (access) => voidInvoice(parsed.data.id, parsed.data.reason, actor(access))); }
export async function createBillingNoteAction(input: unknown) { const parsed = billingCreateSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return run("billing.manage", (access) => createBillingNote(parsed.data, actor(access))); }
export async function issueBillingNoteAction(input: unknown) { const parsed = documentActionSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: "ไม่พบใบวางบิล" }; return run("billing.manage", (access) => issueBillingNote(parsed.data.id, actor(access))); }
export async function cancelBillingNoteAction(input: unknown) { const parsed = cancellationSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return run("billing.manage", (access) => cancelBillingNote(parsed.data.id, parsed.data.reason, actor(access))); }
export async function recordPaymentAction(input: unknown) { const parsed = paymentCreateSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("payment.create"); await requirePermission("payment.allocate"); try { const id = await recordPayment(parsed.data, actor(access)); refresh(id); return { ok: true as const, id }; } catch (error) { return errorResult(error); } }
export async function voidPaymentAction(input: unknown) { const parsed = cancellationSchema.safeParse(input); if (!parsed.success) return { ok: false as const, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; return run("payment.cancel", (access) => voidPayment(parsed.data.id, parsed.data.reason, actor(access))); }
