"use client";

import { ArcElement, BarElement, CategoryScale, Chart as ChartJS, Filler, Legend, LinearScale, LineElement, PointElement, Tooltip, type ChartOptions } from "chart.js";
import { useTheme } from "next-themes";
import { Bar, Doughnut, Line } from "react-chartjs-2";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { chartColors } from "@/config/charts";
import { formatCurrencyDecimal, formatDate } from "@/lib/formatters";

ChartJS.register(ArcElement, BarElement, CategoryScale, Filler, Legend, LinearScale, LineElement, PointElement, Tooltip);
type SalesData = { byPayment: Record<string, string>; retailWholesale: { RETAIL: string; WHOLESALE: string }; trend: Array<{ date: string; value: string }>; byStatus: Array<{ label: string; value: number }> };
function EmptyChart() { return <div className="flex h-52 items-center justify-center text-sm text-muted-foreground">ไม่มีข้อมูลในช่วงนี้</div>; }
function SalesStatusSummary({ items }: { items: SalesData["byStatus"] }) { return <Card className="xl:col-span-4"><CardHeader><CardTitle>สถานะคำสั่งซื้อ</CardTitle><CardDescription>จำนวนคำสั่งซื้อทุกสถานะในช่วงวันที่เลือก รวมฉบับร่างและยกเลิกเพื่อการติดตามงาน</CardDescription></CardHeader><CardContent>{items.length ? <ul className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{items.map((item) => <li key={item.label} className="flex items-center justify-between rounded-md border px-3 py-2 text-sm"><span>{item.label}</span><span className="font-semibold tabular-nums">{item.value.toLocaleString("th-TH")}</span></li>)}</ul> : <p className="py-4 text-center text-sm text-muted-foreground">ไม่มีคำสั่งซื้อในช่วงนี้</p>}</CardContent></Card>; }
export function DashboardCharts({ sales }: { sales: SalesData }) {
  const { resolvedTheme } = useTheme(); const theme = resolvedTheme === "dark" ? chartColors.dark : chartColors.light; const tooltipText = resolvedTheme === "dark" ? "#172033" : "#ffffff"; const tooltipBody = resolvedTheme === "dark" ? "#334155" : "#e2e8f0";
  const basePlugins = { legend: { display: false }, tooltip: { backgroundColor: theme.tooltip, titleColor: tooltipText, bodyColor: tooltipBody, padding: 10 } }; const scale = { beginAtZero: true, grid: { color: theme.grid }, ticks: { color: theme.text, font: { size: 11 } }, border: { display: false } };
  const lineOptions: ChartOptions<"line"> = { responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: "index" }, plugins: basePlugins, scales: { x: { grid: { display: false }, ticks: { color: theme.text, font: { size: 11 } }, border: { display: false } }, y: { ...scale, ticks: { ...scale.ticks, callback: (value) => `฿${Number(value).toLocaleString("th-TH")}` } } } };
  const barOptions: ChartOptions<"bar"> = { responsive: true, maintainAspectRatio: false, plugins: basePlugins, scales: { x: { grid: { display: false }, ticks: { color: theme.text, font: { size: 11 } }, border: { display: false } }, y: scale } };
  const payment = [sales.byPayment.CASH ?? "0.00", sales.byPayment.CREDIT ?? "0.00"]; const customer = [sales.retailWholesale.RETAIL, sales.retailWholesale.WHOLESALE];
  return <section aria-label="กราฟสรุปยอดขาย" className="grid gap-3 xl:grid-cols-4"><Card className="xl:col-span-2"><CardHeader><CardTitle>แนวโน้มยอดขายตามคำสั่งซื้อ</CardTitle><CardDescription>ยอดรวมรายวันตามวันที่สั่งซื้อ</CardDescription></CardHeader><CardContent>{sales.trend.length ? <div className="h-52"><Line role="img" aria-label={`แนวโน้มยอดขาย ${sales.trend.map((item) => `${formatDate(item.date)} ${formatCurrencyDecimal(item.value)}`).join(", ")}`} options={lineOptions} data={{ labels: sales.trend.map((item) => formatDate(item.date)), datasets: [{ data: sales.trend.map((item) => Number(item.value)), borderColor: chartColors.primary, backgroundColor: "rgba(14, 116, 144, 0.1)", pointBackgroundColor: chartColors.primary, pointRadius: 2, borderWidth: 2, fill: true, tension: 0.25 }] }} /></div> : <EmptyChart />}</CardContent></Card><Card><CardHeader><CardTitle>เงินสดเทียบกับเครดิต</CardTitle><CardDescription>ประเภทการขายจากคำสั่งซื้อ</CardDescription></CardHeader><CardContent>{payment.some((value) => Number(value) > 0) ? <div className="mx-auto h-52 max-w-60"><Doughnut role="img" aria-label={`ยอดขายเงินสด ${formatCurrencyDecimal(payment[0]!)} เครดิต ${formatCurrencyDecimal(payment[1]!)}`} options={{ responsive: true, maintainAspectRatio: false, cutout: "68%", plugins: { legend: { position: "bottom", labels: { boxWidth: 9, boxHeight: 9, color: theme.text, padding: 14, font: { size: 11 } } }, tooltip: basePlugins.tooltip } }} data={{ labels: ["เงินสด", "เครดิต"], datasets: [{ data: payment.map(Number), backgroundColor: [chartColors.success, chartColors.warning], borderWidth: 0, spacing: 2 }] }} /></div> : <EmptyChart />}</CardContent></Card><Card><CardHeader><CardTitle>ค้าปลีกเทียบกับค้าส่ง</CardTitle><CardDescription>มูลค่าคำสั่งซื้อตามประเภทลูกค้าปัจจุบัน</CardDescription></CardHeader><CardContent>{customer.some((value) => Number(value) > 0) ? <div className="h-52"><Bar role="img" aria-label={`ค้าปลีก ${formatCurrencyDecimal(customer[0])} ค้าส่ง ${formatCurrencyDecimal(customer[1])}`} options={barOptions} data={{ labels: ["ค้าปลีก", "ค้าส่ง"], datasets: [{ data: customer.map(Number), backgroundColor: [chartColors.primary, chartColors.muted], borderRadius: 3, maxBarThickness: 44 }] }} /></div> : <EmptyChart />}</CardContent></Card><SalesStatusSummary items={sales.byStatus} /></section>;
}
