import { Pencil, Tag, Users } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { DetailHeader } from "@/components/shared/detail-header";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { priceListStatusConfig } from "@/config/products";
import { PriceListItems } from "@/features/pricing/components/price-list-items";
import { PriceListStatusAction } from "@/features/pricing/components/price-list-status-action";
import { formatDate } from "@/lib/formatters";
import { requireRouteAccess } from "@/services/auth.service";
import { getPriceList, getPricingProductUnits } from "@/services/pricing.service";

function Info({ label, value }: { label: string; value?: string | null }) { return <div><dt className="type-caption">{label}</dt><dd className="mt-0.5 text-sm font-medium leading-6">{value || "—"}</dd></div>; }
export default async function PriceListPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const [access, priceList, productUnits] = await Promise.all([requireRouteAccess(`/price-lists/${id}`), getPriceList(id), getPricingProductUnits()]); if (!priceList) notFound(); const canManage = access.permissions.includes("price_list.manage"); const status = priceListStatusConfig[priceList.status]; return <div className="page-stack"><DetailHeader title={priceList.name} identifier={priceList.code} description={priceList.description || "รายการราคาสินค้า"} section={{ label: "รายการราคา", href: "/price-lists" }} status={<StatusBadge status={status.status} />} actions={<>{canManage && <Button asChild size="sm" variant="outline"><Link href={`/price-lists/${id}/edit`}><Pencil className="size-4" aria-hidden="true" />แก้ไข</Link></Button>}{canManage && <PriceListStatusAction id={id} name={priceList.name} status={priceList.status} />}</>} /><div className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Tag className="size-4 text-muted-foreground" aria-hidden="true" />เงื่อนไขรายการราคา</CardTitle></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><Info label="สกุลเงิน" value={priceList.currency} /><Info label="วันเริ่มต้น" value={priceList.validFrom ? formatDate(priceList.validFrom) : "ไม่จำกัด"} /><Info label="วันสิ้นสุด" value={priceList.validTo ? formatDate(priceList.validTo) : "ไม่จำกัด"} /></dl></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="size-4 text-muted-foreground" aria-hidden="true" />การใช้งาน</CardTitle></CardHeader><CardContent><dl className="grid gap-4"><Info label="ลูกค้าที่กำหนดรายการราคานี้" value={`${priceList.customerCount} ราย`} /><Info label="ราคาสินค้า" value={`${priceList.items.length} รายการ`} /></dl></CardContent></Card><Card className="lg:col-span-1"><CardHeader><CardTitle>หลักการใช้ราคา</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">ราคาพิเศษลูกค้ามีลำดับสูงกว่า ตามด้วยรายการราคานี้ และราคามาตรฐานสินค้า</p></CardContent></Card></div><section className="space-y-3" aria-labelledby="items-title"><div><h2 id="items-title" className="type-section-title">ราคาสินค้า</h2><p className="type-secondary">กำหนดราคาแยกตามสินค้า หน่วย และจำนวนขั้นต่ำ</p></div><PriceListItems priceListId={id} items={priceList.items} productUnits={productUnits} canManage={canManage} /></section></div>; }
