"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { Controller, useForm } from "react-hook-form";
import { useRouter } from "next/navigation";
import { createPriceListAction, updatePriceListAction } from "@/features/pricing/actions";
import type { PriceListDetailData } from "@/features/pricing/types";
import { priceListFormSchema, type PriceListFormValues } from "@/validations/pricing";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { DateRange } from "@/components/shared/date-range";
import { FormActions, FormField, FormSection } from "@/components/shared/form-layout";
import { useToast } from "@/components/shared/toast-provider";

const defaults: PriceListFormValues = { code: "", name: "", description: "", status: "DRAFT", validFrom: "", validTo: "" };
export function PriceListForm({ priceList }: { priceList?: PriceListDetailData }) { const router = useRouter(); const { toast } = useToast(); const form = useForm<PriceListFormValues>({ resolver: zodResolver(priceListFormSchema), defaultValues: priceList ? { id: priceList.id, code: priceList.code, name: priceList.name, description: priceList.description, status: priceList.status, validFrom: priceList.validFrom, validTo: priceList.validTo } : defaults }); async function submit(values: PriceListFormValues) { const result = priceList ? await updatePriceListAction(values) : await createPriceListAction(values); if (!result.ok) { form.setError("root", { message: result.message }); return; } toast({ variant: "success", title: priceList ? "บันทึกรายการราคาแล้ว" : "สร้างรายการราคาแล้ว" }); router.push(`/price-lists/${result.id}`); router.refresh(); } return <Card><CardContent><form className="space-y-6" onSubmit={form.handleSubmit(submit)} noValidate>{form.formState.errors.root?.message && <Alert variant="danger"><AlertDescription>{form.formState.errors.root.message}</AlertDescription></Alert>}<FormSection title="ข้อมูลรายการราคา" description="ใช้กำหนดราคาขายสำหรับกลุ่มลูกค้า"><FormField label="รหัสรายการราคา" htmlFor="code" required error={form.formState.errors.code?.message}><Input id="code" placeholder="เช่น WHOLESALE_A" {...form.register("code")} /></FormField><FormField label="ชื่อรายการราคา" htmlFor="name" required error={form.formState.errors.name?.message}><Input id="name" {...form.register("name")} /></FormField><FormField label="สถานะ" htmlFor="status" required error={form.formState.errors.status?.message}><Controller name="status" control={form.control} render={({ field }) => <Select value={field.value} onValueChange={field.onChange}><SelectTrigger id="status"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="DRAFT">ฉบับร่าง</SelectItem><SelectItem value="ACTIVE">ใช้งาน</SelectItem><SelectItem value="INACTIVE">ไม่ใช้งาน</SelectItem></SelectContent></Select>} /></FormField><FormField className="sm:col-span-2 xl:col-span-3" label="คำอธิบาย" htmlFor="description" error={form.formState.errors.description?.message}><Textarea id="description" rows={3} {...form.register("description")} /></FormField></FormSection><FormSection title="ระยะเวลาที่ใช้ราคา" description="เว้นว่างได้ หากรายการราคาไม่มีวันเริ่มต้นหรือสิ้นสุด"><DateRange className="sm:col-span-2 xl:col-span-2" label="ช่วงวันที่มีผล" from={{ id: "validFrom", ...form.register("validFrom") }} to={{ id: "validTo", ...form.register("validTo") }} /></FormSection><FormActions><Button type="button" variant="outline" onClick={() => router.back()} disabled={form.formState.isSubmitting}>ยกเลิก</Button><Button type="submit" loading={form.formState.isSubmitting}>{priceList ? "บันทึกการเปลี่ยนแปลง" : "สร้างรายการราคา"}</Button></FormActions></form></CardContent></Card>; }
