"use client";

import type { ColumnDef, PaginationState, SortingState } from "@tanstack/react-table";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { DataTable } from "@/components/shared/data-table";
import { DataTableColumnHeader } from "@/components/shared/data-table-column-header";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { priceListStatusConfig } from "@/config/products";
import type { PriceListRow } from "@/features/pricing/types";
import { formatDate } from "@/lib/formatters";
import type { PriceListQuery } from "@/validations/pricing";

export function PriceListTable({ rows, total, pageCount, query, canManage }: { rows: PriceListRow[]; total: number; pageCount: number; query: PriceListQuery; canManage: boolean }) { const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const [search, setSearch] = useState(query.q); function navigate(changes: Record<string, string | number | undefined>) { const params = new URLSearchParams(searchParams.toString()); for (const [key, value] of Object.entries(changes)) if (value === undefined || value === "" || value === "ALL") params.delete(key); else params.set(key, String(value)); router.replace(`${pathname}${params.size ? `?${params}` : ""}`); } useEffect(() => { if (search === query.q) return; const timeout = window.setTimeout(() => navigate({ q: search, page: 1 }), 350); return () => window.clearTimeout(timeout); }, [search, query.q]); // eslint-disable-line react-hooks/exhaustive-deps
  const columns = useMemo<ColumnDef<PriceListRow>[]>(() => [{ accessorKey: "code", header: ({ column }) => <DataTableColumnHeader column={column} title="รหัส" />, cell: ({ row }) => <span className="font-medium tabular-nums">{row.original.code}</span> }, { accessorKey: "name", header: ({ column }) => <DataTableColumnHeader column={column} title="รายการราคา" />, cell: ({ row }) => <div className="min-w-44"><p className="font-medium">{row.original.name}</p><p className="truncate text-xs text-muted-foreground">{row.original.description || "ไม่มีคำอธิบาย"}</p></div> }, { id: "items", header: "สินค้า", enableSorting: false, meta: { align: "right" }, cell: ({ row }) => <span className="tabular-nums">{row.original.itemCount}</span> }, { id: "customers", header: "ลูกค้า", enableSorting: false, meta: { align: "right" }, cell: ({ row }) => <span className="tabular-nums">{row.original.customerCount}</span> }, { id: "period", header: "ระยะเวลา", enableSorting: false, cell: ({ row }) => <span className="whitespace-nowrap text-muted-foreground">{row.original.validFrom ? formatDate(row.original.validFrom) : "ไม่จำกัด"} – {row.original.validTo ? formatDate(row.original.validTo) : "ไม่จำกัด"}</span> }, { accessorKey: "status", header: ({ column }) => <DataTableColumnHeader column={column} title="สถานะ" />, cell: ({ row }) => <StatusBadge status={priceListStatusConfig[row.original.status].status} /> }, { accessorKey: "updatedAt", header: ({ column }) => <DataTableColumnHeader column={column} title="แก้ไขล่าสุด" />, cell: ({ row }) => <span className="whitespace-nowrap text-muted-foreground">{formatDate(row.original.updatedAt)}</span> }], []);
  const sorting: SortingState = [{ id: query.sort, desc: query.order === "desc" }]; const pagination: PaginationState = { pageIndex: query.page - 1, pageSize: query.pageSize }; const filters = <Select value={query.status} onValueChange={(value) => navigate({ status: value, page: 1 })}><SelectTrigger className="w-full sm:w-36" aria-label="สถานะ"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกสถานะ</SelectItem><SelectItem value="DRAFT">ฉบับร่าง</SelectItem><SelectItem value="ACTIVE">ใช้งาน</SelectItem><SelectItem value="INACTIVE">ไม่ใช้งาน</SelectItem></SelectContent></Select>; return <DataTable columns={columns} data={rows} searchValue={search} onSearchChange={setSearch} searchPlaceholder="ค้นหารหัสหรือชื่อรายการราคา..." filters={filters} activeFilterCount={query.status === "ALL" ? 0 : 1} onResetFilters={() => { setSearch(""); router.replace(pathname); }} emptyTitle={query.q || query.status !== "ALL" ? "ไม่พบรายการราคาที่ตรงกับตัวกรอง" : "ยังไม่มีรายการราคา"} emptyDescription={query.q || query.status !== "ALL" ? "ลองเปลี่ยนคำค้นหาหรือล้างตัวกรอง" : "สร้างรายการราคาเพื่อกำหนดราคาตามกลุ่มลูกค้า"} emptyAction={!query.q && query.status === "ALL" && canManage ? <Button asChild><Link href="/price-lists/new">สร้างรายการราคา</Link></Button> : undefined} manualPagination manualSorting manualFiltering pageCount={pageCount} totalRows={total} pagination={pagination} onPaginationChange={(next) => navigate({ page: next.pageIndex + 1, pageSize: next.pageSize })} sorting={sorting} onSortingChange={(next) => { const selected = next[0]; if (selected) navigate({ sort: selected.id, order: selected.desc ? "desc" : "asc", page: 1 }); }} pageSizeOptions={[20, 50, 100]} getRowId={(row) => row.id} onRowClick={(row) => router.push(`/price-lists/${row.original.id}`)} />; }
