import { describe, expect, it } from "vitest";
import { filterNavigation } from "@/config/navigation";
import { permissionCodes } from "@/config/permissions";
import { getRoutePermission } from "@/config/route-permissions";
import { defaultRolePermissions } from "@/config/roles";

describe("authorization configuration", () => {
  it("maps protected routes to centralized permissions", () => { expect(getRoutePermission("/sales/orders/123")).toBe("sales_order.view"); expect(getRoutePermission("/customers/123/edit")).toBe("customer.view"); expect(getRoutePermission("/inventory/products/123")).toBe("product.view"); expect(getRoutePermission("/price-lists/123")).toBe("price_list.view"); expect(getRoutePermission("/admin/users")).toBe("user.view"); });
  it("hides unauthorized navigation and empty groups", () => { const visible = filterNavigation(new Set(["dashboard.view", "customer.view"])); const items = visible.flatMap(({ items }) => items); expect(items.some(({ href }) => href === "/customers")).toBe(true); expect(items.some(({ href }) => href === "/admin/users")).toBe(false); expect(visible.some(({ label }) => label === "administration")).toBe(false); });
  it("keeps authorized navigation visible", () => { const visible = filterNavigation(new Set(["user.view"])); expect(visible.flatMap(({ items }) => items).some(({ href }) => href === "/admin/users")).toBe(true); });
  it("shows product and pricing navigation only with matching permissions", () => { const visible = filterNavigation(new Set(["product.view", "price_list.view"])); const hrefs = visible.flatMap(({ items }) => items.map(({ href }) => href)); expect(hrefs).toEqual(expect.arrayContaining(["/inventory/products", "/price-lists"])); });
  it("registers focused sales order workflow permissions", () => { expect(permissionCodes).toEqual(expect.arrayContaining(["sales_order.create", "sales_order.update", "sales_order.confirm", "sales_order.cancel", "sales_order.override_price"])); expect(defaultRolePermissions.SALES).toContain("sales_order.override_price"); });
  it("registers focused inventory permissions", () => { expect(permissionCodes).toEqual(expect.arrayContaining(["inventory.view", "inventory.adjust", "inventory.transfer", "inventory.manage_warehouse"])); expect(defaultRolePermissions.WAREHOUSE).toEqual(expect.arrayContaining(["inventory.adjust", "inventory.transfer", "inventory.manage_warehouse"])); expect(getRoutePermission("/inventory/transfers/new")).toBe("inventory.transfer"); });
  it("protects delivery routes and grants the delivery workflow to its role", () => { expect(permissionCodes).toEqual(expect.arrayContaining(["delivery.view", "delivery.manage"])); expect(defaultRolePermissions.DELIVERY).toEqual(expect.arrayContaining(["delivery.view", "delivery.manage"])); expect(getRoutePermission("/delivery/trips/new")).toBe("delivery.view"); expect(getRoutePermission("/delivery/vehicles")).toBe("delivery.view"); });
  it("registers every default role permission", () => { for (const permissions of Object.values(defaultRolePermissions)) for (const permission of permissions) expect(permissionCodes).toContain(permission); });
  it("grants administration mutations only to configured privileged roles", () => { expect(defaultRolePermissions.ADMIN).toEqual(expect.arrayContaining(["user.update", "user.disable", "role.manage"])); expect(defaultRolePermissions.SALES).not.toContain("user.update"); expect(defaultRolePermissions.SALES).not.toContain("role.manage"); });
});
