export const permissionRegistry = [
  { code: "dashboard.view", label: "ดูแดชบอร์ด", group: "ภาพรวม" },
  { code: "customer.view", label: "ดูลูกค้า", group: "การขาย" },
  { code: "customer.create", label: "สร้างลูกค้า", group: "การขาย" },
  { code: "customer.update", label: "แก้ไขลูกค้า", group: "การขาย" },
  { code: "customer.archive", label: "ปิดใช้งานลูกค้า", group: "การขาย" },
  { code: "product.view", label: "ดูสินค้า", group: "สินค้าและคลัง" },
  { code: "product.create", label: "สร้างสินค้า", group: "สินค้าและคลัง" },
  { code: "product.update", label: "แก้ไขสินค้า", group: "สินค้าและคลัง" },
  { code: "product.archive", label: "ปิดใช้งานสินค้า", group: "สินค้าและคลัง" },
  { code: "price_list.view", label: "ดูรายการราคา", group: "การขาย" },
  { code: "price_list.manage", label: "จัดการรายการราคา", group: "การขาย" },
  { code: "sales_order.view", label: "ดูคำสั่งขาย", group: "การขาย" },
  { code: "sales_order.create", label: "สร้างคำสั่งขาย", group: "การขาย" },
  { code: "sales_order.update", label: "แก้ไขคำสั่งขาย", group: "การขาย" },
  { code: "sales_order.confirm", label: "ยืนยันคำสั่งขาย", group: "การขาย" },
  { code: "sales_order.cancel", label: "ยกเลิกคำสั่งขาย", group: "การขาย" },
  { code: "delivery.view", label: "ดูการจัดส่ง", group: "จัดส่ง" },
  { code: "delivery.manage", label: "จัดการการจัดส่ง", group: "จัดส่ง" },
  { code: "inventory.view", label: "ดูสินค้าคงคลัง", group: "สินค้าและคลัง" },
  { code: "inventory.adjust", label: "ปรับปรุงสต็อก", group: "สินค้าและคลัง" },
  { code: "inventory.transfer", label: "โอนย้ายสต็อก", group: "สินค้าและคลัง" },
  { code: "invoice.view", label: "ดูใบแจ้งหนี้", group: "บัญชี" },
  { code: "invoice.create", label: "สร้างใบแจ้งหนี้", group: "บัญชี" },
  { code: "invoice.issue", label: "ออกใบแจ้งหนี้", group: "บัญชี" },
  { code: "invoice.cancel", label: "ยกเลิกใบแจ้งหนี้", group: "บัญชี" },
  { code: "billing.view", label: "ดูใบวางบิล", group: "บัญชี" },
  { code: "billing.manage", label: "จัดการใบวางบิล", group: "บัญชี" },
  { code: "payment.view", label: "ดูการชำระเงิน", group: "บัญชี" },
  { code: "payment.create", label: "บันทึกการชำระเงิน", group: "บัญชี" },
  { code: "payment.allocate", label: "จัดสรรการชำระเงิน", group: "บัญชี" },
  { code: "ar.view", label: "ดูลูกหนี้การค้า", group: "บัญชี" },
  { code: "report.view", label: "ดูรายงาน", group: "รายงาน" },
  { code: "user.view", label: "ดูผู้ใช้งาน", group: "ผู้ดูแลระบบ" },
  { code: "user.create", label: "สร้างผู้ใช้งาน", group: "ผู้ดูแลระบบ" },
  { code: "user.update", label: "แก้ไขผู้ใช้งาน", group: "ผู้ดูแลระบบ" },
  { code: "user.disable", label: "เปิดหรือปิดผู้ใช้งาน", group: "ผู้ดูแลระบบ" },
  { code: "role.view", label: "ดูบทบาท", group: "ผู้ดูแลระบบ" },
  { code: "role.manage", label: "จัดการบทบาทและสิทธิ์", group: "ผู้ดูแลระบบ" },
  { code: "audit_log.view", label: "ดูประวัติการใช้งาน", group: "ผู้ดูแลระบบ" },
  { code: "settings.view", label: "ดูการตั้งค่า", group: "ผู้ดูแลระบบ" },
  { code: "settings.manage", label: "จัดการการตั้งค่า", group: "ผู้ดูแลระบบ" },
  { code: "production.view", label: "ดูการผลิต", group: "การผลิต" },
  { code: "production.manage", label: "จัดการการผลิต", group: "การผลิต" },
  { code: "purchasing.view", label: "ดูการจัดซื้อ", group: "จัดซื้อ" },
  { code: "purchasing.manage", label: "จัดการการจัดซื้อ", group: "จัดซื้อ" },
  { code: "supplier.view", label: "ดูผู้จำหน่าย", group: "จัดซื้อ" },
  { code: "supplier.manage", label: "จัดการผู้จำหน่าย", group: "จัดซื้อ" },
] as const;

export type PermissionCode = (typeof permissionRegistry)[number]["code"];
export const permissionCodes = permissionRegistry.map(({ code }) => code) as PermissionCode[];
const permissionCodeSet = new Set<string>(permissionCodes);
export function isPermissionCode(value: string): value is PermissionCode { return permissionCodeSet.has(value); }
