import type { PermissionCode } from "@/config/permissions";
import type { ReportColumn } from "@/features/reports/types";
import type { ReportKey } from "@/services/reporting.service";

export type ReportFilterKey = "period" | "search" | "customer" | "customerType" | "paymentType" | "status" | "salesperson" | "product" | "category" | "warehouse" | "tripStatus" | "driver" | "vehicle" | "result" | "method" | "dueDate" | "asOfDate";
type Definition = { title: string; description: string; dateLabel?: string; permission: PermissionCode; filters: ReportFilterKey[]; columns: ReportColumn[] };

export const reportDefinitions: Record<ReportKey, Definition> = {
  sales: { title: "รายงานยอดขาย", description: "ยอดขายตามคำสั่งซื้อที่ยืนยันแล้ว อ้างอิงวันที่สั่งซื้อ", dateLabel: "วันที่สั่งซื้อ", permission: "sales_order.view", filters: ["period", "search", "customer", "customerType", "paymentType", "status", "salesperson"], columns: [{ key: "orderNo", label: "เลขที่คำสั่งซื้อ", linkPrefix: "/sales/orders/", sortKey: "orderNo" }, { key: "orderDate", label: "วันที่สั่งซื้อ", format: "date", sortKey: "date" }, { key: "customer", label: "ลูกค้า", sortKey: "customer" }, { key: "customerType", label: "ประเภทลูกค้า" }, { key: "paymentType", label: "การขาย" }, { key: "subtotal", label: "ยอดก่อนส่วนลด", format: "money", align: "right" }, { key: "discount", label: "ส่วนลด", format: "money", align: "right" }, { key: "tax", label: "ภาษี", format: "money", align: "right" }, { key: "total", label: "ยอดรวม", format: "money", align: "right", sortKey: "total" }, { key: "status", label: "สถานะ", sortKey: "status" }, { key: "salesperson", label: "ผู้บันทึก" }] },
  products: { title: "รายงานยอดขายสินค้า", description: "จัดอันดับตามมูลค่ารายการคำสั่งซื้อ โดยแยกหน่วยขายเพื่อไม่รวมจำนวนต่างหน่วย", dateLabel: "วันที่สั่งซื้อ", permission: "sales_order.view", filters: ["period", "search", "product", "category", "customerType"], columns: [{ key: "sku", label: "SKU" }, { key: "product", label: "สินค้า", sortKey: "product" }, { key: "unit", label: "หน่วย" }, { key: "quantity", label: "จำนวนขาย", format: "quantity", align: "right", sortKey: "quantity" }, { key: "salesValue", label: "มูลค่าขาย", format: "money", align: "right", sortKey: "value" }, { key: "averagePrice", label: "ราคาเฉลี่ย", format: "money", align: "right" }] },
  customers: { title: "รายงานยอดขายลูกค้า", description: "สรุปมูลค่าคำสั่งซื้อที่ยืนยันแล้วแยกตามลูกค้า", dateLabel: "วันที่สั่งซื้อ", permission: "sales_order.view", filters: ["period", "search", "customer", "customerType", "paymentType"], columns: [{ key: "code", label: "รหัสลูกค้า" }, { key: "customer", label: "ลูกค้า", sortKey: "customer" }, { key: "type", label: "ประเภท" }, { key: "orders", label: "คำสั่งซื้อ", align: "right", sortKey: "orders" }, { key: "salesValue", label: "มูลค่าขาย", format: "money", align: "right", sortKey: "value" }, { key: "averageOrder", label: "เฉลี่ยต่อคำสั่งซื้อ", format: "money", align: "right" }] },
  delivery: { title: "รายงานการจัดส่ง", description: "ผลการจัดส่งตามเวลาบันทึกผลสำเร็จหรือไม่สำเร็จ", dateLabel: "วันที่บันทึกผลจัดส่ง", permission: "delivery.view", filters: ["period", "search", "tripStatus", "driver", "vehicle", "result"], columns: [{ key: "tripNo", label: "รอบจัดส่ง" }, { key: "plannedDate", label: "วันที่วางแผน", format: "date" }, { key: "resultDate", label: "เวลาบันทึกผล", format: "datetime" }, { key: "driver", label: "พนักงานขับรถ" }, { key: "vehicle", label: "รถ" }, { key: "orderNo", label: "คำสั่งซื้อ" }, { key: "customer", label: "ลูกค้า" }, { key: "result", label: "ผลจัดส่ง" }] },
  "inventory-stock": { title: "รายงานสต็อกคงเหลือ", description: "ยอดคงเหลือปัจจุบันจาก StockBalance ซึ่งเป็น projection ของบัญชีสต็อก", permission: "inventory.view", filters: ["search", "warehouse", "category", "status"], columns: [{ key: "sku", label: "SKU", sortKey: "sku" }, { key: "product", label: "สินค้า", sortKey: "name" }, { key: "category", label: "หมวดหมู่" }, { key: "warehouse", label: "คลัง", sortKey: "warehouse" }, { key: "unit", label: "หน่วย" }, { key: "quantity", label: "คงเหลือ", format: "quantity", align: "right", sortKey: "quantity" }, { key: "minimumStock", label: "สต็อกขั้นต่ำ", format: "quantity", align: "right" }, { key: "status", label: "สถานะ" }] },
  "inventory-movements": { title: "รายงานการเคลื่อนไหวสต็อก", description: "รายการบัญชีสต็อกตามเวลาธุรกรรมจาก InventoryLedgerEntry", dateLabel: "เวลาธุรกรรม", permission: "inventory.view", filters: ["period", "search", "warehouse", "product", "status"], columns: [{ key: "movementNo", label: "เลขที่รายการ", sortKey: "movementNo" }, { key: "occurredAt", label: "วันที่/เวลา", format: "datetime", sortKey: "date" }, { key: "product", label: "สินค้า", sortKey: "product" }, { key: "warehouse", label: "คลัง", sortKey: "warehouse" }, { key: "type", label: "ประเภท" }, { key: "quantity", label: "จำนวน", format: "quantity", align: "right", sortKey: "quantity" }, { key: "unit", label: "หน่วย" }, { key: "reference", label: "อ้างอิง" }, { key: "user", label: "ผู้บันทึก" }] },
  invoices: { title: "รายงานใบแจ้งหนี้", description: "ใบแจ้งหนี้ตามวันที่เอกสาร พร้อมยอดชำระและคงค้างจาก PaymentAllocation ที่มีผล", dateLabel: "วันที่ใบแจ้งหนี้", permission: "invoice.view", filters: ["period", "search", "customer", "status", "dueDate"], columns: [{ key: "invoiceNo", label: "เลขที่ใบแจ้งหนี้", linkPrefix: "/accounting/invoices/" }, { key: "invoiceDate", label: "วันที่ใบแจ้งหนี้", format: "date" }, { key: "customer", label: "ลูกค้า" }, { key: "dueDate", label: "ครบกำหนด", format: "date" }, { key: "originalAmount", label: "ยอดเดิม", format: "money", align: "right" }, { key: "paid", label: "ชำระแล้ว", format: "money", align: "right" }, { key: "outstanding", label: "คงค้าง", format: "money", align: "right" }, { key: "status", label: "สถานะ" }] },
  payments: { title: "รายงานการรับชำระเงิน", description: "รายการรับชำระตามวันที่รับเงิน แยกจากยอดขายและยอดใบแจ้งหนี้", dateLabel: "วันที่รับชำระ", permission: "payment.view", filters: ["period", "search", "customer", "method", "status"], columns: [{ key: "paymentNo", label: "เลขที่รับชำระ", linkPrefix: "/accounting/payments/" }, { key: "paymentDate", label: "วันที่รับชำระ", format: "date" }, { key: "customer", label: "ลูกค้า" }, { key: "method", label: "วิธีชำระ" }, { key: "amount", label: "ยอดรับชำระ", format: "money", align: "right" }, { key: "allocated", label: "จัดสรรแล้ว", format: "money", align: "right" }, { key: "unapplied", label: "ยังไม่จัดสรร", format: "money", align: "right" }, { key: "status", label: "สถานะ" }] },
  "ar-aging": { title: "รายงานอายุลูกหนี้", description: "ลูกหนี้ ณ วันที่กำหนดจากใบแจ้งหนี้ หัก PaymentAllocation ของรายการรับชำระที่มีผล", permission: "ar.view", filters: ["search", "customer", "asOfDate"], columns: [{ key: "code", label: "รหัสลูกค้า" }, { key: "customer", label: "ลูกค้า", hrefKey: "invoiceHref" }, { key: "current", label: "ยังไม่ครบกำหนด", format: "money", align: "right" }, { key: "days1to30", label: "1–30", format: "money", align: "right" }, { key: "days31to60", label: "31–60", format: "money", align: "right" }, { key: "days61to90", label: "61–90", format: "money", align: "right" }, { key: "days90plus", label: "90+", format: "money", align: "right" }, { key: "total", label: "คงค้างรวม", format: "money", align: "right" }] },
};

export const reportCatalog = [
  { key: "sales", group: "ยอดขาย", detail: "รายละเอียดและยอดรวมคำสั่งซื้อ" }, { key: "products", group: "ยอดขาย", detail: "ยอดขายแยกตามสินค้าและหน่วย" }, { key: "customers", group: "ยอดขาย", detail: "ยอดขายและมูลค่าเฉลี่ยตามลูกค้า" }, { key: "delivery", group: "ปฏิบัติการ", detail: "ผลสำเร็จและไม่สำเร็จของการจัดส่ง" }, { key: "inventory-stock", group: "สินค้าคงคลัง", detail: "ยอดคงเหลือปัจจุบันแยกคลัง" }, { key: "inventory-movements", group: "สินค้าคงคลัง", detail: "บัญชีการเคลื่อนไหวสต็อก" }, { key: "invoices", group: "การเงิน", detail: "ใบแจ้งหนี้ ยอดชำระ และคงค้าง" }, { key: "payments", group: "การเงิน", detail: "รายการรับชำระและการจัดสรร" }, { key: "ar-aging", group: "การเงิน", detail: "อายุลูกหนี้แยกตามลูกค้า" },
] as const;
