import "server-only";
import { Prisma } from "@/generated/prisma/client";
import { db } from "@/lib/db";
import type { DeliveryTripListQuery } from "@/validations/delivery";

export type DeliveryTransaction = Prisma.TransactionClient;

const activeDeliveryStatuses = ["PENDING", "LOADED", "IN_TRANSIT"] as const;
const tripListSelect = { id: true, tripNo: true, plannedDate: true, status: true, driverName: true, vehiclePlate: true, updatedAt: true, warehouse: { select: { name: true } }, stops: { select: { deliveries: { select: { salesOrder: { select: { orderNo: true, customerNameSnapshot: true } } } } } }, _count: { select: { stops: true } } } satisfies Prisma.DeliveryTripSelect;

function tripWhere(query: DeliveryTripListQuery): Prisma.DeliveryTripWhereInput {
  return { ...(query.q ? { OR: [{ tripNo: { contains: query.q, mode: "insensitive" } }, { vehiclePlate: { contains: query.q, mode: "insensitive" } }, { driverName: { contains: query.q, mode: "insensitive" } }, { stops: { some: { deliveries: { some: { OR: [{ salesOrder: { orderNo: { contains: query.q, mode: "insensitive" } } }, { salesOrder: { customerNameSnapshot: { contains: query.q, mode: "insensitive" } } }] } } } } }] } : {}), ...(query.status === "ALL" ? {} : { status: query.status }), ...(query.driverId === "ALL" ? {} : { driverId: query.driverId }), ...(query.vehicleId === "ALL" ? {} : { vehicleId: query.vehicleId }), ...((query.dateFrom || query.dateTo) ? { plannedDate: { ...(query.dateFrom ? { gte: new Date(`${query.dateFrom}T00:00:00.000Z`) } : {}), ...(query.dateTo ? { lte: new Date(`${query.dateTo}T00:00:00.000Z`) } : {}) } } : {}) };
}

export async function findDeliveryTrips(query: DeliveryTripListQuery) {
  const where = tripWhere(query); const orderBy: Prisma.DeliveryTripOrderByWithRelationInput = query.sort === "vehicle" ? { vehiclePlate: query.order } : query.sort === "driver" ? { driverName: query.order } : { [query.sort]: query.order };
  const [rows, total] = await db.$transaction([db.deliveryTrip.findMany({ where, select: tripListSelect, orderBy: [orderBy, { id: "asc" }], skip: (query.page - 1) * query.pageSize, take: query.pageSize }), db.deliveryTrip.count({ where })]); return { rows, total };
}

export async function getDeliveryDashboardCounts(dateToday: Date, dateTomorrow: Date, timestampToday: Date, timestampTomorrow: Date) {
  const [waitingOrders, plannedToday, inProgress, deliveredToday, failedPending] = await db.$transaction([
    db.salesOrder.count({ where: { status: { in: ["CONFIRMED", "READY"] }, shippingAddress: { not: Prisma.JsonNull }, deliveries: { none: { status: { in: [...activeDeliveryStatuses] } } } } }),
    db.deliveryTrip.count({ where: { plannedDate: { gte: dateToday, lt: dateTomorrow }, status: { in: ["PLANNED", "LOADING"] } } }),
    db.deliveryTrip.count({ where: { status: "IN_TRANSIT" } }),
    db.delivery.count({ where: { status: "DELIVERED", deliveredAt: { gte: timestampToday, lt: timestampTomorrow } } }),
    db.delivery.count({ where: { status: "FAILED", returnedAt: null } }),
  ]); return { waitingOrders, plannedToday, inProgress, deliveredToday, failedPending };
}

export function listActiveDeliveryWarehouses() { return db.warehouse.findMany({ where: { status: "ACTIVE", type: "STORAGE" }, select: { id: true, code: true, name: true, isDefault: true }, orderBy: [{ isDefault: "desc" }, { name: "asc" }] }); }
export function listActiveVehicles() { return db.vehicle.findMany({ where: { status: "ACTIVE", warehouse: { status: "ACTIVE" } }, select: { id: true, code: true, registrationNumber: true, description: true, warehouseId: true, warehouse: { select: { name: true } } }, orderBy: [{ code: "asc" }] }); }
export function listDeliveryDrivers() { return db.user.findMany({ where: { status: "ACTIVE", roles: { some: { role: { isActive: true, permissions: { some: { permission: { code: "delivery.manage" } } } } } } }, select: { id: true, name: true, email: true }, orderBy: { name: "asc" } }); }
export function listEligibleDeliveryOrders() { return db.salesOrder.findMany({ where: { status: { in: ["CONFIRMED", "READY"] }, shippingAddress: { not: Prisma.JsonNull }, deliveries: { none: { status: { in: [...activeDeliveryStatuses] } } } }, select: { id: true, orderNo: true, requestedDeliveryDate: true, customerNameSnapshot: true, customerCodeSnapshot: true, shippingAddress: true, saleType: true, totalAmount: true, status: true, warehouseId: true }, orderBy: [{ requestedDeliveryDate: { sort: "asc", nulls: "last" } }, { orderNo: "asc" }], take: 200 }); }

export function findDeliveryTripById(id: string) { return db.deliveryTrip.findUnique({ where: { id }, include: { warehouse: { select: { id: true, code: true, name: true } }, vehicle: { include: { warehouse: { select: { id: true, code: true, name: true } } } }, driver: { select: { id: true, name: true, email: true, status: true } }, createdBy: { select: { name: true } }, stops: { include: { deliveries: { include: { salesOrder: { select: { id: true, orderNo: true, status: true, customerCodeSnapshot: true, customerNameSnapshot: true, saleType: true, totalAmount: true, shippingAddress: true }, }, items: { include: { salesOrderItem: { select: { id: true, productId: true, productUnitId: true, productNameSnapshot: true, skuSnapshot: true, unitNameSnapshot: true, quantity: true, baseQuantity: true } } } } } } }, orderBy: { sequence: "asc" } } } }); }
export function findDeliveryTripForUpdate(id: string, tx: DeliveryTransaction) { return tx.deliveryTrip.findUnique({ where: { id }, include: { warehouse: true, vehicle: { include: { warehouse: true } }, driver: true, stops: { include: { deliveries: { include: { salesOrder: { include: { items: { include: { product: { select: { units: { where: { isBase: true, isActive: true }, select: { id: true }, take: 1 } } } } } } }, items: { include: { salesOrderItem: { include: { product: { select: { units: { where: { isBase: true, isActive: true }, select: { id: true }, take: 1 } } } } } } } } } }, orderBy: { sequence: "asc" } } } }); }
export function findDeliveryForUpdate(id: string, tx: DeliveryTransaction) { return tx.delivery.findUnique({ where: { id }, include: { deliveryStop: { include: { deliveryTrip: { include: { warehouse: true, vehicle: { include: { warehouse: true } } } } } }, salesOrder: { include: { items: true } }, items: { include: { salesOrderItem: { include: { product: { select: { units: { where: { isBase: true, isActive: true }, select: { id: true }, take: 1 } } } } } } } } }); }
export function findAssignableOrder(id: string, tx: DeliveryTransaction) { return tx.salesOrder.findUnique({ where: { id }, include: { customer: { select: { id: true } }, items: { include: { product: { select: { units: { where: { isBase: true, isActive: true }, select: { id: true }, take: 1 } } } } }, deliveries: { where: { status: { in: [...activeDeliveryStatuses] } }, select: { id: true } } } }); }
export function findActiveVehicle(id: string, tx: DeliveryTransaction) { return tx.vehicle.findFirst({ where: { id, status: "ACTIVE", warehouse: { status: "ACTIVE" } }, include: { warehouse: true } }); }
export function findActiveDriver(id: string, tx: DeliveryTransaction) { return tx.user.findFirst({ where: { id, status: "ACTIVE", roles: { some: { role: { isActive: true, permissions: { some: { permission: { code: "delivery.manage" } } } } } } }, select: { id: true, name: true } }); }
export function findActiveStorageWarehouse(id: string, tx: DeliveryTransaction) { return tx.warehouse.findFirst({ where: { id, status: "ACTIVE", type: "STORAGE" }, select: { id: true, name: true } }); }

export async function nextDeliveryTripNumber(tx: DeliveryTransaction, yearMonth: string) { const sequence = await tx.documentSequence.upsert({ where: { key: `DL-${yearMonth}` }, create: { key: `DL-${yearMonth}`, currentValue: 1 }, update: { currentValue: { increment: 1 } }, select: { currentValue: true } }); return `DL-${yearMonth}-${String(sequence.currentValue).padStart(5, "0")}`; }
export function createDeliveryTripRecord(tx: DeliveryTransaction, data: Prisma.DeliveryTripUncheckedCreateInput) { return tx.deliveryTrip.create({ data, select: { id: true, tripNo: true } }); }
export function updateDeliveryTripRecord(tx: DeliveryTransaction, id: string, data: Prisma.DeliveryTripUncheckedUpdateInput) { return tx.deliveryTrip.update({ where: { id }, data, select: { id: true } }); }
export function createDeliveryStopRecord(tx: DeliveryTransaction, data: Prisma.DeliveryStopUncheckedCreateInput) { return tx.deliveryStop.create({ data, select: { id: true, sequence: true } }); }
export function createDeliveryRecord(tx: DeliveryTransaction, data: Prisma.DeliveryUncheckedCreateInput) { return tx.delivery.create({ data, select: { id: true } }); }
export function createDeliveryItems(tx: DeliveryTransaction, data: Prisma.DeliveryItemCreateManyInput[]) { return tx.deliveryItem.createMany({ data }); }
export function updateDeliveryRecord(tx: DeliveryTransaction, id: string, data: Prisma.DeliveryUncheckedUpdateInput) { return tx.delivery.update({ where: { id }, data }); }
export function updateDeliveryStopRecord(tx: DeliveryTransaction, id: string, data: Prisma.DeliveryStopUncheckedUpdateInput) { return tx.deliveryStop.update({ where: { id }, data }); }
export async function completeDeliveryItems(tx: DeliveryTransaction, items: Array<{ id: string; salesOrderItemId: string; plannedQuantity: Prisma.Decimal; plannedBaseQuantity: Prisma.Decimal }>) { for (const item of items) { await tx.deliveryItem.update({ where: { id: item.id }, data: { deliveredQuantity: item.plannedQuantity, deliveredBaseQuantity: item.plannedBaseQuantity } }); await tx.salesOrderItem.update({ where: { id: item.salesOrderItemId }, data: { fulfilledQuantity: item.plannedQuantity } }); } }
export function updateSalesOrderDeliveryStatus(tx: DeliveryTransaction, id: string, data: Prisma.SalesOrderUncheckedUpdateInput) { return tx.salesOrder.update({ where: { id }, data, select: { id: true } }); }
export function createDeliveryOrderHistory(tx: DeliveryTransaction, data: Prisma.SalesOrderStatusHistoryUncheckedCreateInput) { return tx.salesOrderStatusHistory.create({ data }); }
export function createDeliveryAuditLog(tx: DeliveryTransaction, data: Prisma.AuditLogUncheckedCreateInput) { return tx.auditLog.create({ data }); }
export function listDeliveryAuditLogs(id: string) { return db.auditLog.findMany({ where: { entityType: "DeliveryTrip", entityId: id }, select: { id: true, action: true, actorName: true, afterData: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 100 }); }
export async function removeDeliveryAssignment(tx: DeliveryTransaction, deliveryId: string, stopId: string) { await tx.deliveryItem.deleteMany({ where: { deliveryId } }); await tx.delivery.delete({ where: { id: deliveryId } }); await tx.deliveryStop.delete({ where: { id: stopId } }); }
export async function resequenceDeliveryStops(tx: DeliveryTransaction, tripId: string, stopIds: string[]) { await tx.deliveryStop.updateMany({ where: { deliveryTripId: tripId }, data: { sequence: { increment: 10000 } } }); for (const [index, id] of stopIds.entries()) await tx.deliveryStop.update({ where: { id, deliveryTripId: tripId }, data: { sequence: index + 1 } }); }

export function listVehicles() { return db.vehicle.findMany({ include: { warehouse: { select: { id: true, code: true, name: true, status: true, stockBalances: { select: { onHandQuantity: true } } } }, _count: { select: { deliveryTrips: true } } }, orderBy: { code: "asc" } }); }
export function findVehicleById(id: string, tx: DeliveryTransaction) { return tx.vehicle.findUnique({ where: { id }, include: { warehouse: { include: { stockBalances: { select: { onHandQuantity: true } } } }, _count: { select: { deliveryTrips: true } } } }); }
export async function createVehicleWithWarehouse(tx: DeliveryTransaction, data: { code: string; registrationNumber: string; description: string | null }) { const warehouse = await tx.warehouse.create({ data: { code: `VEH-${data.code}`, name: `คลังรถ ${data.registrationNumber}`, type: "VEHICLE", status: "ACTIVE", isDefault: false } }); return tx.vehicle.create({ data: { ...data, warehouseId: warehouse.id }, select: { id: true } }); }
export async function updateVehicleRecord(tx: DeliveryTransaction, id: string, data: { code: string; registrationNumber: string; description: string | null }) { const vehicle = await tx.vehicle.update({ where: { id }, data, select: { id: true, warehouseId: true } }); await tx.warehouse.update({ where: { id: vehicle.warehouseId }, data: { code: `VEH-${data.code}`, name: `คลังรถ ${data.registrationNumber}` } }); return vehicle; }
export async function updateVehicleStatus(tx: DeliveryTransaction, id: string, status: "ACTIVE" | "INACTIVE") { const vehicle = await tx.vehicle.update({ where: { id }, data: { status }, select: { id: true, warehouseId: true } }); await tx.warehouse.update({ where: { id: vehicle.warehouseId }, data: { status } }); return vehicle; }
export function withDeliveryTransaction<T>(operation: (tx: DeliveryTransaction) => Promise<T>) { return db.$transaction(operation, { isolationLevel: "Serializable" }); }
