import "server-only";

import type { Prisma } from "@/generated/prisma/client";
import { db } from "@/lib/db";
import { businessDateKey, dateOnly, dateOnlyRange, bangkokTimestampRange, isReportableSalesStatus, REPORTABLE_SALES_STATUSES } from "@/services/reporting-core";
import type { ReportQuery } from "@/validations/reporting";

const activeInvoiceStatuses = ["ISSUED", "PARTIALLY_PAID", "OVERDUE"] as const;
const completedPayment = { payment: { status: "COMPLETED" as const } };

export function salesWhere(query: ReportQuery, dateFrom: string, dateTo: string): Prisma.SalesOrderWhereInput { return { status: query.status !== "ALL" && isReportableSalesStatus(query.status) ? query.status : { in: [...REPORTABLE_SALES_STATUSES] }, orderDate: dateOnlyRange(dateFrom, dateTo), ...(query.customerId !== "ALL" ? { customerId: query.customerId } : {}), ...(query.customerType !== "ALL" ? { customer: { type: query.customerType as "RETAIL" | "WHOLESALE" } } : {}), ...(query.paymentType !== "ALL" ? { saleType: query.paymentType as "CASH" | "CREDIT" } : {}), ...(query.salespersonId !== "ALL" ? { createdById: query.salespersonId } : {}), ...(query.q ? { OR: [{ orderNo: { contains: query.q, mode: "insensitive" } }, { customerCodeSnapshot: { contains: query.q, mode: "insensitive" } }, { customerNameSnapshot: { contains: query.q, mode: "insensitive" } }] } : {}) }; }

export async function listSales(query: ReportQuery, dateFrom: string, dateTo: string, take = query.pageSize, skip = (query.page - 1) * query.pageSize) { const where = salesWhere(query, dateFrom, dateTo); const sortMap: Record<string, Prisma.SalesOrderOrderByWithRelationInput> = { orderNo: { orderNo: query.order }, date: { orderDate: query.order }, customer: { customerNameSnapshot: query.order }, total: { totalAmount: query.order }, status: { status: query.order } }; const [rows, total, aggregate] = await db.$transaction([db.salesOrder.findMany({ where, select: { id: true, orderNo: true, orderDate: true, customerCodeSnapshot: true, customerNameSnapshot: true, customer: { select: { type: true } }, saleType: true, subtotal: true, discountAmount: true, taxAmount: true, totalAmount: true, status: true, createdBy: { select: { name: true } } }, orderBy: [sortMap[query.sort] ?? sortMap.date!, { orderNo: "desc" }], skip, take }), db.salesOrder.count({ where }), db.salesOrder.aggregate({ where, _count: true, _sum: { subtotal: true, discountAmount: true, taxAmount: true, totalAmount: true } })]); return { rows, total, aggregate }; }

export async function listProductSales(query: ReportQuery, dateFrom: string, dateTo: string, take = query.pageSize, skip = (query.page - 1) * query.pageSize) {
  const where: Prisma.SalesOrderItemWhereInput = { salesOrder: salesWhere(query, dateFrom, dateTo), ...(query.productId !== "ALL" ? { productId: query.productId } : {}), ...(query.categoryId !== "ALL" ? { product: { categoryId: query.categoryId } } : {}), ...(query.q ? { OR: [{ skuSnapshot: { contains: query.q, mode: "insensitive" } }, { productNameSnapshot: { contains: query.q, mode: "insensitive" } }] } : {}) };
  const by = ["productId", "productUnitId", "skuSnapshot", "productNameSnapshot", "unitNameSnapshot"] as const;
  const rowsPromise = query.sort === "quantity" ? db.salesOrderItem.groupBy({ by: [...by], where, _sum: { quantity: true, lineTotal: true }, _count: true, orderBy: { _sum: { quantity: query.order } }, skip, take }) : query.sort === "product" ? db.salesOrderItem.groupBy({ by: [...by], where, _sum: { quantity: true, lineTotal: true }, _count: true, orderBy: { productNameSnapshot: query.order }, skip, take }) : db.salesOrderItem.groupBy({ by: [...by], where, _sum: { quantity: true, lineTotal: true }, _count: true, orderBy: { _sum: { lineTotal: query.order } }, skip, take });
  const [rows, groups, aggregate] = await Promise.all([rowsPromise, db.salesOrderItem.groupBy({ by: [...by], where }), db.salesOrderItem.aggregate({ where, _sum: { lineTotal: true }, _count: true })]); return { rows, total: groups.length, aggregate };
}

export async function listCustomerSales(query: ReportQuery, dateFrom: string, dateTo: string, take = query.pageSize, skip = (query.page - 1) * query.pageSize) {
  const where = salesWhere(query, dateFrom, dateTo); const by = ["customerId", "customerCodeSnapshot", "customerNameSnapshot"] as const;
  const rowsPromise = query.sort === "orders" ? db.salesOrder.groupBy({ by: [...by], where, _sum: { totalAmount: true }, _count: { id: true }, orderBy: { _count: { id: query.order } }, skip, take }) : query.sort === "customer" ? db.salesOrder.groupBy({ by: [...by], where, _sum: { totalAmount: true }, _count: { id: true }, orderBy: { customerNameSnapshot: query.order }, skip, take }) : db.salesOrder.groupBy({ by: [...by], where, _sum: { totalAmount: true }, _count: { id: true }, orderBy: { _sum: { totalAmount: query.order } }, skip, take });
  const [rows, groups, aggregate] = await Promise.all([rowsPromise, db.salesOrder.groupBy({ by: [...by], where }), db.salesOrder.aggregate({ where, _sum: { totalAmount: true }, _count: true })]); const customerTypes = await db.customer.findMany({ where: { id: { in: rows.map((row) => row.customerId) } }, select: { id: true, type: true } }); return { rows, total: groups.length, aggregate, customerTypes };
}

function deliveryWhere(query: ReportQuery, dateFrom: string, dateTo: string): Prisma.DeliveryWhereInput { const range = bangkokTimestampRange(dateFrom, dateTo); const trip: Prisma.DeliveryTripWhereInput = { ...(query.tripStatus !== "ALL" ? { status: query.tripStatus as Prisma.EnumDeliveryTripStatusFilter["equals"] } : {}), ...(query.driverId !== "ALL" ? { driverId: query.driverId } : {}), ...(query.vehicleId !== "ALL" ? { vehicleId: query.vehicleId } : {}) }; const and: Prisma.DeliveryWhereInput[] = [{ OR: [{ deliveredAt: range }, { deliveryStop: { completedAt: range } }] }]; if (Object.keys(trip).length) and.push({ deliveryStop: { deliveryTrip: trip } }); if (query.q) and.push({ OR: [{ deliveryNo: { contains: query.q, mode: "insensitive" } }, { salesOrder: { orderNo: { contains: query.q, mode: "insensitive" } } }, { salesOrder: { customerNameSnapshot: { contains: query.q, mode: "insensitive" } } }] }); return { status: query.result !== "ALL" ? query.result as "DELIVERED" | "FAILED" : { in: ["DELIVERED", "FAILED"] }, AND: and }; }

export async function listDeliveries(query: ReportQuery, dateFrom: string, dateTo: string, take = query.pageSize, skip = (query.page - 1) * query.pageSize) { const where = deliveryWhere(query, dateFrom, dateTo); const [rows, total, delivered, failed, tripGroups] = await Promise.all([db.delivery.findMany({ where, include: { salesOrder: { select: { id: true, orderNo: true, customerCodeSnapshot: true, customerNameSnapshot: true } }, deliveryStop: { select: { completedAt: true, deliveryTrip: { select: { id: true, tripNo: true, plannedDate: true, driverName: true, vehiclePlate: true, status: true } } } } }, orderBy: [{ deliveredAt: query.order }, { deliveryNo: "desc" }], skip, take }), db.delivery.count({ where }), db.delivery.count({ where: { ...where, status: "DELIVERED" } }), db.delivery.count({ where: { ...where, status: "FAILED" } }), db.delivery.findMany({ where, distinct: ["deliveryStopId"], select: { deliveryStop: { select: { deliveryTripId: true } } } })]); return { rows, total, delivered, failed, trips: new Set(tripGroups.map((row) => row.deliveryStop.deliveryTripId)).size }; }

function invoiceWhere(query: ReportQuery, dateFrom: string, dateTo: string): Prisma.InvoiceWhereInput { const asOf = dateOnly(businessDateKey()); const status = query.status === "OVERDUE" ? { status: { in: [...activeInvoiceStatuses] }, dueDate: { lt: asOf } } : query.status !== "ALL" ? { status: query.status as Prisma.EnumInvoiceStatusFilter["equals"] } : {}; return { invoiceDate: dateOnlyRange(dateFrom, dateTo), ...(query.dueFrom || query.dueTo ? { dueDate: { ...(query.dueFrom ? { gte: dateOnly(query.dueFrom) } : {}), ...(query.dueTo ? { lte: dateOnly(query.dueTo) } : {}) } } : {}), ...(query.customerId !== "ALL" ? { customerId: query.customerId } : {}), ...(query.q ? { OR: [{ invoiceNo: { contains: query.q, mode: "insensitive" } }, { customerCodeSnapshot: { contains: query.q, mode: "insensitive" } }, { customerNameSnapshot: { contains: query.q, mode: "insensitive" } }] } : {}), ...status }; }

export async function listInvoices(query: ReportQuery, dateFrom: string, dateTo: string, take = query.pageSize, skip = (query.page - 1) * query.pageSize) { const where = invoiceWhere(query, dateFrom, dateTo); const [rows, total, aggregate, paid] = await Promise.all([db.invoice.findMany({ where, include: { paymentAllocations: { where: completedPayment, select: { amount: true } } }, orderBy: [{ invoiceDate: query.order }, { invoiceNo: "desc" }], skip, take }), db.invoice.count({ where }), db.invoice.aggregate({ where, _sum: { totalAmount: true }, _count: true }), db.paymentAllocation.aggregate({ where: { invoice: where, payment: { status: "COMPLETED" } }, _sum: { amount: true } })]); return { rows, total, aggregate, paid }; }

function paymentWhere(query: ReportQuery, dateFrom: string, dateTo: string): Prisma.PaymentWhereInput { return { paymentDate: dateOnlyRange(dateFrom, dateTo), ...(query.status !== "ALL" ? { status: query.status as Prisma.EnumPaymentStatusFilter["equals"] } : {}), ...(query.customerId !== "ALL" ? { customerId: query.customerId } : {}), ...(query.method !== "ALL" ? { method: query.method as Prisma.EnumPaymentMethodFilter["equals"] } : {}), ...(query.q ? { OR: [{ paymentNo: { contains: query.q, mode: "insensitive" } }, { customer: { code: { contains: query.q, mode: "insensitive" } } }, { customer: { displayName: { contains: query.q, mode: "insensitive" } } }] } : {}) }; }

export async function listPayments(query: ReportQuery, dateFrom: string, dateTo: string, take = query.pageSize, skip = (query.page - 1) * query.pageSize) { const where = paymentWhere(query, dateFrom, dateTo); const validWhere: Prisma.PaymentWhereInput = { ...where, status: "COMPLETED" }; const [rows, total, aggregate, allocated] = await Promise.all([db.payment.findMany({ where, include: { customer: { select: { code: true, displayName: true } }, allocations: { select: { amount: true } } }, orderBy: [{ paymentDate: query.order }, { paymentNo: "desc" }], skip, take }), db.payment.count({ where }), db.payment.aggregate({ where: validWhere, _sum: { amount: true }, _count: true }), db.paymentAllocation.aggregate({ where: { payment: validWhere }, _sum: { amount: true } })]); return { rows, total, aggregate, allocated }; }

export async function getReportOptions() { const [customers, products, categories, warehouses, users, drivers, vehicles] = await Promise.all([db.customer.findMany({ where: { deletedAt: null }, select: { id: true, code: true, displayName: true }, orderBy: { code: "asc" } }), db.product.findMany({ where: { deletedAt: null }, select: { id: true, sku: true, name: true }, orderBy: { sku: "asc" } }), db.productCategory.findMany({ where: { isActive: true }, select: { id: true, name: true }, orderBy: { name: "asc" } }), db.warehouse.findMany({ select: { id: true, code: true, name: true }, orderBy: { code: "asc" } }), db.user.findMany({ where: { status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }), db.user.findMany({ where: { status: "ACTIVE", assignedDeliveryTrips: { some: {} } }, select: { id: true, name: true }, orderBy: { name: "asc" } }), db.vehicle.findMany({ select: { id: true, registrationNumber: true }, orderBy: { registrationNumber: "asc" } })]); return { customers: customers.map((item) => ({ id: item.id, label: `${item.code} · ${item.displayName}` })), products: products.map((item) => ({ id: item.id, label: `${item.sku} · ${item.name}` })), categories: categories.map((item) => ({ id: item.id, label: item.name })), warehouses: warehouses.map((item) => ({ id: item.id, label: `${item.code} · ${item.name}` })), users: users.map((item) => ({ id: item.id, label: item.name })), drivers: drivers.map((item) => ({ id: item.id, label: item.name })), vehicles: vehicles.map((item) => ({ id: item.id, label: item.registrationNumber })) }; }

export async function getDashboardSales(dateFrom: string, dateTo: string) { const where = salesWhere({ status: "ALL", customerId: "ALL", customerType: "ALL", paymentType: "ALL", salespersonId: "ALL", productId: "ALL", categoryId: "ALL", warehouseId: "ALL", tripStatus: "ALL", driverId: "ALL", vehicleId: "ALL", result: "ALL", method: "ALL", q: "", period: "custom", dateFrom, dateTo, dueFrom: "", dueTo: "", asOfDate: "", sort: "date", order: "desc", page: 1, pageSize: 20 }, dateFrom, dateTo); const [totals, byPayment, byStatus, byDate, topCustomers, topProducts] = await Promise.all([db.salesOrder.aggregate({ where, _count: true, _sum: { totalAmount: true } }), db.salesOrder.groupBy({ by: ["saleType"], where, _sum: { totalAmount: true } }), db.salesOrder.groupBy({ by: ["status"], where: { orderDate: dateOnlyRange(dateFrom, dateTo) }, _count: true }), db.salesOrder.groupBy({ by: ["orderDate"], where, _sum: { totalAmount: true }, orderBy: { orderDate: "asc" } }), db.salesOrder.groupBy({ by: ["customerId", "customerNameSnapshot"], where, _sum: { totalAmount: true }, orderBy: { _sum: { totalAmount: "desc" } }, take: 5 }), db.salesOrderItem.groupBy({ by: ["productId", "productNameSnapshot", "skuSnapshot"], where: { salesOrder: where }, _sum: { lineTotal: true }, orderBy: { _sum: { lineTotal: "desc" } }, take: 5 })]); const retailWholesale = await db.salesOrder.groupBy({ by: ["customerId"], where, _sum: { totalAmount: true } }); const customerTypes = await db.customer.findMany({ where: { id: { in: retailWholesale.map((row) => row.customerId) } }, select: { id: true, type: true } }); return { totals, byPayment, byStatus, byDate, topCustomers, topProducts, retailWholesale, customerTypes }; }

export async function getDashboardInventory() { const rows = await db.$queryRaw<Array<{ low: number; out: number }>>`SELECT COUNT(*) FILTER (WHERE balance."onHandQuantity" > 0 AND balance."onHandQuantity" <= product."reorderLevel")::integer AS low, COUNT(*) FILTER (WHERE balance."onHandQuantity" <= 0)::integer AS out FROM "stock_balances" balance INNER JOIN "products" product ON product."id" = balance."productId" WHERE product."trackInventory" = TRUE AND product."deletedAt" IS NULL`; return rows[0] ?? { low: 0, out: 0 }; }
