import { AlertTriangle, CheckCircle2, ClipboardList, MapPinned, Truck } from "lucide-react";
import Link from "next/link";
import { PageHeader } from "@/components/shared/page-header";
import { StatCard } from "@/components/shared/stat-card";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { salesOrderStatusConfig } from "@/config/sales-orders";
import { formatCurrencyDecimal, formatDate } from "@/lib/formatters";
import { requireRouteAccess } from "@/services/auth.service";
import { getDeliveryDashboard, getDeliveryOptions } from "@/services/delivery.service";

export const metadata = { title: "การจัดส่ง" };
export default async function DeliveryDashboardPage() { const [access, dashboard, options] = await Promise.all([requireRouteAccess("/delivery"), getDeliveryDashboard(), getDeliveryOptions()]); const canManage = access.permissions.includes("delivery.manage"); return <div className="page-stack"><PageHeader title="การจัดส่ง" description="ติดตามคำสั่งซื้อรอจัดส่ง รอบวันนี้ และผลการจัดส่ง" actions={canManage ? <Button size="sm" asChild><Link href="/delivery/trips/new">สร้างรอบจัดส่ง</Link></Button> : undefined} /><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="คำสั่งซื้อรอจัดส่ง" value={dashboard.waitingOrders} helper="ยืนยันแล้วหรือรอจัดส่งใหม่" icon={ClipboardList} /><StatCard label="รอบที่วางแผนวันนี้" value={dashboard.plannedToday} helper="วางแผนและกำลังขึ้นสินค้า" icon={MapPinned} /><StatCard label="รอบกำลังจัดส่ง" value={dashboard.inProgress} helper="ออกรถแล้ว" icon={Truck} /><StatCard label="จัดส่งสำเร็จวันนี้" value={dashboard.deliveredToday} helper="คำสั่งซื้อ" icon={CheckCircle2} tone="success" /><StatCard label="ไม่สำเร็จรอคืนสินค้า" value={dashboard.failedPending} helper="ต้องตรวจสอบสต็อกบนรถ" icon={AlertTriangle} tone={dashboard.failedPending ? "danger" : "default"} /></section><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>คำสั่งซื้อรอวางแผน</CardTitle><Button size="sm" variant="outline" asChild><Link href="/delivery/trips">ดูรอบจัดส่ง</Link></Button></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-y bg-muted/50 text-left"><tr><th className="px-4 py-2">คำสั่งซื้อ</th><th className="px-3 py-2">ลูกค้า</th><th className="px-3 py-2">ที่อยู่จัดส่ง</th><th className="px-3 py-2">วันที่จัดส่ง</th><th className="px-3 py-2 text-right">ยอดรวม</th><th className="px-4 py-2">สถานะ</th></tr></thead><tbody>{options.orders.slice(0, 10).map((order) => <tr key={order.id} className="border-b last:border-0"><td className="px-4 py-3 font-medium tabular-nums">{order.orderNo}</td><td className="px-3 py-3">{order.customerName}</td><td className="max-w-80 px-3 py-3 leading-6">{order.address}</td><td className="px-3 py-3 tabular-nums">{order.requestedDeliveryDate ? formatDate(order.requestedDeliveryDate) : "—"}</td><td className="px-3 py-3 text-right font-medium tabular-nums">{formatCurrencyDecimal(order.totalAmount)}</td><td className="px-4 py-3"><StatusBadge status={salesOrderStatusConfig[order.status].badge} /></td></tr>)}</tbody></table></div>{!options.orders.length && <p className="p-8 text-center text-sm text-muted-foreground">ไม่มีคำสั่งซื้อรอวางแผนจัดส่ง</p>}</CardContent></Card></div>; }
