"use client";

import type { ColumnDef, PaginationState, SortingState } from "@tanstack/react-table";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { DataTable } from "@/components/shared/data-table";
import { DataTableColumnHeader } from "@/components/shared/data-table-column-header";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { DateRange } from "@/components/shared/date-range";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { customerTypeConfig } from "@/config/customers";
import { paymentTypeConfig, salesOrderStatusConfig } from "@/config/sales-orders";
import type { SalesOrderRow } from "@/features/sales-orders/types";
import { formatCurrencyDecimal, formatDate } from "@/lib/formatters";
import type { SalesOrderListQuery } from "@/validations/sales-order";

export function SalesOrderTable({ rows, total, pageCount, query, canCreate }: { rows: SalesOrderRow[]; total: number; pageCount: number; query: SalesOrderListQuery; canCreate: boolean }) { const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const [search, setSearch] = useState(query.q); function navigate(changes: Record<string, string | number | undefined>) { const params = new URLSearchParams(searchParams.toString()); for (const [key, value] of Object.entries(changes)) if (value === undefined || value === "" || value === "ALL") params.delete(key); else params.set(key, String(value)); router.replace(`${pathname}${params.size ? `?${params}` : ""}`); } useEffect(() => { if (search === query.q) return; const timeout = window.setTimeout(() => navigate({ q: search, page: 1 }), 350); return () => window.clearTimeout(timeout); }, [search, query.q]); // eslint-disable-line react-hooks/exhaustive-deps
  const columns = useMemo<ColumnDef<SalesOrderRow>[]>(() => [{ accessorKey: "orderNo", header: ({ column }) => <DataTableColumnHeader column={column} title="เลขที่คำสั่งซื้อ" />, cell: ({ row }) => <span className="font-medium tabular-nums">{row.original.orderNo}</span> }, { accessorKey: "orderDate", header: ({ column }) => <DataTableColumnHeader column={column} title="วันที่สั่งซื้อ" />, cell: ({ row }) => <span className="whitespace-nowrap tabular-nums">{formatDate(row.original.orderDate)}</span> }, { id: "customer", header: ({ column }) => <DataTableColumnHeader column={column} title="ลูกค้า" />, cell: ({ row }) => <div className="min-w-44"><p className="font-medium">{row.original.customerNameSnapshot}</p><p className="type-caption tabular-nums">{row.original.customerCodeSnapshot}</p></div> }, { accessorKey: "customerType", header: "ประเภทลูกค้า", enableSorting: false, cell: ({ row }) => customerTypeConfig[row.original.customerType].th }, { accessorKey: "saleType", header: "การชำระเงิน", enableSorting: false, cell: ({ row }) => paymentTypeConfig[row.original.saleType] }, { accessorKey: "requestedDeliveryDate", header: ({ column }) => <DataTableColumnHeader column={column} title="วันที่จัดส่ง" />, cell: ({ row }) => row.original.requestedDeliveryDate ? <span className="whitespace-nowrap tabular-nums">{formatDate(row.original.requestedDeliveryDate)}</span> : "—" }, { accessorKey: "totalAmount", header: ({ column }) => <DataTableColumnHeader column={column} title="ยอดสุทธิ" />, meta: { align: "right" }, cell: ({ row }) => <span className="font-medium tabular-nums">{formatCurrencyDecimal(row.original.totalAmount)}</span> }, { accessorKey: "status", header: ({ column }) => <DataTableColumnHeader column={column} title="สถานะ" />, cell: ({ row }) => <StatusBadge status={salesOrderStatusConfig[row.original.status].badge} /> }, { id: "salesperson", header: "ผู้ขาย", enableSorting: false, cell: ({ row }) => row.original.salesperson }], []);
  const activeFilterCount = [query.status, query.saleType, query.customerType].filter((value) => value !== "ALL").length + Number(Boolean(query.dateFrom || query.dateTo)); const filters = <><Select value={query.status} onValueChange={(value) => navigate({ status: value, page: 1 })}><SelectTrigger className="w-full md:w-40" aria-label="สถานะ"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกสถานะ</SelectItem>{Object.entries(salesOrderStatusConfig).map(([value, item]) => <SelectItem key={value} value={value}>{item.th}</SelectItem>)}</SelectContent></Select><Select value={query.saleType} onValueChange={(value) => navigate({ saleType: value, page: 1 })}><SelectTrigger className="w-full md:w-32" aria-label="ประเภทการชำระเงิน"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ทุกการชำระเงิน</SelectItem><SelectItem value="CASH">เงินสด</SelectItem><SelectItem value="CREDIT">เครดิต</SelectItem></SelectContent></Select><Select value={query.customerType} onValueChange={(value) => navigate({ customerType: value, page: 1 })}><SelectTrigger className="w-full md:w-36" aria-label="ประเภทลูกค้า"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">ลูกค้าทุกประเภท</SelectItem><SelectItem value="RETAIL">ลูกค้าปลีก</SelectItem><SelectItem value="WHOLESALE">ลูกค้าส่ง</SelectItem></SelectContent></Select><DateRange hideLabel className="w-full md:w-72" label="ช่วงวันที่สั่งซื้อ" from={{ value: query.dateFrom, onChange: (event) => navigate({ dateFrom: event.target.value, page: 1 }), "aria-label": "วันที่สั่งซื้อเริ่มต้น" }} to={{ value: query.dateTo, onChange: (event) => navigate({ dateTo: event.target.value, page: 1 }), "aria-label": "วันที่สั่งซื้อสิ้นสุด" }} /></>;
  const sorting: SortingState = [{ id: query.sort, desc: query.order === "desc" }]; const pagination: PaginationState = { pageIndex: query.page - 1, pageSize: query.pageSize }; return <DataTable columns={columns} data={rows} searchValue={search} onSearchChange={setSearch} searchPlaceholder="ค้นหาเลขที่คำสั่งซื้อ รหัส หรือชื่อลูกค้า..." filters={filters} activeFilterCount={activeFilterCount} onResetFilters={() => { setSearch(""); router.replace(pathname); }} emptyTitle={query.q || activeFilterCount ? "ไม่พบคำสั่งซื้อที่ตรงกับตัวกรอง" : "ยังไม่มีคำสั่งซื้อ"} emptyDescription={query.q || activeFilterCount ? "ลองเปลี่ยนคำค้นหาหรือล้างตัวกรอง" : "สร้างคำสั่งซื้อฉบับร่างเพื่อเริ่มงานขาย"} emptyAction={!query.q && !activeFilterCount && canCreate ? <Button asChild><Link href="/sales/orders/new">สร้างคำสั่งซื้อ</Link></Button> : undefined} manualPagination manualSorting manualFiltering pageCount={pageCount} totalRows={total} pagination={pagination} onPaginationChange={(next) => navigate({ page: next.pageIndex + 1, pageSize: next.pageSize })} sorting={sorting} onSortingChange={(next) => { const selected = next[0]; if (selected) navigate({ sort: selected.id, order: selected.desc ? "desc" : "asc", page: 1 }); }} pageSizeOptions={[20, 50, 100]} getRowId={(row) => row.id} onRowClick={(row) => router.push(`/sales/orders/${row.original.id}`)} />; }
