"use server";

import { revalidatePath } from "next/cache";
import { requirePermission } from "@/services/auth.service";
import { changePriceListStatus, createPriceList, deactivateCustomerPrice, PricingRuleError, removePriceListItem, resolveProductUnitPrice, saveCustomerPrice, savePriceListItem, updatePriceList } from "@/services/pricing.service";
import { customerPriceDeactivateSchema, customerPriceSchema, priceListFormSchema, priceListItemDeleteSchema, priceListItemSchema, priceListStatusSchema, pricePreviewSchema } from "@/validations/pricing";

export type PricingActionResult = { ok: true; id: string } | { ok: false; message: string };
export type PricePreviewResult = { ok: true; price: Awaited<ReturnType<typeof resolveProductUnitPrice>> } | { ok: false; message: string };
function actionError(error: unknown): PricingActionResult { if (error instanceof PricingRuleError) return { ok: false, message: error.message }; console.error("Pricing action failed", error); return { ok: false, message: "ไม่สามารถบันทึกข้อมูลราคาได้ กรุณาลองอีกครั้ง" }; }
function actor(context: Awaited<ReturnType<typeof requirePermission>>) { return { id: context.user.id === "development-preview" ? null : context.user.id, name: context.user.name }; }
function refreshPriceList(id?: string) { revalidatePath("/price-lists"); if (id) revalidatePath(`/price-lists/${id}`); revalidatePath("/customers"); }

export async function createPriceListAction(input: unknown): Promise<PricingActionResult> { const parsed = priceListFormSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("price_list.manage"); try { const id = await createPriceList(parsed.data, actor(access)); refreshPriceList(id); return { ok: true, id }; } catch (error) { return actionError(error); } }
export async function updatePriceListAction(input: unknown): Promise<PricingActionResult> { const parsed = priceListFormSchema.safeParse(input); if (!parsed.success || !parsed.data.id) return { ok: false, message: parsed.success ? "ไม่พบรหัสรายการราคา" : parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("price_list.manage"); try { const id = await updatePriceList({ ...parsed.data, id: parsed.data.id }, actor(access)); refreshPriceList(id); return { ok: true, id }; } catch (error) { return actionError(error); } }
export async function changePriceListStatusAction(input: unknown): Promise<PricingActionResult> { const parsed = priceListStatusSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("price_list.manage"); try { const id = await changePriceListStatus(parsed.data.id, parsed.data.status, actor(access)); refreshPriceList(id); return { ok: true, id }; } catch (error) { return actionError(error); } }
export async function savePriceListItemAction(input: unknown): Promise<PricingActionResult> { const parsed = priceListItemSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("price_list.manage"); try { const id = await savePriceListItem(parsed.data, actor(access)); refreshPriceList(parsed.data.priceListId); return { ok: true, id }; } catch (error) { return actionError(error); } }
export async function removePriceListItemAction(input: unknown): Promise<PricingActionResult> { const parsed = priceListItemDeleteSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("price_list.manage"); try { const id = await removePriceListItem(parsed.data.id, parsed.data.priceListId, actor(access)); refreshPriceList(parsed.data.priceListId); return { ok: true, id }; } catch (error) { return actionError(error); } }
export async function saveCustomerPriceAction(input: unknown): Promise<PricingActionResult> { const parsed = customerPriceSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("price_list.manage"); try { const id = await saveCustomerPrice(parsed.data, actor(access)); revalidatePath(`/customers/${parsed.data.customerId}`); return { ok: true, id }; } catch (error) { return actionError(error); } }
export async function deactivateCustomerPriceAction(input: unknown): Promise<PricingActionResult> { const parsed = customerPriceDeactivateSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("price_list.manage"); try { const id = await deactivateCustomerPrice(parsed.data.id, parsed.data.customerId, actor(access)); revalidatePath(`/customers/${parsed.data.customerId}`); return { ok: true, id }; } catch (error) { return actionError(error); } }
export async function previewCustomerPriceAction(input: unknown): Promise<PricePreviewResult> { const parsed = pricePreviewSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; await requirePermission("price_list.view"); try { return { ok: true, price: await resolveProductUnitPrice(parsed.data) }; } catch (error) { const result = actionError(error); return { ok: false, message: result.ok ? "ไม่สามารถตรวจสอบราคาได้" : result.message }; } }
