"use server";

import { revalidatePath } from "next/cache";
import { requirePermission } from "@/services/auth.service";
import { changeCategoryStatus, changeProductStatus, changeUnitStatus, createProduct, ProductRuleError, saveCategory, saveUnit, updateProduct } from "@/services/product.service";
import { productCategorySchema, productCategoryStatusSchema, productFormSchema, productStatusSchema, unitSchema, unitStatusSchema } from "@/validations/product";

export type ProductActionResult = { ok: true; id: string } | { ok: false; message: string };
function resultError(error: unknown): ProductActionResult { if (error instanceof ProductRuleError) return { ok: false, message: error.message }; console.error("Product action failed", error); return { ok: false, message: "ไม่สามารถบันทึกข้อมูลสินค้าได้ กรุณาลองอีกครั้ง" }; }
function actor(context: Awaited<ReturnType<typeof requirePermission>>) { return { id: context.user.id === "development-preview" ? null : context.user.id, name: context.user.name }; }
function refreshProduct(id?: string) { revalidatePath("/inventory/products"); if (id) revalidatePath(`/inventory/products/${id}`); }

export async function createProductAction(input: unknown): Promise<ProductActionResult> { const parsed = productFormSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("product.create"); if (parsed.data.status === "INACTIVE") await requirePermission("product.archive"); try { const id = await createProduct(parsed.data, actor(access)); refreshProduct(id); return { ok: true, id }; } catch (error) { return resultError(error); } }
export async function updateProductAction(input: unknown): Promise<ProductActionResult> { const parsed = productFormSchema.safeParse(input); if (!parsed.success || !parsed.data.id) return { ok: false, message: parsed.success ? "ไม่พบรหัสสินค้า" : parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("product.update"); try { const id = await updateProduct({ ...parsed.data, id: parsed.data.id }, actor(access)); refreshProduct(id); return { ok: true, id }; } catch (error) { return resultError(error); } }
export async function changeProductStatusAction(input: unknown): Promise<ProductActionResult> { const parsed = productStatusSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("product.archive"); try { const id = await changeProductStatus(parsed.data.id, parsed.data.status, actor(access)); refreshProduct(id); return { ok: true, id }; } catch (error) { return resultError(error); } }
export async function saveCategoryAction(input: unknown): Promise<ProductActionResult> { const parsed = productCategorySchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("product.update"); try { const id = await saveCategory(parsed.data, actor(access)); refreshProduct(); return { ok: true, id }; } catch (error) { return resultError(error); } }
export async function changeCategoryStatusAction(input: unknown): Promise<ProductActionResult> { const parsed = productCategoryStatusSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("product.update"); try { const id = await changeCategoryStatus(parsed.data.id, parsed.data.isActive, actor(access)); refreshProduct(); return { ok: true, id }; } catch (error) { return resultError(error); } }
export async function saveUnitAction(input: unknown): Promise<ProductActionResult> { const parsed = unitSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("product.update"); try { const id = await saveUnit(parsed.data, actor(access)); refreshProduct(); return { ok: true, id }; } catch (error) { return resultError(error); } }
export async function changeUnitStatusAction(input: unknown): Promise<ProductActionResult> { const parsed = unitStatusSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("product.update"); try { const id = await changeUnitStatus(parsed.data.id, parsed.data.isActive, actor(access)); refreshProduct(); return { ok: true, id }; } catch (error) { return resultError(error); } }
