"use server";

import { revalidatePath } from "next/cache";
import { createStockAdjustment, createStockTransfer, changeWarehouseStatus, InventoryRuleError, saveWarehouse, WarehouseRuleError } from "@/services/inventory.service";
import { requirePermission } from "@/services/auth.service";
import { stockAdjustmentSchema, stockTransferSchema, warehouseFormSchema, warehouseStatusSchema } from "@/validations/inventory";

export type InventoryActionResult = { ok: true; id: string } | { ok: false; message: string };
function actor(context: Awaited<ReturnType<typeof requirePermission>>) { return { id: context.user.id === "development-preview" ? null : context.user.id, name: context.user.name }; }
function errorResult(error: unknown): InventoryActionResult { if (error instanceof InventoryRuleError || error instanceof WarehouseRuleError) return { ok: false, message: error.message }; if (typeof error === "object" && error && "code" in error && (error.code === "P2034" || error.code === "P2002")) return { ok: false, message: error.code === "P2002" ? "รหัสคลังสินค้านี้ถูกใช้งานแล้ว" : "สต็อกมีการเปลี่ยนแปลงพร้อมกัน กรุณาตรวจสอบข้อมูลแล้วลองอีกครั้ง" }; console.error("Inventory action failed", error); return { ok: false, message: "ไม่สามารถดำเนินการสต็อกได้ กรุณาลองอีกครั้ง" }; }
function refreshInventory() { revalidatePath("/inventory/stock"); revalidatePath("/inventory/movements"); revalidatePath("/inventory/warehouses"); }

export async function saveWarehouseAction(input: unknown): Promise<InventoryActionResult> { const parsed = warehouseFormSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("inventory.manage_warehouse"); try { const id = await saveWarehouse(parsed.data, actor(access)); refreshInventory(); return { ok: true, id }; } catch (error) { return errorResult(error); } }
export async function changeWarehouseStatusAction(input: unknown): Promise<InventoryActionResult> { const parsed = warehouseStatusSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("inventory.manage_warehouse"); try { const id = await changeWarehouseStatus(parsed.data.id, parsed.data.status, actor(access)); refreshInventory(); return { ok: true, id }; } catch (error) { return errorResult(error); } }
export async function createStockAdjustmentAction(input: unknown): Promise<InventoryActionResult> { const parsed = stockAdjustmentSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("inventory.adjust"); try { const id = await createStockAdjustment(parsed.data, actor(access)); refreshInventory(); return { ok: true, id }; } catch (error) { return errorResult(error); } }
export async function createStockTransferAction(input: unknown): Promise<InventoryActionResult> { const parsed = stockTransferSchema.safeParse(input); if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? "ข้อมูลไม่ถูกต้อง" }; const access = await requirePermission("inventory.transfer"); try { const id = await createStockTransfer(parsed.data, actor(access)); refreshInventory(); return { ok: true, id }; } catch (error) { return errorResult(error); } }
